### ISSUE TITLE
What i have to do to obtain the geometry of Walls, columns, slabs, etc?

### ISSUE THREAD

**Issue by IFChaos** [xBimTeam/XbimGeometry#1]
Hello, I'm not sure it is the correct place to ask it, if it's not please redirect me:

I'm new in Xbim, and I need to obtain all the geometric data of an object in order to represent it. At the moment i'm using the next code

            if (OpenFile.ShowDialog() != DialogResult.Cancel)
            {
                Wnd.IFCModel.CreateFrom(OpenFile.FileName, "temp.xbim");
                Wnd.IFCModel.Close();
                Wnd.IFCModel.Open("temp.xbim", Xbim.XbimExtensions.XbimDBAccess.ReadWrite);
                var TotalColumns = Wnd.IFCModel.Instances.OfType<Xbim.Ifc2x3.SharedBldgElements.IfcColumn>();
                int num = TotalColumns.Count();
                for (int i = 0; i < num; i++)
                {
                    //Now what i have to do to obtain columns, walls, slabs, geometry??
                }
            }

But i'm completely blocked at this point, i have no idea what to do now, i tried it by myself, but after spending many days without result i need help. I need something to began with, at least to obtain the cartesian points and the 3dplacement coordinates.

Thank you in advance.

**Comment by andyward** [comment]
I make a little demo app at https://github.com/andyward/XBimDemo which might help. It shows how to parse the model and generate IFC and then work the Geometry Context. I've used the BoundingBoxes to show the bounds rather than the meshes. The XYZ needs converting to World Coordinates. Best to look at XbimWebUI if you want to see how to do this.

![image](https://cloud.githubusercontent.com/assets/923699/8205943/0db67e2a-14ed-11e5-818f-2813daec38f5.png)

**Comment by IFChaos** [comment]
Thank you.

I have a new problem with geometry, i have an IFC file that Xbim seems unable to load properly.
When i open this IFC file using XbimXplorer many objects are missing. But these objects are visible using SOLIBRI.
If i could send this file to you, then maybe you will be able to detect where is the problem.

**Comment by tulip411** [comment]
> I made a little demo app at https://github.com/andyward/XBimDemo which might help. It shows how to parse the model and generate IFC and then work the Geometry Context. I've used the BoundingBoxes to show the bounds rather than the meshes. The XYZ needs converting to World Coordinates. Best to look at XbimWebUI if you want to see how to do this.
> 
> ![image](https://cloud.githubusercontent.com/assets/923699/8205943/0db67e2a-14ed-11e5-818f-2813daec38f5.png)

**************************************************************************************
Hi! It seems that the demo you provided is based on the old version of Xbim. I tried to compile but there are still some issues.

Could you please update this demo?

Thank you!
Maggie
