### ISSUE TITLE
Taking a too much time to convert from ifc to wexbim 

### ISSUE THREAD

**Issue by Marks10** [xBimTeam/XbimGeometry#10]
Hi ,
I am trying to convert 600MB ifc file ,It is converted but it takes a near about 1 hour for that.
Please help me to reduce time for this.

My hardware configuration is as follws:
1) NVIDIA Graphics card - 2gb
2)
![configure](https://cloud.githubusercontent.com/assets/16130194/11558654/e989532a-99d9-11e5-9b2c-ac82b494de37.png)

**Comment by CBenghi** [comment]
Hello @Marks10,
the conversion time you mention seems disproportionate.
Can you find a way to provide me with the model to run some tests? I can provide NDA, if needed.
If you prefer taking this private my email il claudio.benghi@gmail.com

Best,
Claudio

**Comment by SteveLockley** [comment]
600MB models if they contain a lot of boolean operations can take normally 2-5 minutes, it is computationally intensive, the most likely problem is you have complex geometries (i.e. a lot of openings cut a wall) look for the objects that are taking the time. In the geometry engine package there is a utility called profiler run this with your IFC file as an argument it will give you timings and help you see what is causing the problem.
