### ISSUE TITLE
Problem with IfcProduct.transform after updating to ifc4 

### ISSUE THREAD

**Issue by FrieBIM91** [xBimTeam/XbimGeometry#103]
Hi Team,
@martin1cerny 
@CBenghi 

I am facing issues in getting the ifcproduct transformations while using the new version agnostic upgrade of xbim.
I was using this code to get the position and rotation of the ifcproduct:

  
```
IfcProduct p = o as IfcProduct; // o is of type iifcObjectDefenition

XbimVector3D t = new XbimVector3D();
XbimQuaternion r = new XbimQuaternion();

var plc = p.ObjectPlacement;
if (plc != null)
{
t = plc.ToMatrix3D().Translation;
r = plc.ToMatrix3D().GetRotationQuaternion();    
}

```
now, using the **Xbim.Ifc4.ProductExtension** namespace, I'm not able to access the transform property anymore. In other words, the **variable plc does not have the ToMatrix3D() function anymore!**

Could you please point me to a documentation on this issue or provide a sample code to get the object transformations in the update?

Thanks in advance,
Frieder

**Comment by andyward** [comment]
Looks like you need to pass the IIfcObjectPlacement into the `XbimGeometryEngine`

See:

https://github.com/xBimTeam/XbimGeometry/blob/08920df29f909dde0c4f65c63d80ae0b5540025f/Xbim.Geometry.Engine.Interop/XbimGeometryEngine.cs#L442
