### ISSUE TITLE
Exception while converting IFC file to wexbim

### ISSUE THREAD

**Issue by Dhruti03** [xBimTeam/XbimGeometry#105]
Hello,
I'm facing an exception while converting IFC file to wexbim. While creating context it gives exception on line "WriteShapeGeometries(contextHelper, progDelegate, geometryTransaction, geomStorageType);". I have attached the snap of exception and IFC file.

[TestModel.zip](https://github.com/xBimTeam/XbimGeometry/files/1886128/TestModel.zip)

![3dconvertexception](https://user-images.githubusercontent.com/30585303/38452581-aeb2b222-3a64-11e8-8a22-c5a96a4c02f5.png)

Thanks.

**Comment by martin1cerny** [comment]
Is your application multithreaded?

**Comment by adam9000** [comment]
I'm facing the same exact problem, on my production enviroment (Windows Server 2008 R2).

Maybe some dependency is missing???

**Comment by andyward** [comment]
@adam9000 Is it a specific model failing to process, or all models?

The error above is indicative of an error hitting an edge case in the geometry engine, so I doubt it relates to a dependency missing.

What version of XBIM are you running? If it's V5 then it may be you're impacted by #154 if running on Server 2008 R2. (Bearing in mind 2008R2 is 4 years out of mainstream support by MS, and will be totally unsupported in 9 months, you may want to look at a newer OS!)

**Comment by adam9000** [comment]
Hi Andy

Thank you for the help.

Yes, its the V5 version, and seams to me that I'm in the impact zone :S

We are working on the upgrade process to a newer SO right now.

Thanks again!!!

**Comment by andyward** [comment]
Original issue is still occurring in 5.0.216-develop. Tried single-thread Geometry but still and issue, so looks like a data issue

**Comment by andyward** [comment]
Can you retest in the latest 5.1.307 Geometry in develop. I've just opened the model file in the latest explorer. There's a lot of warnings but it does complete.
