### ISSUE TITLE
Can't work with <2 floor BIM house.ifc> file. Xbim3DModelContext.CreateContext() fails. 

### ISSUE THREAD

**Issue by KosMoY** [xBimTeam/XbimGeometry#110]
Work with attached file <2 floor BIM house.ifc> causes error. 
There are not unique IIfcRelAggregates by RelatingObject in Model.Instances

Xbim3DModelContext.cs
private void GetOpeningsAndProjections()
{                var compoundElementsDictionary =
                    Model.Instances.OfType<IIfcRelAggregates>()
                        .Where(x => x.RelatingObject is IIfcElement)

// Duplication key insertion exception here
                        .ToDictionary(x => x.RelatingObject, y => y.RelatedObjects); 
                     ...
}

Most of IFC viewers works with the file correctly. (Solibry process this file fine)

#### Versions of xBIM Packages:

- xBIM Essentials: 
- xBIM Geometry: 

#### Minimal code (or steps) to reproduce the issue:
```cs
using (var model = IfcStore.Open(file.ifc))
{
    _xbimModel = IfcStore.Open(@"2 floor BIM house.ifc",...);
    _xbim3DModelContext = new Xbim3DModelContext(_xbimModel);
    _xbim3DModelContext.CreateContext();
}
```

#### Minimal file to reproduce the issue:

[2 floor BIM house.zip](https://github.com/xBimTeam/XbimGeometry/files/2044555/2.floor.BIM.house.zip)

**Comment by martin1cerny** [comment]
This has been [fixed](https://github.com/xBimTeam/XbimGeometry/blob/develop/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L290) more than a year ago in the `develop` branch.

**Comment by CBenghi** [comment]
Martin, this probably means we are overdue a master release!
:-)

**Comment by LloydPickering** [comment]
I'd argue if you've gone more than 6 months without a master release it's
probably well overdue! ;) Ideally monthly or 3 monthly schedules might be
better.

**Comment by martin1cerny** [comment]
Yes, agreed. Shall we split the process? I can push changes to XbimEssentials master in next few days. Claudio, could you push changes to XbimGeometry? I agree it would be best to set up some kind of predictable schedule.

**Comment by CBenghi** [comment]
Yep, as mentioned in the other thread.
Occ 7.3 is on its way and then new classes of ifc4 and ifc4.1.
Perhaps a couple of weeks and we can happily be up to speed again.
C

**Comment by CBenghi** [comment]
I've created a branch with opencascade 7.3 but there are some regressions that need understanding.
https://github.com/xBimTeam/XbimGeometry/tree/feature/occ730
It might take a little bit longer than I hoped.

**Comment by martin1cerny** [comment]
Claudio has asked to hold on until he implements validation rules for the new classes in Essentials and investigate these regressions mentioned above.

**Comment by martin1cerny** [comment]
I haven't heard from Claudio yet.

**Comment by andyward** [comment]
Should go with v5

**Comment by andyward** [comment]
Opens fine in v5
![image](https://user-images.githubusercontent.com/923699/49660300-22966c80-fa3e-11e8-99a4-09953dcab798.png)
