### ISSUE TITLE
Compilation issue on development branch

### ISSUE THREAD

**Issue by I-Sokolov** [xBimTeam/XbimGeometry#111]
Cloned and tried to build development branch I'm observing errors below.
Have you any ideas on this?

1>------ Build started: Project: Xbim.Geometry.Engine.Interop - VS2015, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.Common". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.Ifc4". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.Tessellator". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.

**Comment by andyward** [comment]
Old issue, but have you tried a manual `nuget restore`?
