### ISSUE TITLE
 Real time change

### ISSUE THREAD

**Issue by mbow1** [xBimTeam/XbimGeometry#114]
hi
I try to modify the properties "wind openning angle" but even it changes the window remains open.
I would like to see if there is a way to close the window with C # for an ifc and Wexbim file, saved the file.
if it is possible that I can see it in real time on xbim web viewer it's even better
I really need you ..
thank you in advance

![41358664-c4c537ba-6f20-11e8-8366-c7f34dc8cca3](https://user-images.githubusercontent.com/24434347/41475494-3d170078-70bf-11e8-9fce-063dc585eb2b.PNG)

**Comment by andyward** [comment]
These properties aren't really linked to the 3D representation in a meaningful way. PropertySets are mostly data generated, inferred or manually entered in the authored model - not the data that drives the geometry.

If you wanted to implement dynamic 3D modeling you'd need to investigate some of IFC parametric capabilities, and figure out how to transform the element in the view. 

I think that's probably beyond the scope of what we can resolve in a GH issue. StackOverflow might be a good place to take this to.
