### ISSUE TITLE
Color inheritance

### ISSUE THREAD

**Issue by Tpullmann** [xBimTeam/XbimGeometry#118]
Hi,

I've got an ifc file which shows colored elements in various viewers (incl. Tekla BimSight) , but not in XBim. Obviously the inheritance of colors from IFCGroups is not implemented here.

[Tubes without colors.zip](https://github.com/xBimTeam/XbimGeometry/files/2149845/Tubes.without.colors.zip)

**Comment by martin1cerny** [comment]
Hi @Tpullmann , I'll have alook.

**Comment by Tpullmann** [comment]
Hi, did you have a chance to investigate a bit?

**Comment by martin1cerny** [comment]
Hi @Tpullmann, I did have a look and problem is that colour representation is defined for maps in this file which is not very common. Styling is usually defined elsewhere in the hierarchy. Saying so, this way of definition is valid as well. But xBIM Geometry didn't expect it there.

**Comment by Tpullmann** [comment]
Hi @martin1cerny,
thanks a lot. So for now I will manually "fix" this (to satisfy the customers). 
Do you consider to process this unusual representation in xBIM Geometry in future, or is it too far away from standard?

**Comment by andyward** [comment]
Adding to v5 as it looks we have started a fix

**Comment by andyward** [comment]
Current state in v5

![image](https://user-images.githubusercontent.com/923699/49661196-58d4eb80-fa40-11e8-8ac3-dba21c8b4aad.png)

Assume this is correct?
