### ISSUE TITLE
How I can to calculate a distance between two element of ifc model data?

### ISSUE THREAD

**Issue by soniagagliardi** [xBimTeam/XbimGeometry#12]
Hi,

I'm working on a project that uses the xBIM Toolkit. I need to calculate a distance between two elements of IFC data model. Example: between two Walls, between a Door and a window, ecc..

How can I do this?

**Comment by LloydPickering** [comment]
What exactly do you mean by distance between two elements? How accurate do you need it to be?

1. If you want a rough guide, grab the bounding box for each item and check the distance between the centre points (as per http://freespace.virgin.net/hugo.elias/routines/r_dist.htm).

2. If you want the minimum distance between the nearest part of each object (ie accuracy is really important) then you need to iterate over each triangle forming the 3d geometry and perform the above calc for each against the other object's triangles. This is a VERY CPU intense calculation (it will be big-o something like O(n2) ). There may be ways to optimise this a bit, but no matter what you are trying to achieve, it's basically going to be CPU intensive. 

A happy medium might be to do option 2 but only use the bounding boxes. It might be accurate enough for what you are trying to achieve.

It really depends on what your goal is, and how accurate you need it to be.

**Comment by CBenghi** [comment]
Closing for long inactivity, please reopen if needed.

**Comment by satregiftc** [comment]
Hi

we are able to display wexbim map on the web browser and able to do few basic viewer functionalities using xViewer. similar to this do we have any redline/markup tool available to display on the map using xViewer. please getback to me if any API is available display measure/Annotation on the map
using xViewer API

Thanks for your suport

Thank you 
Satish
