### ISSUE TITLE
[QUESTION] WexBim region meaning ?

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimGeometry#121]
Hello,
I have just a simple question, the thing you called region in your file, which is the corresponding ifc element behind ?
Is it the BuildingStorey ?

Thanks !

**Comment by LloydPickering** [comment]
I'm not very familiar with the Wexbim side of things, but further down the stack, the XbimRegion doesn't have an IFC mapping that I am aware of. 

It's is a concept which was generated internal to Xbim to try and detect when models are out of alignment in a significant way. If you have 2 models 1km/1mile apart, you federate, and you Zoom Extents - the items are going to be so small you are going to think they haven't loaded as the screen will just look empty. In this scenario testing the Regions will show that you have 2 distinct regions of geometric data, and not a single one. Checking the distance between them will show that they are literally km/miles away from each other. If the models are in the same rough location, it should show as a single region.

The benefit of doing this (other than detecting when you have models out of alignment) is that you can potentially zoom to the coords of the region as you know them in advance, and move between the two models, though doing this is beyond scope of this post :)

**Comment by liszto** [comment]
Ok. I start to read the code just after my question cause I didn't read this part before and indeed it's that.
I asked this cause I'm generate 3D element in Unity based on this file. But all the pivot seems to be "bad" cause in unity logic the pivot must be the center of the object but it seems in wexBim file it will be the min of the bounding box. If I'm right.
So I try to find a way to have all element with the good bounding box position (even for site / building / buildingstorey . etc...) to make them interactable for the user. 

So it's currently for me at least quite a pain to use this to generate a "logic unity" rendering. The rendering is good but not the pivot / bounding box logic based on this file.

At least thanks for this region explanation, I can continue to ignore this parameter at least :)
