### ISSUE TITLE
"model=ifcstore.open(file)" if the model contains all informations of ifc data?

### ISSUE THREAD

**Issue by Febfire** [xBimTeam/XbimGeometry#124]
I try to convrt ifc to json,it woks
Unfortunately,it unly contains the geometry data but lack of property data.
So,if is viable to convert json absolutely?
thanks advence.

**Comment by Febfire** [comment]
And what means of the json that convert from xbimExchange->Xbim.COBieLiteUK.Client?

**Comment by martin1cerny** [comment]
I'm sorry but I don't understand your question.
