### ISSUE TITLE
Xbim3DModelContext not found

### ISSUE THREAD

**Issue by Dakki97** [xBimTeam/XbimGeometry#125]
I have installed every library by the xBim Team available on NuGet. I figured the class is part of Xbim.ModelGeometry.Scene but there is no Scene in Xbim.Geometry just Xbim.Geometry.Converter.

![image](https://user-images.githubusercontent.com/1222525/43829055-5e392c4a-9afe-11e8-925d-3706b024a6c3.png)

I use VS17 and my application targets .NetCore

**Comment by Dakki97** [comment]
Tried it with .NetFramework as target and works.
Can we please have .NetCore Support

**Comment by CBenghi** [comment]
Geometry is a C++ /clr lib; net core support would take a substantial amount of work; it's in our desire to do it but it's contingent on available resources.
Thanks,
Claudio
