### ISSUE TITLE
Failed to write ifcxml file

### ISSUE THREAD

**Issue by Febfire** [xBimTeam/XbimGeometry#126]
#### Expected behavior:

*Screenshot or image of desired state:*

#### Actual behavior or exception details:
When i save ifc as ifcxml,an error occured: Failed to write ifcxml file.
and i got an incomplete ifcxml file.

*Screenshot or image of desired state:*
![image](https://user-images.githubusercontent.com/37166494/43884137-dd47455a-9be7-11e8-9dfc-f8aaa06855b3.png)

#### Versions of xBIM Packages:

- xBIM Essentials: 
- xBIM Geometry: 

#### Minimal code (or steps) to reproduce the issue:
```cs
using (var model = IfcStore.Open(file.ifc))
{
    ...
}
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*

**Comment by martin1cerny** [comment]
I'm sorry but we can only help you with this kind of issue if you provide us with the original file. Also, this has nothing to do with Geometry and should be moved to [XbimEssentials](https://github.com/xBimTeam/XbimEssentials/issues).

**Comment by Febfire** [comment]
Thanks,martin1cerny.
I means that if the ifc file is large such as 13 Mb,the error "failed to write ifcxml file"will occur.
If the ifc file is small,it works well.

**Comment by martin1cerny** [comment]
This is weird because xBIM doesn't have any limit on the size of IFC files. Can you provide us with one such a file?

**Comment by Febfire** [comment]
[


](url)

**Comment by Febfire** [comment]
[SampleBuilding.zip](https://github.com/xBimTeam/XbimGeometry/files/2286326/SampleBuilding.zip)

**Comment by martin1cerny** [comment]
Your file seems to contain some invalid XML characters: https://stackoverflow.com/a/8256631/6345585
