### ISSUE TITLE
The concept of ContextWcsAdjustment need to be reviewed in the geometry engine.

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimGeometry#128]
#### Expected behavior:

Meshed models should be fully independent when it comes to world transform.

#### Actual behavior or exception details:

Models need to be interpreted knowing what configuration of wcs transform has been used in the meshing stage.

#### Versions of xBIM Packages:

- xBIM Geometry: develop and master branches 

#### Minimal code (or steps) to reproduce the issue:

Creating a file with adjustWcs false and reading it with adjustWcs at true produces unexpected transformation errors when dealing with federations.

#### Minimal file to reproduce the issue:
Any models that have an offset from the 0,0,0 transform.

**Comment by martin1cerny** [comment]
@Claudio, what do you mean by this?

> reading it with adjustWcs at true

My understanding is that
  * The mesh **is independent**. It is only stored in its local coordinates.
  * All transformations are stored independently for every shape instance
  * When `adjustWcs` is set to `true`, its value is stored as WCS of the region(s)
  * When the geometry is read from the store, it should check the region WCS to see if it has some global displacement.
  * For the federation absolute placement (including any global WCS) should be always considered to allow models using different local local origin.

**Comment by andyward** [comment]
Should be closed in 5.1
