### ISSUE TITLE
Error on rendering IfcTriangulatedFaceSet

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#129]
Hi,
while testing our software due to IFC4 we found some customer files where the IfcTriangulatedFaceSet geometry doesn't work correctly. This occurs both via XBimGeometry (Xbim.Geometry.Engine.Interop ) and  XbimWindowsUI. 

Maybe this also refers to issue: "Not rendering IfcTriangulatedFaceSet correctly ( but other IFC viewers can)" # 89 in XbimWindowsUI

I found an example file from [IFC4 Documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/) attached to this issue where you can reproduce the effect.

Guenter

[column-straight-rectangle-tessellation.zip](https://github.com/xBimTeam/XbimEssentials/files/2344979/column-straight-rectangle-tessellation.zip)

**Comment by bekraft** [comment]
Hey, I've found the issue within the XbimEssentials / XbimTesselator project. Just opened a new PR. See https://github.com/xBimTeam/XbimEssentials/pull/211.

I'm not sure about the overall intention how to implement the different initialisation cases for IfcTriangulatedFaceSet. Up to now, the code only distinguishes into 2 cases having normals or not. It doesn't care about given normal Indexes...

**Comment by SteveLockley** [comment]
I believe with the help of bekraft which has been put in release 5 this is resolved to a large extent, there are still other issues with simple triangulation we are looking at though
