### ISSUE TITLE
Esnet PermissionDenied exception on trying to save as wexbim

### ISSUE THREAD

**Issue by chirdeeptomar** [xBimTeam/XbimGeometry#13]
I have downloaded the pre release of xbim.geometry and essentials from https://www.dropbox.com/sh/srhs5jfc1nwavqb/AADOvjwclPIGnxq5h27Rkbfna following one of the discussions on github as I had the same issue with unable to find xbim.geometry.engine32.dll.

I am currently referencing the pre-release and I have manually copied x64 and x86 folders in to my calling project which is a web api project. I am getting a PermissionDeniedEception which leaves me clueless.

![error](https://cloud.githubusercontent.com/assets/77834/12235250/747eec52-b86a-11e5-9bf5-558df5b27285.png)

**Comment by CBenghi** [comment]
Your web account does not seem to have some permission.
My guess is that the folder you are trying to write to is not under your control.
Can you try to save to that folder with a normal file streamer (i.e. no use of any xbim api)?

**Comment by chirdeeptomar** [comment]
@CBenghi I am just saving in App_Data folder in my web API. IFC file uploads and Xbim model database are already being written to this folder.

**Comment by CBenghi** [comment]
Si the model o opened in readWrite mode?
Have you tried opening it in exclusive mode, maybe.

**Comment by chirdeeptomar** [comment]
@CBenghi That did the trick model.Open(xbimDatabase, XbimDBAccess.Exclusive);
