### ISSUE TITLE
How to read geometry such as vertices, indices and normals?

### ISSUE THREAD

**Issue by Dakki97** [xBimTeam/XbimGeometry#130]
I am trying to read vertices indices and normals to create a datamodel so I can draw meshes in a custom viewer. There seems to be no example of how to get this information. The only example I found tries to use context.CreateContext(), which does not work due to an external error.

I use VS2017.

How is this achieved?

**Comment by martin1cerny** [comment]
`context.CreateContext()` is the right way to do this. It will process all the geometry and make it available in `IModel.GeometryStore` where you can read it and access all vertices, indices and normals. You will need to be more specific about the external error, and possibly provide the IFC file you are trying to process or its part.

**Comment by Dakki97** [comment]
![image](https://user-images.githubusercontent.com/1222525/47292916-cf409a00-d608-11e8-901d-ac2b87b90c36.png)
This is the error I get.
Looking at the context instance I cannot find a CreateContext() method.

**Comment by martin1cerny** [comment]
I'm sorry but you will need to post a repeatable code snippet or sample project including some testing data. I'm sure you will appreciate this is not enough to do anything.

**Comment by Dakki97** [comment]
Hello, I edited my previous comment. Thanks for the help

**Comment by Dakki97** [comment]
Github seems to bug out, with my comment so I will post it here again

[IFC_Simplifiziert.zip](https://github.com/xBimTeam/XbimGeometry/files/2501402/IFC_Simplifiziert.zip)

```
using System;
using System.Linq;
using Xbim.Ifc;
using Xbim.Ifc2x3.Interfaces;
using Xbim.ModelGeometry.Scene;
using Xbim.Common.Geometry;
using System.Collections.Generic;
using Xbim.Presentation;

namespace IFCParser
{
    class Program
    {
        static void Main(string[] args)
        {

            using (var model = IfcStore.Open("C:\\Users\\Daniel Ignjat\\Desktop\\Plaene\\IFC_Simplifiziert.ifc"))
            {
                //if (model.GeometryStore.IsEmpty)
                //{
                //    var context = new Xbim3DModelContext(model);
                //    context.CreateContext();
                //}
                using (var txn = model.BeginTransaction("Vertices"))
                {
                    var context = new Xbim3DModelContext(model);
                    context.CreateContext();

                    var relevantProducts = new IIfcProduct[0]
                        .Concat(model.Instances.OfType<IIfcWall>())
                        .Concat(model.Instances.OfType<IIfcWallStandardCase>())
                        .Concat(model.Instances.OfType<IIfcSlab>())
                        .Concat(model.Instances.OfType<IIfcFooting>())
                        .Concat(model.Instances.OfType<IIfcColumn>());
                    List<double> positions;
                    List<double> normals;
                    List<int> triangleIndices;


                    txn.Commit();
                    Console.ReadLine();



                }
            }

        }
    }
}

```

**Comment by martin1cerny** [comment]
Using the latest xBIM Essentials and xBIM Geometry your file is processed without any warnings or errors:
![image](https://user-images.githubusercontent.com/773078/47294319-03b65500-d60d-11e8-92c7-88456dca91c7.png)

**Comment by Dakki97** [comment]
I can also see that u target 4.5.2 and use newer versions which are unable on nuGet. How do I get these newer versions?

**Comment by martin1cerny** [comment]
You will find relevant sources on the first page: http://docs.xbim.net

**Comment by Dakki97** [comment]
Yes I found that and implemented it, but I still get the Exception

**Comment by martin1cerny** [comment]
The exception is thrown by the system and we can't help you if you don't provide a repeatable example. You can start with [this](https://github.com/xBimTeam/XbimSamples/tree/master/CreateWexBIM).

**Comment by mwymwy** [comment]
Please make sure you have all required DLL in your bin folder, including
"x86" and "x64" folders which contain the native dll for geometry engine.

This exception is frequently related to those dlls missing.

You can take a start from an existing and working application project (xbim
xplorer), this way you won't be fooled by missing anything critical at
runtime.

mwy


Le mar. 23 oct. 2018 à 12:06, Martin Černý <notifications@github.com> a
écrit :

**Comment by Dakki97** [comment]
I reinstalled everything and got a new IFC File and it works now. I guess it was an issue inside the IFC.

Now that I can read geometry, I can return to my actual question...

```
                var instances = context.ShapeInstances();
                foreach (var instance in instances)
                {
                    var geometry = context.ShapeGeometry(instance);
                    var data = ((IXbimShapeGeometryData)geometry).ShapeData;
                    using (var stream = new MemoryStream(data))
                    {
                        using (var reader = new BinaryReader(stream))
                        {
                            var mesh = reader.ReadShapeTriangulation();
                          
                                
                                
                            }
                        }
                    }
                }

```

I have my mesh, I can read vertices, indices and normals via the face.. but how is this mapped to the corresponsing IFCProduct. There is a IFCProductlabel which returns some number, but how do I get the reference to the IFCProduct

**Comment by martin1cerny** [comment]
This is another question. You can read the geometry mesh now. And the file was OK because I could process it with no problems (see [above](https://github.com/xBimTeam/XbimGeometry/issues/130#issuecomment-431831902)).

**Comment by Dakki97** [comment]
True then I will close this issue as the question has been answered
