### ISSUE TITLE
Question:  integration with FreeCAD...?

### ISSUE THREAD

**Issue by luzpaz** [xBimTeam/XbimGeometry#133]
There has been a lot going on with BIM over in the FreeCAD (the cross-platorm FOSS parametric CAD/CAM project)
One of the main devs is an architect, he's developing and [blogging](http://yorik.uncreated.net/guestblog.php?2018=536) a lot of BIM these days. Perhaps there is an interest in the Xbim community to make a connection ?

**Comment by martin1cerny** [comment]
We are aware of FreeCAD and we have OpenCascade engine in common with it. Do you think about anything specific?

**Comment by luzpaz** [comment]
Great. Maybe I can list a few places you may want to intermittently track (or even participate) ? :man_shrugging: 

* [FreeCAD IFC subforum](https://forum.freecadweb.org/viewforum.php?f=39)
* [Upstream OCC Bugs in the FreeCAD Bugtracker(https://forum.freecadweb.org/viewtopic.php?t=20264)

**Comment by martin1cerny** [comment]
Closing this issue as it will stay there for a reference.
