### ISSUE TITLE
OpenCascade Exception when Creating Grids

### ISSUE THREAD

**Issue by kikootwo** [xBimTeam/XbimGeometry#135]
Hello,

If you have instantiated an IFCGRID type, and have not defined these lines:

`#43= IFCDIMENSIONALEXPONENTS(1,0,0,0,0,0,0);`
`#44= IFCMEASUREWITHUNIT(IFCRATIOMEASURE(0.3048),#42);`
`#45= IFCCONVERSIONBASEDUNIT(#43,.LENGTHUNIT.,'FOOT',#44);`

XbimXplorer will throw this exception 
![image](https://user-images.githubusercontent.com/14036771/42663541-eff83c8a-8603-11e8-8e53-da903cbe9a62.png)

To recreate this bug, remove your reference to IFCCONVERSIONBASEDUNIT from unit assignment in any file with an IFCGRID. Please let me know if you need any additional information.

EDIT: Forgot to mention, the grid must have at least one grid axis.

**Comment by andyward** [comment]
Do we have a test file to confirm this fix?

**Comment by SteveLockley** [comment]
kikootwo can you provide a file for this please. Just removing the Conversion based unit line seems odd, why do you want to do this? I suspect if you do so the units and the model precision will mismatch. i.e. The model will default to millimeters and everything will be approx 3 times smaller but you precision will still be the same.

**Comment by AllanCrow** [comment]
I am having the exact same issue with an IFC file.  It loads with errors and warnings in Explorer but when in debug mode it crashes. The error is System.StackOverflowException

` var model = IfcStore.Open(dlgFileName);
            if (model.GeometryStore.IsEmpty)
            {
                // Create the geometry using the XBIM GeometryEngine
                try
                {
                    var context = new Xbim3DModelContext(model);

                    context.CreateContext(); //Crashes here <----------------------`

I have tried in XbimXplorer & Xbim.Presentation the following packages
Xbim.Geometry (5.1.430) & (5.1.403)
Xbim.Geometry.Engine.Interop (5.1.403) & (5.1.403)

I can share the IFC file if need be.

I have searched the Internet up and down and cannot find a solution!!!!

Please help.
