### ISSUE TITLE
 Boolean operations on walls

### ISSUE THREAD

**Issue by WENTBY** [xBimTeam/XbimGeometry#136]
Hi:

Is there any examples about boolean operations on walls? I hope to dig holes in a wall. Thanks!

**Comment by martin1cerny** [comment]
You might want to start [in the IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcrelvoidselement.htm). You will need to define the opening in the IFC schema. If you do it right, geometry engine will process it and will cut the hole. So, I suggest you study the schema and existing files first.

**Comment by andyward** [comment]
There's some tests that might be useful : https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Tests/IfcBooleanTests.cs

**Comment by SteveLockley** [comment]
I have all of these in

Steve Lockley
Mob: 079 67 600 923

________________________________

**Comment by WENTBY** [comment]
Thank you all, I think I will learn more about the information you provide.
