### ISSUE TITLE
How to get the geometry of opening elements?

### ISSUE THREAD

**Issue by Dakki97** [xBimTeam/XbimGeometry#138]
I need to get the geometry of the opening elements so that I can cut holes into my walls.
Currently I am reading the vertices of walls, but the vertices do not include the holes inside the elements.
In order to be able to calculate the correct volume and visualize correctly I would use the vertices of the OpeningElements to cut the walls.

How is this achieved?

**Comment by andyward** [comment]
Do you want to take a look at #136 ? Sounds like a similar question

**Comment by Dakki97** [comment]
I do not think that this applies, since the only test that uses a opening element requires me to know what specific instance the ifcopeningelement is, which I do not know.
What I basically want to do is to read geometry of an openingelement which belongs to a e.g. wall in order to provide the vertices of the openingelement to the visualization step

**Comment by martin1cerny** [comment]
You might want to check something like this:

```cs
using System.IO;
using System.Linq;
using Xbim.Common.Geometry;
using Xbim.Common.XbimExtensions;
using Xbim.Ifc;
using Xbim.Ifc4.Interfaces;
using Xbim.ModelGeometry.Scene;

namespace Sample
{
    class Program
    {
        public static void Main()
        {
            const string fileName = @"SampleHouse.ifc";
            using (var model = IfcStore.Open(fileName, null, -1))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                using (var geom = model.GeometryStore.BeginRead())
                {
                    var openings = model.Instances.OfType<IIfcOpeningElement>();
                    foreach (var opening in openings)
                    {
                        var instances = geom.ShapeInstancesOfEntity(opening.EntityLabel);
                        var geometries = instances.Select(i => geom.ShapeGeometryOfInstance(i) as IXbimShapeGeometryData);
                        foreach (var g in geometries)
                        {
                            using (var ms = new MemoryStream(g.ShapeData))
                            using (var br = new BinaryReader(ms))
                            {
                                var triangulation = br.ReadShapeTriangulation();
                            }
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by Dakki97** [comment]
Thank you, can you provide clarification in some parts.

This code implies that an element can have multiple geometries e.g. 2 meshes?
Does IFCOpeningElement not inherit from IFCProduct because iterating all products does not get me OpeningElements.

**Comment by martin1cerny** [comment]
It is `IfcProduct` so iterating over all products certainly **will** give you `IfcOpeningElements` if there are any in the model.

And yes, any element can have any number of geometries (like a window consisting of the frame, glazing panels and handles for example).

**Comment by Dakki97** [comment]
Oh yes I understand. Another question I have is about the instances.
There seem to be 2 instances 1 with openings and 1 without openings
But the instance without openings does not have a transformation. How can I get correctly transformed objects with openings?
