### ISSUE TITLE
Does Revit support entities built through IfcTriangulatedFaceSet?

### ISSUE THREAD

**Issue by WENTBY** [xBimTeam/XbimGeometry#144]
Hi
I built some entities through IfcTriangulatedFaceSet, these entities can be displayed in XBIM, but don't work in Revit.

**Comment by martin1cerny** [comment]
You will need to be a lot more specific about the issue. What data do you have? What are you trying to achieve? What have you tried? Is it an issue with xBIM or Revit? If it is a Revit issue you will need to raise it in [their importer repository](https://github.com/Autodesk/revit-ifc).

**Comment by WENTBY** [comment]
year, I made a simple wall through the IfcTriangulatedFaceSet, and I saved as a file in IFC format that can be displayed on XBIMWindowsUI and BIM Vision, but dosen't work in Revit, I have no idea about that.

**Comment by martin1cerny** [comment]
Than it is a Revit issue and you have to ask [there](https://github.com/Autodesk/revit-ifc). Or you can debug/study their importer to see what goes wrong. Nobody from our team is an expert for Revit importer and it is out of the scope of xBIM Toolkit.
