### ISSUE TITLE
Not rendering IfcTriangulatedFaceSet correctly ( but other IFC viewers can)

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimGeometry#145]
Referring to the below ifc file:

Note that in XBimExplorer, this is what I get:
![wrongrendering](https://user-images.githubusercontent.com/13161574/43114494-fec662dc-8f31-11e8-954b-00b6f56472a7.png)

But if I open it in other IFC viewers, then the `IfcTriangulatedFaceSet` is being rendered correctly

![bimvision](https://user-images.githubusercontent.com/13161574/43114507-103c02e2-8f32-11e8-9cb9-2983d7b52b6a.png)

![renderingifc](https://user-images.githubusercontent.com/13161574/43114515-139875c4-8f32-11e8-9daa-b52c5893846e.png)

 

[allterrain.zip](https://github.com/xBimTeam/XbimWindowsUI/files/2221826/allterrain.zip)

**Comment by andyward** [comment]
Looks like this is still an issue in v5.

**Comment by andyward** [comment]
Related to https://github.com/xBimTeam/XbimEssentials/pull/211

**Comment by martin1cerny** [comment]
This doesn't seem to be related. After the merge the problem is still present.

**Comment by bekraft** [comment]
Found a solution. See PR #151
