### ISSUE TITLE
Very slow cutting with IfcBooleanResult

### ISSUE THREAD

**Issue by honghu666** [xBimTeam/XbimGeometry#147]
#### Expected behavior:
![bimvision](https://user-images.githubusercontent.com/43664201/49496789-cac2fe80-f8a1-11e8-9c08-120a88d053cb.png)

#### Actual behavior or exception details:
![xbim](https://user-images.githubusercontent.com/43664201/49496669-846d9f80-f8a1-11e8-910e-8b5a106cf376.png)
#### Versions of xBIM Packages:

- xBIM Essentials:  version 4.x
- xBIM Geometry:  version 4.x

#### Minimal file to reproduce the issue:
[1.zip](https://github.com/xBimTeam/XbimGeometry/files/2647628/1.zip)

**Comment by martin1cerny** [comment]
Can you verify if the problem is still present with xBIM 5 (the latest)?

**Comment by andyward** [comment]
I took a look. It actually opens in v4 for me. (4.0.12.V0069) - but I don't think it's cutting the holes correctly in the columns.

It's broken in V5.0 so looks like we need to investigate. It seems to go into a long-running/endless process in the GeometryEngine. Nothing in the logs. Tested with the latest v5.0.141-prerelease geometry engine. Will take a deep dive this evening

**Comment by andyward** [comment]
I had a look at this last night (I've added some logging which is now in the latest v5 Desktop). It seems like the CreateSolidSet is running **extremely** slowly at this point:

https://github.com/xBimTeam/XbimGeometry/blob/develop/Xbim.Geometry.Engine.Interop/XbimGeometryEngine.cs#L575

By slow, I mean 2-3+ minutes per operation, and this model has hundreds of what looks like chained boolean operations. 

![image](https://user-images.githubusercontent.com/923699/49659447-2c1ed500-fa3c-11e8-9ddb-b58723c573b9.png)

I'm not sure yet whether this is a regression, or related to this specific model. I think it's going to need @SteveLockley  to take a look when he gets back in a few days time.

**Comment by honghu666** [comment]
@andyward Great work! When 5.x will be released.

**Comment by andyward** [comment]
Next few days hopefully...

**Comment by SteveLockley** [comment]
This model has Boolean Unions in, we don't really see much of these so I will have a dig

**Comment by SteveLockley** [comment]
I have update the Boolean Union code to be optimized for complex/compound Unions like this one and to utilise multiple threads This is in the develop branch now. The performance seems significantly faster, this model now takes 45 seconds to process on a 3.5Ghz PC with 4 cores and 8 processors. Unions like this are rarely found so we haven't had good test cases to work with. Thanks for putting this one up on github.

**Comment by andyward** [comment]
Just tested in Explorer in Release build and it's **much** faster. Opens in < 2 secs on my similar spec machine. Nice 👍
