### ISSUE TITLE
Invalid extrusion exception raised when using IfcCenterLineProfileDef as SweptArea

### ISSUE THREAD

**Issue by 1molPotato** [xBimTeam/XbimGeometry#149]
#### IfcExtrudedAreaSolid cannot be visualized in XbimXplorer, the warn is showed as below
![invalid_extrusion_warn](https://user-images.githubusercontent.com/11970884/49981561-697ee780-ff93-11e8-98bb-4861bf5006a8.jpg)

In the ifc file provided at the bottom, IfcCenterLineProfileDef is used as the ***SweptArea*** of IfcExtrudedAreaSolid. And IfcPolyLine is used as the ***Curve*** of IfcCenterLineProfileDef.

Actually, I found a unit test in ***Ifc4GeometryTest.cs*** that creates extruded solid using Semi-circle (IfcTrimmedCurve based on IfcCircle) as IfcCenterLineProfileDef's Curve. It worked well in the viewer, but it failed after I changed the Curve to an instance of IfcPolyline.

I also tried using an instance of IfcTrimmedCurve based on IfcLine but it didn't work, either.

I would appreciate if you can tell me whether I used the entity incorrectly or it is a bug of XbimGeometry.

#### Minimal file to reproduce the issue:
[ExtrudedBeamTest.zip](https://github.com/xBimTeam/XbimGeometry/files/2678529/ExtrudedBeamTest.zip)

**Comment by martin1cerny** [comment]
I had a look at the file and the definition seems to be correct.

**Comment by 1molPotato** [comment]
> I had a look at the file and the definition seems to be correct.

Thanks for your quick reply, then could you please give me any advice on how to solve this problem? Although, actually, I am not confident to fix it myself because I am not from software engineering background.

**Comment by 1molPotato** [comment]
Thanks!
By the way, the _**ProfileType**_ of IfcCenterLineProfileDef should be "AREA" instead of "CURVE". I made a mistake.

**Comment by SteveLockley** [comment]
OK this is fixed in the develop branch, the issue was that the single line effectively had no normal and the offseter could not decide which side to offset to, this is now calculated correctly

**Comment by 1molPotato** [comment]
It works fine now. Thanks a lot!

If you don't mind I have one more question..
Do you have any plan to support new geometric entities in [IFC4x1 Schema](http://www.buildingsmart-tech.org/ifc/IFC4x1/final/html/) like **_IfcSectionedSolidHorizontal_** or **_IfcLinearPlacement_**?  XbimEssentials can handle them well but XbimGeometry seems not.

Anyway, thanks again for all your work done. It has greatly helped me in my Master thesis.

**Comment by SteveLockley** [comment]
Glad it worked. We have these geometries on our future planned release. (after v5)
