### ISSUE TITLE
Problem with IfcFastener bolt holes

### ISSUE THREAD

**Issue by richardpotter-au** [xBimTeam/XbimGeometry#15]
Hi xBimTeam,

I am part of a team developing a system to fabricate steel beam assemblies using 6 axis robots.
Our system is driven by data imported from IFC files.
We have some existing IFC import code but it is poorly written and slow and doesn't support Tekla 21 IFC export.
Your code looks much better and we are in the process of incorporating it into our system.
Great job guys.

I currently have a problem with IfcMechanicalFasteners.
For our system, in some cases we need to generate part meshes with fastener holes included.
In other cases, we need to generate meshes without the holes, so we can calculate the intersections with the fasteners and instruct the robots to cut the holes.

We are hoping to move to IFC files exported by Tekla Structures 21.0, these have a feature where the fastener bolt holes can be included as a void in the triangle part mesh.

Hovever the mesh geometry generated by your geometry engine often seems to incorrectly generate the meshes with bolt holes. For some parts it works correctly but not for all. If I import the same IFC file in Solibri viewer the holes are all generated correctly.

Can you tell me if this is a known issue?

I am using Xbim.Geometry.Engine V3.1, the master branch on NuGet.

I have included a small IFC file which I think demonstrates the problem.

Any help is greatly appreciated.

Regards,

Richard.

[testv2_ifc.txt](https://github.com/xBimTeam/XbimGeometry/files/147552/testv2_ifc.txt)

**Comment by martin1cerny** [comment]
Hi @richardpotter-au ,

your project seems to be very interesting. I'm sorry we didn't reply earlier but we do heavy refactoring of the code and implementation of IFC4. All the new development is in develop branch. Using that code it seems identical to what I can see in Solibri. Can you try the latest develop version if it works for you?

**Comment by SteveLockley** [comment]
Please download our latest version on the develop branch V092, this will resolve many of these issues

**Comment by richardpotter-au** [comment]
Thanks for responding to my question.
When I get time I will try the latest development branch as suggested and see if I can reproduce the issue.
