### ISSUE TITLE
Show Dimensions on X-Bim web viewer 

### ISSUE THREAD

**Issue by satregiftc** [xBimTeam/XbimGeometry#152]
Hi..

Can i get help to show line , dimension and annotation on web viewer

Regards
Satish

**Comment by martin1cerny** [comment]
This is not supported in the viewer.

**Comment by satregiftc** [comment]
Hi..

Any development is going on in this area for future releases as this is more important 
while comparing to commercial BIM viewers

Regards
Satish 

Regards
Satish

**Comment by andyward** [comment]
Happy to take your pull request :)  
Closing as this should be in WebUI
