### ISSUE TITLE
Xbim.Geometry.Engine.dll not found when referencing console project to library project that references XbimGeometry

### ISSUE THREAD

**Issue by Truning** [xBimTeam/XbimGeometry#153]
This may be a duplicate of #93, but I did not understand the provided solution.

My problem is that I have a library project (IfcManagerLib) that uses several of the the Xbim packages (also XbimGeometry) and a console project (IfcManagerConsole) referencing IfcManagerLib. Now whenever IfcManagerConsole calls a procedure inside IfcManagerLib that uses:

`context = new Xbim3DModelContext(manager.model);
  context.CreateContext();
`

I get the following error:

> System.IO.FileLoadException
>   HResult=0x80131621
>   Message=Failed to load Xbim.Geometry.Engine32.dll
>   Source=Xbim.Geometry.Engine.Interop
>   StackTrace:
>    at Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor(ILogger`1 logger) in C:\buildagent_os\_work\1\s\Xbim.Geometry.Engine.Interop\XbimGeometryEngine.cs:line 65
>    at Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor() in C:\buildagent_os\_work\1\s\Xbim.Geometry.Engine.Interop\XbimGeometryEngine.cs:line 27
>    at Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine() in C:\buildagent_os\_work\1\s\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 486
>    at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs) in C:\buildagent_os\_work\1\s\Xbim.ModelGeometry.Scene\Xbim3DModelContext.cs:line 678
>    at IfcFileManagerLib.IfcGeometryExtractor..ctor(IfcManager manager) in C:\Users\david\source\repos\IFCFileManager\IfcFileManagerLib\IfcExtractor.cs:line 92
>    at IfcFileManagerLib.IfcManager.Start() in C:\Users\david\source\repos\IFCFileManager\IfcFileManagerLib\IfcManager.cs:line 79
>    at IfcFileManagerConsole.Program.DefaultTest() in C:\Users\david\source\repos\IFCFileManager\IfcFileManagerConsole\Program.cs:line 61
>    at IfcFileManagerConsole.Program.Main(String[] args) in C:\Users\david\source\repos\IFCFileManager\IfcFileManagerConsole\Program.cs:line 35
> 
> Inner Exception 1:
> FileNotFoundException: Die Datei oder Assembly "Xbim.Geometry.Engine.dll" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
> 

What I understand is that the dll is loaded after compiling the program and that I need to manually include the dll after deploying the code. But how do I do that? And why do I even _have_ to do that? Can't the IfcManagerConsole automatically get the right path to the dll?

A rather unsatisfiying solution is to install XbimGeometry on IfcManagerConsole. But I don't think that is a good idea for that only one method that fails to be executed.
Also: I have a third project (a windows service referencing IfcManagerLib). It has the same problem and when I install the packages on it, the errors still persist.

Thank you for any help!

**Comment by martin1cerny** [comment]
Make sure that `Xbim.Geometry.Engine32.dll` gets copied over to your executable location.

**Comment by Truning** [comment]
Thank you Martin and Andy for your answers!

@andyward The console project now works after copying the engines to the project's bin folder, however, I copied both Engines (32bit and 64bit) to the Service project too (it runs on 64bit), and it still gives the error: Failed to load Xbim.Geometry.Engine64.dll.
What am I doing wrong?

**Comment by andyward** [comment]
Can you provide the logs on the service project? - there's a lot of diagnostics in [XbimCustomAssemblyResolver.cs](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Interop/XbimCustomAssemblyResolver.cs) to help when things go wrong. You might need to set up a [File logger](https://github.com/serilog/serilog-extensions-logging-file). It'll likely come down to how you're running the windows Service. 

As a rule I'd only copy the engine version you need for the process, rather than copying both.

**Comment by Truning** [comment]
Oh! Nevermind. It was a problem with the installer of the service not copying over the dlls. The problem is fixed. Thank you a lot!

**Comment by astashkevich39** [comment]
Hi all! 
I have same problem on Windows Server 2016, but my IIS trying search DLL on C:\Windows\System32\inetsrv\Xbim.Geometry.Engine64.dll path.
I work with Microsoft SharePoint 2016 and if I use TimerJob it try load assembly from C:\Windows\System32\Xbim.Geometry.Engine64.dll. 
Thinking now about how i must package this.

![image](https://user-images.githubusercontent.com/29597786/60017449-0a5c0700-9689-11e9-9d7f-bb5c97c28f62.png)

**Comment by andyward** [comment]
Looks like you've deployed Xbim.Geometry.Engine.Interop into the GAC. I don't think we support that. If you must do this, you could try copying the native 32/64 bit DLL into either the same folder as the Interop dll, or by putting it somewhere on the $PATH.

**Comment by astashkevich39** [comment]
Thanks for reply, @andyward. Yes, SharePoint work with GAC. Now, if I put Xbim.Geometry.Interop into GAC, and Xbim.Geometry.Engine64.dll into c:\windows\system32 it works great. I found more options for SharePoint after your answer, so thanks again!

**Comment by rubit0** [comment]
The issue resurfaced for me after updating `Xbim.Geometry` from `5.1.541` to `6.1.801-netcore`.
After some debugging I managed to fix the issue by directly referencing the `Xbim.Tessellator` package.

You might also need to reference `Xbim.Geometry.Engine.Interop` and `Xbim.ModelGeometry.Scene`.

**Comment by andyward** [comment]
Hi @rubit0 

It may be worth opening a new issue as this one already has a couple of distinct different problems in v5 GE and netcore/v6 does things differently.

Can you clarify what the exact issue you saw is with `6.1.801-netcore`? There should be no need to reference the child dependencies of `Xbim.Geometry` directly. Xbim.Geometry just brings in both `Xbim.Geometry.Engine.Interop` and `Xbim.ModelGeometry.Scene` and those in turn bring in `Xbim.Tessellator`
