### ISSUE TITLE
Is it possible to get world coordinates for IfcSpace elements?

### ISSUE THREAD

**Issue by GravTrainee** [xBimTeam/XbimGeometry#156]
Hi!

Thanks again for helping me with my last issue, but a new one rose quickly after. 
I am trying to get coordinates for spaces in the building, but the following code returns to me a list of [0.0.0].

static void Coordinates(IfcStore model)
        {
            
            var context = new Xbim3DModelContext(model);
            context.CreateContext();
            var instances = context.ShapeInstances();
            int n = 0;
            var allSpaces = model.Instances.OfType<IIfcSpace>().ToList();

            foreach (var Space in allSpaces)
            {
                var instance = instances.FirstOrDefault(x => x.IfcProductLabel == Space.EntityLabel);
                var global_pos = instance.Transformation.Translation;
                Console.WriteLine(global_pos + ", " + n);

            }

        }

But when I use it to find out the coordinates of other ifcelements, like doors or walls, it works as it is supposed to. Where is the problem?

EDIT: I want to know the coordinates of the space, meaning I want to know the corners/vertices of the space.

**Comment by GravTrainee** [comment]
![image](https://user-images.githubusercontent.com/46449153/51605117-c668a880-1f16-11e9-8edd-1d6882880bdf.png)

We would want to read the information of IFCSpace, in order to be able to draw them out in 3D/2D. As you can see, we have already managed to do this much even without Xbim, but we are missing the tools to read the coordinates and attributes of the room.

**Comment by martin1cerny** [comment]
As you say, you need to read coordinates, not just transformation.
