### ISSUE TITLE
Unable to load GeometryEngine32 on .NET Framework 4.7.2

### ISSUE THREAD

**Issue by Dakki97** [xBimTeam/XbimGeometry#157]
Trying to run context.CreateContext() on 4.7.2 causes : "Failed to load Xbim.Geometry.Engine32.dll"
This works on .NET 4.5.2. with following versions:
Xbim.Geometry 4.0.15-V0042
Xbim.WindowsUI 4.0.12-V0017
Xbim.Essentials 4.0.30-V036

on 4.7.2 I use 
Xbim.Essentials 5.0.213
Xbim.Geometry 5.0.163
Xbim.WindowsUI 5.0.118

Minimal Code is any Code that uses this piece of code:
```
var context = new Xbim3DModelContext(model);
context.CreateContext();
```
Minimal File is any IFC File
[House.zip](https://github.com/xBimTeam/XbimGeometry/files/2800330/House.zip)

Is there anything I can do make it run on 4.7.2
My goal is to make my console application into a web api and Iam unable to retrieve the same libraries from nuget that I use in my 4.5.2 version.

**Comment by andyward** [comment]
What version of Windows is this on? Have you taken a look at #154

**Comment by andyward** [comment]
Did you get this resolved @Dakki97 ?

**Comment by Dakki97** [comment]
No, I managed to use a combination of older versions that work now
