### ISSUE TITLE
Could not load file or assembly 'Xbim.Geometry.Engine64.DLL' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by nguyennam0705** [xBimTeam/XbimGeometry#159]
Not working when publish project asp.net to iis

**Comment by martin1cerny** [comment]
You will need to be a lot more specific.

**Comment by nguyennam0705** [comment]
"Xbim.Geometry.Engine64.DLL" copy to bin and x64.
XBim Geometry v5.0.163

![bin1](https://user-images.githubusercontent.com/25917101/52624497-71023480-2ee1-11e9-923e-9185b8067a30.png)
![bin](https://user-images.githubusercontent.com/25917101/52624505-752e5200-2ee1-11e9-85c0-bcc784661143.png)

**Comment by nguyennam0705** [comment]
run debug in visual studio 2017 working but publish to iis not working

**Comment by martin1cerny** [comment]
Yes, you need to make sure it gets copied to the IIS. NuGet package manager makes sure it get's copied to the right place locally but you have to set up your deployment correctly.

**Comment by nguyennam0705** [comment]
Thank for reply.
Website not working when i copy dll file to bin in locally web.if i delete
it. Website run but xbim geometry not load

Vào 16:25, T.3, 12 Th2, 2019 Martin Černý <notifications@github.com đã viết:

**Comment by nguyennam0705** [comment]
I think Xbim.geometry.engine64.dll cannot register in iis

Vào 16:33, T.3, 12 Th2, 2019 Văn Nam Nguyễn <nguyennam0705@gmail.com đã
viết:

**Comment by martin1cerny** [comment]
You need to copy x64 folder to IIS

**Comment by nguyennam0705** [comment]
I created x64 folder in bin and copied it to x64 but not working

**Comment by andyward** [comment]
Don't put it in the x64 folder - put it along side the other Xbim dlls. Also make sure your website it running in 64 bit.

**Comment by nguyennam0705** [comment]
i'm sure website is running in 64 bit. i deleted x64 folder but it not working

**Comment by martin1cerny** [comment]
What version of Windows is running on the server? If it is < Win10 you might have to deploy [vcredist](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) alongside the `Xbim.Geometry.Engine64.dll`.

**Comment by andyward** [comment]
Also, enable logging - it'll tell you what it's doing. E.g. one approach:

https://github.com/xBimTeam/XbimExchange/blob/60f4d0489042fe46f7cccef515d633b861223bb2/Xbim.Exchange/Program.cs#L252

**Comment by nguyennam0705** [comment]
> What version of Windows is running on the server? If it is < Win10 you might have to deploy [vcredist](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) alongside the `Xbim.Geometry.Engine64.dll`.

thank! after install vcredist it work. CLOSE!
