### ISSUE TITLE
Missing dlls

### ISSUE THREAD

**Issue by nourrt** [xBimTeam/XbimGeometry#16]
I'm getting the below errors when running Bim.Geometry.Nuget solution:

Could not copy Xbim.Geometry.Engine32.dll because it was not found	
Could not copy Xbim.Geometry.Engine64.dll because it was not found

Any help would be appreciated.

**Comment by SteveLockley** [comment]
Can you give us a bit more context are you just compiling the xbim.geometry.solution?

**Comment by nourrt** [comment]
The above compile errors are generated when I run the Bim.Geometry.Nuget solution using VS2012.
When I tried to run the solution using VS2013,I got the following error message in a dialog window:
Unable to start program '...\XbimGeometry-master\Xbim.Geometry.Engine\..\Output\Debug\x86\Xbim.Geometry.Engine32.dll'. The system cannot find the file specified.

**Comment by gijskoning** [comment]
i've got the same problem

**Comment by martin1cerny** [comment]
We don't use win sdk at all so it is most probably reporting other issue.

**Comment by SteveLockley** [comment]
Please make sure you are installing the Nuget package correctly. When it is properly installed it will add the required dlls to your project and set the copy to output directory. Look at our windows Xplorer to see one that is correctly installed
