### ISSUE TITLE
CreateContext hangs and does not return

### ISSUE THREAD

**Issue by BjDi** [xBimTeam/XbimGeometry#160]
Hi,

I got a customer IFC file, that can't be loaded. The Xbim3DModelContext.CreateContext never ends
and I have to kill the process.

I use Xbim.ModelGeometriy.Scene v5.0.163

#### Steps (or code) to reproduce the issue:

Just try to open the IFC file with your WindowsUI

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*
[Test_181112.zip](https://github.com/xBimTeam/XbimGeometry/files/2865695/Test_181112.zip)

#### Expected behavior:

It should retrun, also if it can't be rendered.

#### Actual behavior or exception details:

Never ends

**Comment by SteveLockley** [comment]
This model has an odd feature, it has almost infinite solid extrusions
#83776= IFCEXTRUDEDAREASOLID(#83777,#83787,#83790,**3.300000000000000E36**);
Whilst technically it is OK, really these should ideally  be half space solids.
I will look at how we might trap this and avoid the problem of hanging

**Comment by SteveLockley** [comment]
I have put a fix for this in the develop branch could you confirm it is OK please. It seems that OCC has an undocumented limit on extrusions of 1e36,  might be worth raising with AllPlan at some time as I don't think what they are doing is best practice

**Comment by BjDi** [comment]
I have tested it and now it can be rendered.
Great
