### ISSUE TITLE
Package 5.0.163 installation error

### ISSUE THREAD

**Issue by ras254** [xBimTeam/XbimGeometry#165]
I try to install 5.0.163 version but got error
Could not install package 'Microsoft.Extensions.Logging 2.1.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7', but the package does not contain any assembly references or content files that are compatible with that framework.

Visual Studio 2015 Update 2
Windows 10

.NetFramework 4.7. not supported?

**Comment by andyward** [comment]
net47 is definitely supported. Do you get the same issue when installing Xbim.Essentials from nuget? 

Can you try adding Microsoft.Extensions.Logging @ 2.1.1 directly? If that fails it sounds like you need to ensure you've got a later version of Nuget installed.  See https://www.nuget.org/downloads

**Comment by ras254** [comment]
>Do you get the same issue when installing Xbim.Essentials from nuget?
No. Installation ok.

>Can you try adding Microsoft.Extensions.Logging @ 2.1.1 directly?
After NuGet was updated I got the next error
"Failed to add reference. The package 'System.Numerics.Vectors' tried to add a framework reference to 'System.Numerics' which was not found in the GAC. This is possibly a bug in the package."

Installation of the "System.Numerics.Vectors" get the same error.

**Comment by andyward** [comment]
What version of nuget do you have installed? Did you install 3.6.0 from https://dist.nuget.org/visualstudio-2015-vsix/latest/NuGet.Tools.vsix

Without trying to duck the issue, this feels like a question you may find the answer to over at https://github.com/NuGet/Home/issues

**Comment by ras254** [comment]
> What version of nuget do you have installed?
Yes, 3.6.0 version

Package was successfully installed using vs2017.
Thanks
