### ISSUE TITLE
Wall with hole in 3.2 but not in 5.0

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#166]
I save words for that bug. In Xbim 4.0 the same issue.

![image](https://user-images.githubusercontent.com/42930849/53870274-311f0080-3ffa-11e9-951c-277b2817d4cb.png)

![image](https://user-images.githubusercontent.com/42930849/53870282-3714e180-3ffa-11e9-864d-25d41d3efd60.png)

[Wall without hole.zip](https://github.com/xBimTeam/XbimGeometry/files/2935412/Wall.without.hole.zip)

**Comment by SteveLockley** [comment]
Gunter I cannot look at this today due to work, but I will look this week

Steve Lockley
Mob: 079 67 600 923

________________________________

**Comment by bekraft** [comment]
Here's what I've found: The file is correct (although the majority of the data amount is the site model). The opening geometry at entity 47 is read correctly. As far I can see, the final cut comprised of the wall parts and the overall opening seems to be a post step. The cut figure of the insulation layer exists but it's somehow hidden. Maybe it's a problem with some tolerance of the cut algorithm which yields a complete internal cut result? At which position in the code does the algorithm assemble the final mesh?
![166-cut-figure](https://user-images.githubusercontent.com/10463824/53975594-75e38e00-4105-11e9-8ae2-ed728c0e0512.png)

**Comment by SteveLockley** [comment]
Bernold thanks for looking into this, I have come across a few issues where the Boolean ops have inverted the result, it happened in the latest releases of OCC when they re-engineered Booleans for performance. Generally I have found it to be a tolerance issue, quite often BIM vendors incorrectly specify their tolerances.
I am really stuck at the moment with some work deadlines but will get to this as soon as I can. Thanks again for your help

Steve Lockley
Mob: 079 67 600 923

________________________________

**Comment by bekraft** [comment]
I only try to keep my head busy :-) But there's also a strong interest to have properly working geometry representation for CSG models on my side. Most engineering models are created that way. So I try to help out where possible.

**Comment by guenter1holzeder** [comment]
I found a code line where this bug could be fixed or rather removed: [Xbim3DModelContext.cs#L785](https://github.com/xBimTeam/XbimGeometry/blob/14228be89f822e85069a2b8f180b3c26b9260e1f/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L785)
If you use only the precision of the model factors for the following union and cut operations everything will be fine. Maybe this is a hint for further investigations.

**Comment by SteveLockley** [comment]
Hi all, thanks for digging on this, I suspect it is one of those things where you do a work around and it bites you later. Previous versions of OCC had some issues with precision and tolerance on booleans, but they have been getting fixed. I think this work around needs to go now. I will update asap. Thanks Guenter and Bekraft for continuing to help us make things better

**Comment by SteveLockley** [comment]
I ahve removed the offending line and push the build through the build pipeline to Nuget, it works fine now so I will close this issue
