### ISSUE TITLE
Still not rendering IfcTriangulatedFaceSet

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#167]
A sample wall with IfcTriangulatedFaceSet is not rendered as a shape. 
But it can be converted to a XbimSolid via XbimGeometryEngine and XbimShellset correctly.

I played with several constellations develope/master but with no positive result.

![image](https://user-images.githubusercontent.com/42930849/53876423-08513800-4007-11e9-86f2-e1706133f726.png)

![image](https://user-images.githubusercontent.com/42930849/53876431-0c7d5580-4007-11e9-9122-f145ddbb0eec.png)

[IfcTriangulatedFaceSet.zip](https://github.com/xBimTeam/XbimGeometry/files/2935812/IfcTriangulatedFaceSet.zip)

**Comment by andyward** [comment]
Is it related to #145? There was a recent PR #151 that got merged. Have you got the very latest?

**Comment by andyward** [comment]
Thanks. 169 includes that PR, so looks like this is a bug.

**Comment by bekraft** [comment]
The main reason here is, that the implementation ignores the "PnIndex" Attribute. It map between the local index and the provided index of the  *IfcCartesianPointList3D* given by "Coordinates". There's an argument-out-of range exception on the log 

```
==== 13:53	5	Error
Xbim.ModelGeometry.Scene.Xbim3DModelContext
GeomScene: #48="IfcTriangulatedFaceSet" ["Failed to create shape geometry, Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Sammlung sein.
Parametername: index"]
```

But somehow the given IFC model does not correspond to the latest IFC4 spec. It roughly says, that the given 2D list of normals should have the same length as the provided coordinate indices. It seems that the model exporter has written less normals than coordinates (6 vs. 8). "PnIndex" refers also to one of 6 indexes. So my guess is, that the exporter's "PnIndex" refers to the normals and maps it onto the vertices - which is indeed not the meaning of the IFC4 spec (see [IfcTriangulatedFaceSet](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifctriangulatedfaceset.htm)). Am I wrong? On the other hand, the way it has been exported makes more sense to me ...

**Comment by SteveLockley** [comment]
Guenter, I am not sure where the issue starts here, it looks like you have used xbim extract to strip some objects out. Do you have the original file so we can start from base zero?

**Comment by SteveLockley** [comment]
This is really odd, as Bekraft points out the PnIndex should be a L[1:?] of integers but your file has a L[1:?] L[3:3] of integers

I would have thought this just plain wrong except one of the samples on the IFC schema site does a similar thing [http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/](url) . We build our code from the express schema and that says it should be a list of integers.
To compound things we are not even processing PnIndex it in the geometry engine, other than when parsing. This is becasue it did not exist until Addendum 2 (they snook it in)
I think the best thing is that we assume the sample file above is wrong and the schema is correct. If you can fix your IFC file to comply with the schema, i.e. List of Integers that point to the the coordinate index to be used. Then we need to implement it :-)

**Comment by guenter1holzeder** [comment]
From a practical view I must say - other IFC viewers seem to have no problem with this. When you are in a B2B situation, no modification on IFC files can be done (by the end user). So it's sink or swim for them.

I think the question is, how tolerant an application should be on schema variances?

**Comment by SteveLockley** [comment]
I understand and am not trying to fascist with this in anyway. We are in fact ignoring this data, which is most likely what other tools are doing as this was not in add1. 
Wasn't sure if you were the author of the file, but I guess it is graphisoft. I will have a chat with the guys who deal with parsing and see if we swallow some of these complaints and take a softer approach

**Comment by guenter1holzeder** [comment]
In our business we're getting only final models from different producers (CADs). If we get a dickey IFC file we have to deal with it :-)

**Comment by bekraft** [comment]
I've tried also to find some other examples. But even the IFC spec doesn't provide some for this special case. Also the figures of spec page itself are somehow inconsistent. So figure 347 refers to Add1 whilst figure 348 refers to Add2. Don't know how to handle this ... Taking to graphisoft or others might be the best (since their exporters should be certified against whatever ;-)

**Comment by SteveLockley** [comment]
Had a good look and I think the PnIndex is fundamentally written out wrong by Graphisoft, their line says

**Comment by guenter1holzeder** [comment]
Well done
