### ISSUE TITLE
Xbim.Geometry.Engine32/64 assembly issue (Azure Web App)

### ISSUE THREAD

**Issue by Bissy29** [xBimTeam/XbimGeometry#168]
Hi Team,

I am trying to create a small web-app (.NET Framework 4.7) deployed on Azure to generate a wexbim based on ifc.

I added the Xbim.Geometry v5.0.163 NuGet but the app crashes on runtime (IIS Express, IIS) complaining that it cannot load the assembly Xbim.Geometry.Engine32 (or 64, depending on config).

<img width="1889" alt="exception" src="https://user-images.githubusercontent.com/5812307/53936580-e9a87b00-40b2-11e9-9149-ed32ef06c821.png">

Stack Trace:

<img width="1889" alt="stack trace" src="https://user-images.githubusercontent.com/5812307/53936592-f6c56a00-40b2-11e9-9811-06622e6d1c18.png">

Can you please give me a hint?

Thanks!
Alex

**Comment by martin1cerny** [comment]
This looks like if you were loading x64 Geometry engine dll into x32 process. Can you make sure that your IIS architecture matches the version of geometry engine?

**Comment by Bissy29** [comment]
I tried also the other way around, to run the IIS on x64. In this case the situation looks like this:

<img width="1478" alt="screen shot 2019-03-07 at 9 15 02 am" src="https://user-images.githubusercontent.com/5812307/53938656-8a019e00-40b9-11e9-9833-2e6985e367e1.png">

And the configuration looks like this:

<img width="1097" alt="screen shot 2019-03-07 at 9 13 37 am" src="https://user-images.githubusercontent.com/5812307/53938671-98e85080-40b9-11e9-929c-7efbf8cfaf17.png">

Maybe I am missing something...

**Comment by martin1cerny** [comment]
Can you also confirm that `Xbim.Geometry.Engine32.dll` and `Xbim.Geometry.Engine64.dll` are copied to your application? Some deployment mechanisms drop these because they are loaded in runtime and there is no direct dependency in the project.

**Comment by Bissy29** [comment]
I confirm that the files were referenced automatically in the project after I added the NuGet:
<img width="275" alt="screen shot 2019-03-07 at 10 36 32 am" src="https://user-images.githubusercontent.com/5812307/53943111-11a0da00-40c5-11e9-845e-de177b118fdf.png">

And the files can be found in bin folder:
<img width="586" alt="screen shot 2019-03-07 at 10 36 54 am" src="https://user-images.githubusercontent.com/5812307/53943148-22e9e680-40c5-11e9-89bb-31ae98c7e509.png">

**Comment by andyward** [comment]
**Don't** put both 32 and 64 bit in the bin folder. Just put the one you need. IIS loads all assemblies in the bin folder at the start, so you'll get 'Bad Image Format' when it loads a 64 bit dll into a 32 bit process (and vice versa)

**Comment by martin1cerny** [comment]
Also, you need to check your deployed directory, not the build.

**Comment by Bissy29** [comment]
Thank you team, I managed to solve the issue.

The solution was to clean the bin and then to remove the reference to Xbim.Geometry.Engine32 from the Xbim.Geometry.Interop.targets file located in MyProject\packages\Xbim.Geometry.Engine.Interop.5.0.163\build\net47. Otherwise, every time both dlls (32 & 64) were copied to bin. So I left only the 64 dll:

![screen shot 2019-03-08 at 12 00 40 pm](https://user-images.githubusercontent.com/5812307/54021949-ff44a000-4199-11e9-9d0c-bb445d7ab04b.png)

Thanks again and have a nice weekend!
