### ISSUE TITLE
IFCSHAPEREPRESENTATION($, ... issue

### ISSUE THREAD

**Issue by alexmatv70** [xBimTeam/XbimGeometry#169]
Some IFC files rendered fine with other IFC viewers are rendered bad using xBIM.

#### Assemblies and versions affected:

XbimGeometry 5.0.0.0, XbimXplorer 5.0.0.0

#### Steps (or code) to reproduce the issue:

Open attached 171210eccentricity_physical(edited).ifc file using XbimXplorer

#### Minimal file to reproduce the issue:
[171210eccentricity_physical(edited).ifc.zip](https://github.com/xBimTeam/XbimGeometry/files/2953517/171210eccentricity_physical.edited.ifc.zip)

#### Expected behavior:

Scene contains rendered model

#### Actual behavior or exception details:

Scene is empty

#### Additional Details

The problem is found on IFC file saved by CATIA 3DEXPERIENCE Platform.
I've found that the problem is in IFCSHAPEREPRESENTATION($, ... that has no reference to IFCGEOMETRICREPRESENTATIONCONTEXT. 
I would agree that it doesn't comply to the specification and consider such file as invalid, but other popular software such as Datacomp BIM Vision, Autodesk Viewer have no such problem. 
Therefore it would be good for XbimGeometry to handle such case too.

**Comment by martin1cerny** [comment]
As you say, this is a bug in CATIA 3DEXPERIENCE Platform. You should really raise an issue with them. We use the context as a root for geometry processing. That is why it is not being processed. As a temporal workaround you can check if all `IFCSHAPEREPRESENTATIONs` have a context assigned and assign it (or create the context) if needed.

**Comment by urosjovanovic** [comment]
I reported the same issue a while ago (#38).
Although I agree that this clearly violates the IFC specs, as @alexmatv70 mentioned other software seem to load this files regardless. From my experience chances that authoring tools (as CATIA mentioned above) would react are fairly slim for that exact reason.

Anyway, in the meantime, feel free to use or modify this workaround which I have used for some time to get around this. It basically pre-processes the IModel in order to create some default 3D context (ONLY if there are no 3D ctx) and allow the Xbim Geometry Engine to do it's magic. I don't really know if this is a 100% right way to do it, but feel free to ajdust.

```
private static void FillMissingRepresenationContext(IModel model)
{
    bool ifc4schema = model.Header.SchemaVersion?.ToLower().Contains("ifc4") ?? false;

    IIfcRepresentationContext defaultCtx = null;
    ITransaction transaction = null;

    try
    {
        foreach (IIfcProduct product in model.Instances.Where<IIfcProduct>(prod => !ReferenceEquals(prod.Representation, null)))
            foreach (IIfcRepresentation representation in product.Representation.Representations.Where(rep => ReferenceEquals(rep.ContextOfItems, null)))
            {
                if (defaultCtx == null)
                {
                    transaction = model.BeginTransaction("Create Default 3D Context");

                    if (ifc4schema)
                    {
                        defaultCtx = model.Instances.New<Xbim.Ifc4.RepresentationResource.IfcGeometricRepresentationContext>(ctx =>
                        {
                            ctx.CoordinateSpaceDimension = 3;
                            ctx.WorldCoordinateSystem = model.Instances.New<Xbim.Ifc4.GeometryResource.IfcAxis2Placement3D>(axis =>
                            {
                                axis.Location = model.Instances.New<Xbim.Ifc4.GeometryResource.IfcCartesianPoint>(pt => pt.SetXYZ(0, 0, 0));
                            });
                        });
                    }
                    else
                    {
                        // Suppose it's 2x3

                        defaultCtx = model.Instances.New<Xbim.Ifc2x3.RepresentationResource.IfcGeometricRepresentationContext>(ctx =>
                        {
                            ctx.CoordinateSpaceDimension = 3;
                            ctx.WorldCoordinateSystem = model.Instances.New<Xbim.Ifc2x3.GeometryResource.IfcAxis2Placement3D>(axis =>
                            {
                                axis.Location = model.Instances.New<Xbim.Ifc2x3.GeometryResource.IfcCartesianPoint>(pt => pt.SetXYZ(0, 0, 0));
                            });
                        });
                    }

                    defaultCtx.ContextIdentifier = "Auto generated default 3D context";
                    defaultCtx.ContextType = "Model";
                }

                representation.ContextOfItems = defaultCtx;
            }

        transaction?.Commit();
    }
    finally
    {
        (transaction as IDisposable)?.Dispose();
    }
}
```

**Comment by alexmatv70** [comment]
Thank you for comments. I've already made a workaround for that problem and problem of missing context. I am not sure if it is correct therefore would appreciate if someone review.

```
        private static void ValidateModel(IfcStore model)
        {
            if (model.SchemaVersion == IfcSchemaVersion.Ifc2X3 || model.SchemaVersion == IfcSchemaVersion.Ifc4)
            {
                IEntityCollection instances = model.Instances;
                var contexts = instances.OfType<IIfcGeometricRepresentationContext>();
                FixMissingContext(model, instances, contexts);
                FixShapeRepresentationsWithoutContext(model, contexts);
            }
        }

        private static void FixMissingContext(IfcStore model, IEntityCollection instances, IEnumerable<IIfcGeometricRepresentationContext> contexts)
        {
            if (contexts.Count() == 0)
            {
                LoggerNet.WriteLog(String.Format("Model {0} is invalid. Add missing IfcGeometricRepresentationContext as a workaround.", model.FileName),
                    LogLevel.Warning, IFCConstants.LOG_CATEGORY);
                using (var tx = model.BeginTransaction("Add missing IfcGeometricRepresentationContext"))
                {
                    IIfcGeometricRepresentationContext grc = null;
                    switch (model.IfcSchemaVersion)
                    {
                        case IfcSchemaVersion.Ifc2X3:
                            grc = instances.New<Xbim.Ifc2x3.RepresentationResource.IfcGeometricRepresentationContext>();
                            break;
                        case IfcSchemaVersion.Ifc4:
                            grc = instances.New<Xbim.Ifc4.RepresentationResource.IfcGeometricRepresentationContext>();
                            break;

                    }
                    if (null != grc)
                    {
                        instances.OfType<IIfcShapeRepresentation>().ForAll(sr => { sr.ContextOfItems = grc; });
                    }
                    tx.Commit();
                }
            }
        }

        private static void FixShapeRepresentationsWithoutContext(IfcStore model, IEnumerable<IIfcGeometricRepresentationContext> contexts)
        {
            if (contexts.Count() == 1)
            {
                var ctx = contexts.FirstOrDefault();
                var badShapeReps = model.Instances.OfType<IIfcShapeRepresentation>().Where(s => null == s.ContextOfItems);
                if (badShapeReps.Any())
                {
                    LoggerNet.WriteLog(
                        String.Format("Model {0} is invalid. There are {1} IfcShapeRepresentation items without context. Fixing them as a workaround.",
                            model.FileName, badShapeReps.Count()),
                        LogLevel.Warning,
                        IFCConstants.LOG_CATEGORY
                    );
                    using (var txn = model.BeginTransaction("Fix shape representations without context"))
                    {
                        foreach (var s in badShapeReps) s.ContextOfItems = ctx;
                        txn.Commit();
                    }
                }
            }
        }

```

**Comment by andyward** [comment]
@martin1cerny should we consider something like this in the IModel `SetWorkArounds`? We're already handling other exporter quirks there...

**Comment by bekraft** [comment]
Hey. 
I've also experienced a lot of different interpretations of the IFC spec. Some are only given verbally. There's enough space for doing Things different. Allowing a handler in a post step to do semantic validation and correction might solve some issues. But it raises also a discussion about the responsibility of the data. So, if such a "workaround" handling is introduced, the modification has to be identifiable. Means, there's a need of revision and version support to separate original and modified data. At least there should be some hurdles to avoid overwriting the original file by accident.

**Comment by martin1cerny** [comment]
No, I don't think so. This would require to change the model processing
strategy in XbimModelContext3D.

Dne út, 12. 3. 2019 12:09 uživatel Andy Ward <notifications@github.com>
napsal:

**Comment by andyward** [comment]
Looks like we can close
