### ISSUE TITLE
Wexbim file fails to display

### ISSUE THREAD

**Issue by nourrt** [xBimTeam/XbimGeometry#17]
Hello,

I'm facing an issue where some IFC files (mostly the ones that are small in size) are converted successfully to wexbim and displayed in the viewer, however other IFC files are failing to display (although their wexbim files are generated, they seem to be corrupt).

I'm using Xbim.Geometry.3.1.14 package. Below is the code I'm using to convert the files to wexbim:
```
 using (var wexBimFile = new FileStream(wexBimFileName, FileMode.Create))
            {
                using (var binaryWriter = new BinaryWriter(wexBimFile))
                {
                    using (var model = new XbimModel())
                    {
                        model.CreateFrom(ifcFileFullName,xbimFile, null, true, false);
                        Xbim3DModelContext geomContext = new Xbim3DModelContext(model);
                        geomContext.CreateContext(XbimGeometryType.PolyhedronBinary);
                        geomContext.Write(binaryWriter);
                    }
                }
            }
```
Any help/suggestion as to why the wexbim files are generated corruptly ,would be highly appreciated.

**Comment by nourrt** [comment]
I got this error using page inspector:
uncaught exception: Style index not found.

**Comment by zhengcongyin** [comment]
I met the same error. Have you find out the solution? Thanks,

**Comment by SteveLockley** [comment]
Once you have created the 3D Model context as above you can export the WexBIM file like this

  using (var wexBiMfile = new FileStream(wexBimFilename, FileMode.Create, FileAccess.Write))
                        {
                            using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                            {
                                model.SaveAsWexBim(wexBimBinaryWriter);
                                wexBimBinaryWriter.Close();
                            }
                            wexBiMfile.Close();
                        }

**Comment by metorm** [comment]
@nourrt 

I am new to xBIM. I am working on a viewer system which is aimed at rendering a structure as fast as possible.

I want to know, is it possible to render/display an *.wexBIM file in a wpf window? I want to use *.wexBIM instead of *.ifc because it appears that parsing *.wexBIM file is much faster than *.ifc files.

It seems you have successfully displayed *.wexBIM using XbimGeometry. I am not sure whether you have used WebUI or windowsUI or anything else. Will you kindly give me some advice?
