### ISSUE TITLE
Problems installing xbim essentials and geometry into unity project

### ISSUE THREAD

**Issue by Wolgraph** [xBimTeam/XbimGeometry#170]
Hi,
I'm trying to import import geometry and properties into Unity3D v.2018.3.8f1.
I'm using Visual Studio 2017 community v. 15.9

Since Unity tends to rebuild the solution at every start up, cleaning out every external reference, I managed to install nuget packages for xbim.essentials and geometry into Vs and It returns me no error, but the Unity internal compiler says I miss references to Xbim packages.
I even tried copy-paste all .dll file into assets's sub folders, but Unity can't even install them.

I found no documentation or posts about this issue.

I tried to make and compile a custom library (mathematical operations )to test the importation process: I compiled the library and pasted the dll file into the Unity asset folder and it worked just fine.

I'm sorry if I'm not clear, but I'm quite a newbe to this.

**Comment by martin1cerny** [comment]
I'm sorry but we don't have any experience with Unity. There have been people trying to use xBIM with Unity with various levels of success. See this: #109

**Comment by Wolgraph** [comment]
https://github.com/xBimTeam/XbimGeometry/issues/93#issuecomment-365952047
This solved the problem.
I opened the github folder XbimWindowsUI, searched for alle dll files and copy-pasted them all into a "Plugins" folder I created. 
I had to solve some importing problems with a few useless dlls and everything just went fine. I managed to compile this code. At least I can convert the ifc file into a more readable ifcxml format.
`using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;

public class Testprogetto : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
       const string fileName = @"D:/Documenti/Unity Projects/Testprogetto/Assets/Muro finestrato.ifc";
        using (var Stepmodel = IfcStore.Open(fileName, null, -1))
        {
            Stepmodel.SaveAs(@"D:/Documenti/Unity Projects/Testprogetto/Assets/Muro finestrato.ifcxml");
        }
        using (var model = IfcStore.Open("Muro finestrato.ifcxml"))
        {
            
        }
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}`
