### ISSUE TITLE
How to use EsentModel?

### ISSUE THREAD

**Issue by tulip411** [xBimTeam/XbimGeometry#171]
Hi! I want to obtain the geometry data of certain buildinelement from existing IFC file. I found EsentModel seems to be helpful. But I couldn't figure out how to creat an EsentModel. Are there any examples of this kind? 

Thank you!
Maggie

**Comment by andyward** [comment]
I don't think the model format has much bearing on this. The different `IModel` implementations are just to provide access to the IFC data. `MemoryModel` is an in-memory version of the IFC file (so memory hungry and transient), while Esent is backed by the EsentDb data store and better suited to 'random access' queries.

But both host exactly the same data.

When you use the `IfcStore`, by default it uses the different IModel representations based on model size, although you can over-ride the behaviour.   E.g. https://github.com/xBimTeam/XbimEssentials/blob/9f1962a1187e61cc7222b562865f5526def8cecf/Xbim.Ifc/IfcStore.cs#L38

If you need more info I'd suggest opening another ticket (Esent queries live over in XbimTeam/XbimEssentials)
