### ISSUE TITLE
What i have to do to obtain the geometry of Walls, columns, etc?

### ISSUE THREAD

**Issue by BetsyCarrera** [xBimTeam/XbimGeometry#172]
Hi, I'm not sure it is the correct place to ask it, if it's not please redirect me:

I'm new in Xbim, and I need to obtain all the geometric data of an object in order to represent it.

**Comment by martin1cerny** [comment]
Do you need the original IFC definition of the geometry or processed triangulated mesh?

**Comment by tulip411** [comment]
> Do you need the original IFC definition of the geometry or processed triangulated mesh?

Could you explain a bit between these two concepts?

**Comment by tulip411** [comment]
> Do you need the original IFC definition of the geometry or processed triangulated mesh?

Could you explain a bit between these two concepts?
Since I also need to get the geometric data, I'm also a bit confused.
Actually what I need is just the shape and sizes of the building elements and also the location. I'm not sure if this refers to the mesh.

Thank you in advance.

**Comment by BetsyCarrera** [comment]
> Do you need the original IFC definition of the geometry or processed triangulated mesh?
Hi!,
He explained my situation, I need to remove by each wall its dimensions and considering that may have windows or doors i need the measures and location of these openings. The aim of this is to be able to divide each wall in pieces of certain dimensions and that finally the original wall by joining these parts.i am not sure which is the best option, if they could help me.

**Comment by BetsyCarrera** [comment]
> Do you need the original IFC definition of the geometry or processed triangulated mesh?
Hi!, 
He explained my situation, I need to remove by each wall its dimensions and considering that may have windows or doors i need the measures and location of these openings. The aim of this is to be able to divide each wall in pieces of certain dimensions and that finally the original wall by joining these parts.i am not sure which is the best option, if they could help me.

**Comment by martin1cerny** [comment]
Original IFC definition describes the complete definition of the geometry like this:

```
#33=IFCEXTRUDEDAREASOLID(#30,#36,#34,2400.);
#30=IFCRECTANGLEPROFILEDEF(.AREA.,$,#32,300.,4000.);
#31=IFCCARTESIANPOINT((0.,400.));
#32=IFCAXIS2PLACEMENT2D(#31,$);
#34=IFCDIRECTION((0.,0.,1.));
#35=IFCCARTESIANPOINT((0.,0.,0.));
#36=IFCAXIS2PLACEMENT3D(#35,$,$);
```

Where extruded area is defined as a profile extruded alongside a directrix in a particular direction and length.

When you want to visualize this on the screen as a 3D object you need to process it into triangles. That's what we do in with our geometry engine. You can than use this processed geometry for geometrical analyses and operations.

What @BetsyCarrera describes would involve analysing of both semantic relations and processed geometry and than altering the geometry definitions in original IFC file. That is all possible with xBIM but is definitely not trivial.

**Comment by andyward** [comment]
Duplicates #127
