### ISSUE TITLE
Create Walls and Windows in a global coordinate system

### ISSUE THREAD

**Issue by ChrisMun89** [xBimTeam/XbimGeometry#174]
Hi everyone!

I hope you can help me. I start to using this great tool but seem to have some problems with creating simple walls and windows. I want to build a simple house by coding. Therefore I've got the coordinates of the start point of the wall, the length and the angle.

I use that code to add a new wall:

if (model != null)
{                                            
      wall = CreateWall(model, l * 1000, thickness * 1000, 3000, x * 1000, y * 1000, alpha);

      if (wall != null) AddPropertiesToWall(model, wall);
      using (var txn = model.BeginTransaction("Add Wall"))
       {
                       building.AddElement(wall);
                       txn.Commit();
         }

        if (wall != null)
        {
                        try
                        {
                           model.SaveAs(BIM_Output, IfcStorageType.Ifc);
                         }
                         catch (Exception e)
                         {
                             Console.WriteLine("Failed to save HelloWall.ifc");
                             Console.WriteLine(e.Message);
                           }
             }
  }

The walls are placed in seemingly arbitrary locations (see picture). I think this are local positions but how can I create an 3d model of an hole building?

Thanks in advance!

Chris

![XBim](https://user-images.githubusercontent.com/50044575/56847812-ef675380-68e0-11e9-905f-240ca22a6725.PNG)

**Comment by andyward** [comment]
What's in the implementation of `CreateWall`? Are you using the sample code at http://docs.xbim.net/examples/proper-wall-in-3d.html ?

You'll need to set some local placement. 

I think there used to be a sample that created a sample house in XBIM somewhere but I can't find it. Will get back if I come across it.
