### ISSUE TITLE
Circular Openings regressed in v5

### ISSUE THREAD

**Issue by andyward** [xBimTeam/XbimGeometry#178]
Some openings have changed between v4 and v5 Geometry. 

#### Assemblies and versions affected:

Geometry v5.0.118

#### Steps (or code) to reproduce the issue:

Demonstrable in v5. XbimXplorer

What was a circular opening in a slab has become a different shape

#### Minimal file to reproduce the issue:

IFC supplied by BT: `p2013-60_b_all-p2013-60_s_ct.ifc`

**Comment by SteveLockley** [comment]
This is resolved in build 5.209 in the develop  branch

**Comment by andyward** [comment]
Confirmed Fixed
