### ISSUE TITLE
[Question] How to calculate the quantities?

### ISSUE THREAD

**Issue by fabiogmartins** [xBimTeam/XbimGeometry#179]
Hi,

How can I calculate the quantities?

I am using this IFC file ([OneWallTwoWindows.ifc](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/tests/data/OneWallTwoWindows.ifc)).

Xbim Xplorer does not show quantities:
![xBimExplorer](https://user-images.githubusercontent.com/13428045/57407450-97223280-71b9-11e9-83f0-fd9e916eec57.PNG)

In the Solibri Model Viewer the quantities are displayed:
![SMV](https://user-images.githubusercontent.com/13428045/57407605-faac6000-71b9-11e9-9b39-c52844796b1e.PNG)

I looked the topics, but I could not implement consistent
https://github.com/xBimTeam/XbimGeometry/issues/60
https://github.com/xBimTeam/XbimGeometry/issues/127

Could anyone help me with this?

Thanks,
Fabio.

**Comment by martin1cerny** [comment]
There is a standard way to export quantities in IFC. That is using `IfcElementQuantity` in a similar way property sets and properties are used. We would show these in Xplorer if they were present in the data. What Solibri shows as quantities is derived from geometry. You can do that using our geometry engine but be aware that these measures are usually only to be treated as indicative unless you can rely on the way the model was authored.

**Comment by fabiogmartins** [comment]
Thanks for the answer @martin1cerny,

I think in my case, when there is no quantity information in the IFC file, I must calculate via geometry.

I tried this code to get the information:


> static void Main(string[] args)
        {
            using (var model = IfcStore.Open("C:\\OneWallTwoWindows.ifc"))
            {
                var project = model.Instances.OfType<IIfcProject>().FirstOrDefault();
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var item = model.Instances.FirstOrDefault<IIfcWall>();

                Console.WriteLine("Name:{0}", item.Name);
                Console.WriteLine("-----------");

                var productshape = context.ShapeInstancesOf((Xbim.Ifc4.Interfaces.IIfcProduct)item);
                var _productShape = productshape.Where(s => s.RepresentationType != XbimGeometryRepresentationType.OpeningsAndAdditionsExcluded).ToList();
                var geometry = new XbimShapeGeometry();

                XbimShapeTriangulation mesh;

                var vol = 0.0;
                var area = 0.0;

                foreach (var shapeInstance in _productShape)
                {
                    geometry = context.ShapeGeometry(shapeInstance);
                    var ms = new MemoryStream(((IXbimShapeGeometryData)geometry).ShapeData);
                    var br = new BinaryReader(ms);
                    mesh = br.ReadShapeTriangulation();
                    mesh = mesh.Transform(((XbimShapeInstance)shapeInstance).Transformation);

                    List<int> trs = new List<int>();
                    foreach (var f in mesh.Faces)
                    {
                        trs = trs.Concat(f.Indices).ToList();
                        area += GetAreaOfMesh(mesh, f);
                    }
                    vol += VolumeOfMesh(mesh.Vertices, trs);
                }
                Console.WriteLine("-----------");
                Console.WriteLine("Area Total:{0}", area);
                Console.WriteLine("Volume Total:{0}", vol);

            }
            Console.ReadKey();
        }

        private static double GetAreaOfMesh(XbimShapeTriangulation mesh, XbimFaceTriangulation f)
        {
            var area = 0.0;
            for (int i = 0; i < f.Indices.Count(); i += 3)
            {
                var p1 = mesh.Vertices[f.Indices[i]];
                var p2 = mesh.Vertices[f.Indices[i + 1]];
                var p3 = mesh.Vertices[f.Indices[i + 2]];
                var t = new XbimPoint3D[] { p1, p2, p3 };

                double[] point1 = new double[3] { p1.X, p1.Y, p1.Z };
                double[] point2 = new double[3] { p2.X, p2.Y, p2.Z };
                double[] point3 = new double[3] { p3.X, p3.Y, p3.Z };
                var distp1p2 = Math.Sqrt(point1.Zip(point2, (a, b) => (a - b) * (a - b)).Sum());
                var distp2p3 = Math.Sqrt(point2.Zip(point3, (a, b) => (a - b) * (a - b)).Sum());
                var distp3p1 = Math.Sqrt(point3.Zip(point1, (a, b) => (a - b) * (a - b)).Sum());
                double s = (distp1p2 + distp2p3 + distp3p1) / 2;
                area += Math.Sqrt(s * (s - distp1p2) * (s - distp2p3) * (s - distp3p1));
            }
            Console.WriteLine("Area Face:{0}", area);
            return area;
        }

        private static double SignedVolumeOfTriangle(XbimPoint3D p1, XbimPoint3D p2, XbimPoint3D p3)
        {
            var v321 = p3.X * p2.Y * p1.Z;
            var v231 = p2.X * p3.Y * p1.Z;
            var v312 = p3.X * p1.Y * p2.Z;
            var v132 = p1.X * p3.Y * p2.Z;
            var v213 = p2.X * p1.Y * p3.Z;
            var v123 = p1.X * p2.Y * p3.Z;
            return (1.0 / 6.0) * (-v321 + v231 + v312 - v132 - v213 + v123);
        }

        public static double VolumeOfMesh(IList<XbimPoint3D> vertices, List<int> trs)
        {
            double volume = 0.0;

            for (int i = 0; i < trs.Count; i += 3)
            {
                XbimPoint3D p1 = vertices[trs[i + 0]];
                XbimPoint3D p2 = vertices[trs[i + 1]];
                XbimPoint3D p3 = vertices[trs[i + 2]];

                var vol = SignedVolumeOfTriangle(p1, p2, p3);
                Console.WriteLine("Volume Trg:{0}", vol);

                volume += vol;
            }
            return Math.Abs(volume);
        }


But the data obtained were not exactly as expected.

> Name:Basic Wall:Wall-Ext_102Bwk-75Ins-100LBlk-12P:285323
>
> Area Face:16343800,0971985
> Area Face:870000,091552733
> Area Face:1740000,18310547
> Area Face:1740000,18310547
> Area Face:870000,091552733
> Area Face:263899,992370602
> Area Face:263900,027770996
> Area Face:263899,992370602
> Area Face:263900,027770996
> Area Face:263900,032196046
> Area Face:263900,027770996
> Area Face:263900,032196046
> Area Face:263900,027770996
> Area Face:16343800,0971985
> Volume Trg:-83724468,4611751
> Volume Trg:-140638294,475565
> Volume Trg:-137547342,94863
> Volume Trg:-83724455,8262237
> Volume Trg:-552029453,125
> Volume Trg:-98305694,4661458
> Volume Trg:-324084707,03125
> Volume Trg:-508611425,178766
> Volume Trg:-154278798,970892
> Volume Trg:-112886923,767877
> Volume Trg:-140638294,475565
> Volume Trg:-185457091,61613
> Volume Trg:-112886906,731987
> Volume Trg:-744309375
> Volume Trg:347548044,386029
> Volume Trg:347548044,386029
> Volume Trg:0
> Volume Trg:0
> Volume Trg:870000091,552734
> Volume Trg:870000091,552734
> Volume Trg:522452047,166705
> Volume Trg:522452047,166705
> Volume Trg:-92804830,6503282
> Volume Trg:-92804830,6503283
> Volume Trg:-112514532,803785
> Volume Trg:-112514532,803785
> Volume Trg:52779998,4741203
> Volume Trg:52779998,4741203
> Volume Trg:72489700,6275774
> Volume Trg:72489700,6275775
> Volume Trg:-92804844,6556093
> Volume Trg:-92804844,6556093
> Volume Trg:-6734608,36124018
> Volume Trg:-6734608,36124018
> Volume Trg:52780006,4392091
> Volume Trg:52780006,4392091
> Volume Trg:-33290229,8551601
> Volume Trg:-33290229,85516
> Volume Trg:-44579297,0187618
> Volume Trg:-74883202,2092279
> Volume Trg:-73237417,5452888
> Volume Trg:-44579290,2912511
> Volume Trg:-293929425,964355
> Volume Trg:-52343106,2960307
> Volume Trg:-172559691,085815
> Volume Trg:-270811391,304254
> Volume Trg:-82146122,0289569
> Volume Trg:-60106917,3286676
> Volume Trg:-74883202,2092279
> Volume Trg:-98747079,8363444
> Volume Trg:-60106908,2578667
> Volume Trg:-396309338,378906
> 
> Area Total:40018800,9039307
> Volume Total:2018543937,18966


How could I abstract the correct information?

**Comment by martin1cerny** [comment]
You need to consider units. This model is in millimetres. When you divide areas by 1e-6 and volumes by 1e-9 the results will look a lot better.

**Comment by fabiogmartins** [comment]
How can I identify in the IFC file the unit is in millimetres?

Another question, how could I identify the correct face to calculate the area (in this case of the wall)?

The first calculated face returned exactly the value displayed in Solibri: 16.34sqm

**Comment by martin1cerny** [comment]
> How can I identify in the IFC file the unit is in millimetres?

Check IfcUnitAssignment.

> Another question, how could I identify the correct face to calculate the area (in this case of the wall)?

You can try to use direction of normals.

**Comment by bekraft** [comment]
The "area" of a wall is a quantity term of design. There's no unique meaning. What do you mean: Lateral area, area along the axis, area of bottom / top? Therefore, no serious software computing "area" of directionally aligned components. Even with normals you might get into trouble. If these data are a basis of some serious computations, you should strongly consider another way (exporting like @martin1cerny already said)

**Comment by fabiogmartins** [comment]
Thanks guys for the help.

@bekraft I agree with your points.

@martin1cerny I implemented considering normals and got the expected value for this case.

I did more testing, with other IFC files, where they were exported with quantities and without quantities. In all cases the values are calculated correctly or very close to the correct by Solibri.

I really need to implement similar operation to Solibri.

For this, I must manually implement the specific rules for each object type (ifcWall, ifcWindow, ifcDoor, and etc). Do you agree?
Any idea to simplify this?

**Comment by martin1cerny** [comment]
I don't think you can simplify this. You will need to formally implement people's perception of these objects or some formal rules of measurement.

**Comment by andyward** [comment]
Closing. Please raise again if there's specific questions.

**Comment by kimirmahajan** [comment]
hi 
@fabiogmartins 
wanted your help in calculating the areas using normals.
also how did you found out the measurement unit of ifc file

thanks
Kimir
