### ISSUE TITLE
Create FacetedBrep from XBimSolid object

### ISSUE THREAD

**Issue by Thomis01** [xBimTeam/XbimGeometry#182]
Hello guys,

I've got a IfcExtrudedAreaSolid. With this I created a IXbimSolid with the engine, so that I can execute a Transform.

Now the question is how to get a IfcFacetedBrep or simular, because I need to add it to a IfcShapeRepresentation.
I've seen that there has been a CreateFacetedBrep() in the engine, but was removed. So how can I handle it.

Or is there an other way to transform (rotate, translate) an IfcExtrudedAreaSolid. Or should I work with other  @types?

Thanks for help,
Thomis.

**Comment by SteveLockley** [comment]
I am sorry but I don't understand your issue. You seem to be switching between the XbimGeometry objects and the IFC geometry objects. Can you be clearer about your intentions please

**Comment by Thomis01** [comment]
Yes its kind of switching between XbimGeometry and IFC geometry objects.
I need to rotate, translate or mirror IFC geometry objects.
So i parsed it to XBimSolid to use the Transform method.

Now i needed to create from this xbimsolid a ifcfactedbrep. How can I handle this?

**Comment by martin1cerny** [comment]
If you only need to transform the object than you would be better to use IFC data structures to actually define/redefine the transformation itself. You can use [IfcMappedItem](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcmappeditem.htm) to apply rotation, translation and scale to any geometry.

**Comment by Thomis01** [comment]
Ok thanks. I'll try it.
