### ISSUE TITLE
Unable to load the file or assembly 'Xbim.Geometry.Engine64'

### ISSUE THREAD

**Issue by jacopo2405** [xBimTeam/XbimGeometry#189]
I created a simple console project in VS2017 in vb.net, FW 4.71, all xbim dll's loaded with nuget and updated with last versions.

Code is very easy
`        
```
Try
            If Not File.Exists(ConfigurationManager.AppSettings("pathXbim").ToString & "\" & nomeFile.Replace(".ifc", ".wexBIM")) Then
                Using model = IfcStore.Open(ConfigurationManager.AppSettings("pathModelli").ToString & "\" & nomeFile)
                    Dim context = New Xbim3DModelContext(model)
                    context.CreateContext()
                    Dim wexBimFilename = ConfigurationManager.AppSettings("pathXbim").ToString & "\" & nomeFile.Replace(".ifc", ".wexBIM")
                    Using wexBiMfile = File.Create(wexBimFilename)
                        Using wexBimBinaryWriter = New BinaryWriter(wexBiMfile)
                            model.SaveAsWexBim(wexBimBinaryWriter)
                            wexBimBinaryWriter.Close()
                        End Using
                        wexBiMfile.Close()
                        ret = True
                    End Using
                End Using
            Else
                ret = True
            End If

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
```
`

it works fine on my develop pc (win10) but not on a server with Windows 2008r2: fw 4.71 installed, all c++ redistributable from 2008 to 2019 (included 2013, 2015 …).
I've Always "Unable to load the file or assembly 'Xbim.Geometry.Engine64'" error when try to create the IfcStore.
Xbim.Geometry.Engine64 is in exe project: I tried also to put it on x64 subdir.
I also tried to use 32bit instead but I had the same error "Unable to load the file or assembly 'Xbim.Geometry.Engine32'".

I'm sure that it's something on what VS installed and I don't have on server but don't know what other than vc++.

thanks in advance

**Comment by jacopo2405** [comment]
don't know if it could help
I also tried to install xbimxplorer http://docs.xbim.n et/downloads/xbimxplorer.html
it works on my pc but on server it doesn't display the file: no errors shown but the display won't initizialize, only properties and tree, on the left, are shown; graphic on the right remains gray

**Comment by andyward** [comment]
You likely need to install the vc runtime on older servers. See:

Take a look at https://github.com/xBimTeam/XbimGeometry/issues/159#issuecomment-463092144

**Comment by jacopo2405** [comment]
I'm trying also on a Windows Server 2016, same project, it gives me another error
Could not load file or assembly 'System.IO.Compression, Version=4.2.0.0"
even on this server vcredist are installed in all versions

**Comment by andyward** [comment]
On Server 2008 I suspect it's this issue. https://github.com/xBimTeam/XbimGeometry/issues/154

On Server 2016, that's a different error. Make sure that 'System.IO.Compression.dll' is present in the bin folder.

**Comment by jacopo2405** [comment]
> On Server 2008 I suspect it's this issue. #154
> On Server 2016, that's a different error. Make sure that 'System.IO.Compression.dll' is present in the bin folder.

on 2016 now works: don't know why setup didn't include 'System.IO.Compression.dll' but I added all the dll's in the bin folder to the setup dir and it works
I saw the issue. #154 but as 2008r2 is a test server I prefer to don't risk my develop pc installing old toolset so I accept that on old OS's it doesn't work (maybe it can be a good excuse to update the test server).
thanks a lot Andy
