### ISSUE TITLE
CreateContext function throws System.AccessViolationException for larger models(> 400 MB)

### ISSUE THREAD

**Issue by ashish1691** [xBimTeam/XbimGeometry#190]
*Short summary describing the issue. (3-5 sentences)*

#### Assemblies and versions affected:

*Which assemblies/packages and their versions are known to be affected. E.g. __Xbim.Essentials 4.0.29__*

#### Steps (or code) to reproduce the issue:

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

```csharp
using (var model = IfcStore.Open("file.ifc"))
{
    ...
}
```

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

#### Expected behavior:

*What would you expect to happen*

#### Actual behavior or exception details:

*What actually is happening*

#### Additional Details

*Optional, details of the root cause if known. 
Delete this section if you have no additional details to add.*

**Comment by andyward** [comment]
I suspect we need the model to reproduce this. Can you share it?

**Comment by ashish1691** [comment]
No, I can not provide the model as it is confidential data and I am not authorised to share.

**Comment by martin1cerny** [comment]
We are sorry but this is very generic type of exception and we will not be able to fix it if we cant reproduce it. You can try to dig into xBIM Geometry to find the problem yourself of course.

**Comment by CBenghi** [comment]
@ashish1691, if you manage to isolate the elements that produce the error I can show you how to reduce the file so that you don't have confidentiality issues.

**Comment by andyward** [comment]
If you turn up logging to Verbose you should see what geometry element is failing (if running single threaded)

**Comment by annpag** [comment]
Hi, i have the same problem, even though my file is smaller (24 MB). Are there any updates about the problem? thanks

**Comment by andyward** [comment]
Generally this is not down to file size. 

This error is what you see when there's an failure in the unmanaged C++ code in the GeometryEngine - typically down in the OpenCascade library. Unfortunately the `AccessViolationException` is usually just masking the real error (in the Cpp marshalling) - the actual fault is typically down to some fundamentally invalid _boolean_ operation, and the best way to track it down is if you can supply the model (or part of it) exhibiting the issue.

We can do this privately if the model is sensitive.

**Comment by SteveLockley** [comment]
can you tell us what version of the xbim geometry engine dll you are using please?

**Comment by SteveLockley** [comment]
Can you please supply a snippet of the model that causes the error or turn the information logging on in windows xplorer and let us have the verbose log output

**Comment by ashish1691** [comment]
Finally able to caught an exception

{"Method 'CreateSolidSet' in type 'Xbim.Geometry.Engine.Interop.XbimGeometryEngine' from assembly 'Xbim.Geometry.Engine.Interop, Version=5.1.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation.":"Xbim.Geometry.Engine.Interop.XbimGeometryEngine"}

**Comment by ashish1691** [comment]
How can I turn on the information logging? and where can i find the log file?

**Comment by martin1cerny** [comment]
You have to hook in your own logger. We are using Microsoft Logging Abstractions. You can use any logging framework. We often use Serilog like this:

```xml
<PackageReference Include="Serilog.Extensions.Logging" Version="2.0.2" />
<PackageReference Include="Serilog.Sinks.ColoredConsole" Version="3.0.1" />
```

```cs
Log.Logger = new LoggerConfiguration()
   .Enrich.FromLogContext()
   .WriteTo.ColoredConsole()
   .CreateLogger();

// set up xBIM logging before you use xBIM. It will use your providers.
XbimLogging.LoggerFactory.AddSerilog();

IfcStore.ModelProviderFactory.UseHeuristicModelProvider();
using (var model = IfcStore.Open(fileName))
{
    // do what you want
}
```

**Comment by ashish1691** [comment]
@martin1cerny  can you please share your details on which I can share the IFC file.

**Comment by andyward** [comment]
You can send it (or a link to a download service/dropbox etc) to my email address - details in my profile. I'll get it to Martin/Steve

**Comment by CBenghi** [comment]
Hi Andy,
I'm also working on geometry lately, feel free to copy me in.
Claudio

Il Ven 1 Nov 2019, 19:44 Andy Ward <notifications@github.com> ha scritto:

**Comment by haschulz** [comment]
I'm getting the same issue on ~70% of the IFC models I have. Should I send you the models? 

Regards,
Harald

**Comment by andyward** [comment]
There's been a number of stability fixes on the 5.1 develop codebase the last 6-8 weeks. Can you retest with the 5.1.297-develop Geometry engine? (This has been integrated in the latest XbimXplorer develop branch if that's easier)

**Comment by andyward** [comment]
Still don't have a repro for this

**Comment by haschulz** [comment]
with the latest xbim version this exception was gone - thanks

**Comment by andyward** [comment]
Thanks for getting back
