### ISSUE TITLE
Error: Failed to initialize geometric context

### ISSUE THREAD

**Issue by secomDevs** [xBimTeam/XbimGeometry#193]
I'm trying to parse an ifc4 file. The code writes the model context in a new Xbim3DModelContext variable and throws the error: Failed to initialize geometric context while trying context.CreateContext(). The error from contextHelper.InitialiseError i guess is about duplicated keys from GeometryShapes. The XbimXplorer doesn't throw any error. Sorry i'm new, can you please support me.

**Comment by martin1cerny** [comment]
Can you post a full error message and package versions here please?

**Comment by secomDevs** [comment]
Thanks for your quick reply.
Error Message was:
Exception: "System. Exception"; in Xbim. ModelGeometry. Scene. dll
An exception error of type "System. Exception"; occurred in Xbim. ModelGeometry. Scene. dll.
Failed to initialise geometric context, An element with the same key has already been added. 

The package versions we use are:
Xbim.Geometry 4.0.11
Xbim.Essentials 4.0.29

The parser works fine with some other IFC4-Files.
Thanks in advance!

**Comment by martin1cerny** [comment]
Geometry processing happens **after** parser reads the file. It is a data transformation operation.

Can you try if this is still the case with the [latest release](https://www.nuget.org/packages/Xbim.Geometry/) please? A lot of development went into geometry engine recently.

If the problem persists in the latest version, can you share the file or it's offending part?

**Comment by secomDevs** [comment]
Thanks Martin works great now! :)
