### ISSUE TITLE
Issue with Xbim.Geometry.Engine64 dll in hosted environment.

### ISSUE THREAD

**Issue by anilkandoor** [xBimTeam/XbimGeometry#195]
Issue with Xbim.Geometry.Engine64  dll in hosted environment.

we have developed the XBim application to view the ifc files.
we used the "Xbim.Geometry.Engine64" dll, its is responsible for converting IFC file – XBIM – WEXBIM. The application is running fine and able to view ifc files in local machine.
(i.e this works in IIS server from Visual studio2015).
When we host the application in IIS, the application is not running, Xbim.Geometry.Engine64 dll is not recognizing.
please help us to resolve the issue.

**Comment by GeorgDangl** [comment]
Can you verify that the `Xbim.Geometry.Engine64.dll` file is present in the deployed application folder on IIS?

**Comment by martin1cerny** [comment]
Also - is your deployment application 64bit? Web servers often run as 32bit so xBIM would be looking for `Xbim.Geometry.Engine32.dll`.

**Comment by anilkandoor** [comment]
> Can you verify that the `Xbim.Geometry.Engine64.dll` file is present in the deployed application folder on IIS?

We verified it present in bin folder.

**Comment by anilkandoor** [comment]
> Also - is your deployment application 64bit? Web servers often run as 32bit so xBIM would be looking for `Xbim.Geometry.Engine32.dll`.

I have added the  `Xbim.Geometry.Engine32.dll`. manually in bin folder of deployed application folder.
still facing the same issue.

**Comment by GeorgDangl** [comment]
When you say _"When we host the application in IIS, the application is not running"_, what's happening exactly? Is the application refusing to start up? Are you getting an exception when a conversion is happening? Are there any logs or exceptions you can share?

**Comment by anilkandoor** [comment]
> When you say _"When we host the application in IIS, the application is not running"_, what's happening exactly? Is the application refusing to start up? Are you getting an exception when a conversion is happening? Are there any logs or exceptions you can share?

 The application refusing to start up and showing message like "HTTP Error 503. The service is unavailable" when browse from the URL.

**Comment by martin1cerny** [comment]
I'm sorry, but you will need to inspect the application/server logs to provide more details. It would also be helpful if you could provide more details about the system (OS version, IIS version, .NET version, xBIM version etc.)

**Comment by anilkandoor** [comment]
> I'm sorry, but you will need to inspect the application/server logs to provide more details. It would also be helpful if you could provide more details about the system (OS version, IIS version, .NET version, xBIM version etc.)

when the Xbim.Geometry.Engine64 dll present the bin folder , the application refusing to start up, when i browse the site and abserve the site stopped immediatly in application pool.
hence there is no server logs.
below is the version details.
.Net Versuion  4.0
Server OS: windows server 2008 R2 Enterprice.
IIS : internet information Service 7
Xbim Version: 5.0.0.0

**Comment by andyward** [comment]
Sounds like #154  Can you try a more modern server OS?

**Comment by niranjankala** [comment]
We are also facing some issue when integrating Xbim in ASP.NET WebAPI project. 

Could not load file or assembly 'xxxxx' or one of its dependencies. An attempt was made to load a program with an incorrect format.
An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--

**Comment by martin1cerny** [comment]
You will need to provide us with more information about your deployment environment and exception details.

**Comment by niranjankala** [comment]
below is the version details.
.Net Version 4.7
Server OS: windows server 2016 Standard
IIS : internet information Service 10.0.14393.0
Xbim Version: 5.1.259
Publish Profile settings: **Debug x64**

Error message:
Could not load file or assembly 'Xbim.Geometry.Engine.dll' or one of its dependencies. The system cannot find the file specified.

StackTrace:
   at Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor(ILogger`1 logger)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine()
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs)
   at XModelCreator.CreateOBJFile(String projectId)
   at BiMService.Controllers.XbimController.Get3D(String projectId) in D:\TFS\RS\BIMserverAPI\BiMService\Controllers\XbimController.cs:line 131
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)


Packages:
<package id="Xbim.Cobie" version="5.1.179" targetFramework="net47" />
<package id="Xbim.CobieExpress" version="5.1.146" targetFramework="net47" />
<package id="Xbim.COBieLite" version="5.1.179" targetFramework="net47" />
<package id="Xbim.COBieLiteUK" version="5.1.179" targetFramework="net47" />
<package id="Xbim.CobieLiteUK.Validation" version="5.1.179" targetFramework="net47" />
<package id="Xbim.Common" version="5.1.259" targetFramework="net47" />
<package id="Xbim.DPoW" version="5.1.179" targetFramework="net47" />
<package id="Xbim.Essentials" version="5.1.259" targetFramework="net47" />
<package id="Xbim.Exchanger" version="5.1.179" targetFramework="net47" />
<package id="Xbim.Geometry" version="5.1.239" targetFramework="net47" />
<package id="Xbim.Geometry.Engine.Interop" version="5.1.239" targetFramework="net47" />
<package id="Xbim.Ifc" version="5.1.259" targetFramework="net47" />
<package id="Xbim.Ifc2x3" version="5.1.259" targetFramework="net47" />
<package id="Xbim.Ifc4" version="5.1.259" targetFramework="net47" />
<package id="Xbim.IO.CobieExpress" version="5.1.146" targetFramework="net47" />
<package id="Xbim.IO.Esent" version="5.1.259" targetFramework="net47" />
<package id="Xbim.IO.MemoryModel" version="5.1.259" targetFramework="net47" />
<package id="Xbim.IO.Table" version="5.1.146" targetFramework="net47" />
<package id="Xbim.ModelGeometry.Scene" version="5.1.239" targetFramework="net47" />
<package id="Xbim.PropertySets" version="4.0.1" targetFramework="net47" />
<package id="Xbim.Tessellator" version="5.1.259" targetFramework="net47" />

**Comment by martin1cerny** [comment]
Can you confirm that your system is 64bit and that Xbim.Geometry.Engine64.dll is present in the deployed environment? Because this library is loaded at runtime it is sometimes missed out by deployment routines.

**Comment by andyward** [comment]
Also you should ensure you're capturing the logging. There's `Microsoft.Extensions.Logging.ILogger` support in the geometry interop which will highlight [what it's doing](https://github.com/xBimTeam/XbimGeometry/blob/3aacca65b29cc9c9e05d07665594ac718b855c17/Xbim.Geometry.Engine.Interop/XbimCustomAssemblyResolver.cs#L41) when looking for the native geometry engine. 

To make use of this logging you need to add a provider. There's an example of how to do this at:

https://github.com/xBimTeam/XbimExchange/blob/58b3dcc6174bf1dc15e7985ecb7b173efb85bf90/Xbim.Exchange/Program.cs#L33

...which you can use/repurpose for ASP.Net / asp.net core. Note it outputs to a console.

If you want a really simple setup to output to a file you can use something like https://github.com/serilog/serilog-extensions-logging-file

**Comment by niranjankala** [comment]
Hi @andyward,

I am calling below lines of code in an ApiController from the Business logic project. 

public void CreateContext(modelPath)
{
IfcStore model = IfcStore.Open(modelPath);
this.context = new Xbim3DModelContext(model);
}

It is a working Console and Winforms application which is using .NET framework 4.7. But in Web API 2 it always gives an error for loading Xbim.Geometry.Engine64.dll due to some missing dependency.

To make it work, I have deleted Xbim.Geometry.Engine64.dll from the output directory using some post-build script. After that application working in x86 and AnyCPU configuration.

> It would be better we should have a boilerplate project sample for ASP.NET, WebApi in Xbim repository to that how can we use these assemblies in the hosted environment.

**Comment by andyward** [comment]
Great. 

We probably need something in a wiki on best practices for running under ASP.NET

ASP.NET can be a bit tricky with native DLLs..  Frankly, I'd be very careful running that kind of code under a customer facing ASP.NET site.
