### ISSUE TITLE
IfcPolygonalFaceSet is not working properly

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#196]
See attached file with three Openings. None of them do any solid cuttings (no holes).

![image](https://user-images.githubusercontent.com/42930849/60271739-2ebb1c00-98f3-11e9-8d1a-f29d9156dcb7.png)
![image](https://user-images.githubusercontent.com/42930849/60272057-bd2f9d80-98f3-11e9-8ac2-9d5de67e21ba.png)

![image](https://user-images.githubusercontent.com/42930849/60271964-8e192c00-98f3-11e9-8824-b9884d5c3dc9.png)

[IFC4 IfcPolygonalFaceSet.zip](https://github.com/xBimTeam/XbimGeometry/files/3335024/IFC4.IfcPolygonalFaceSet.zip)

**Comment by SteveLockley** [comment]
Hi Guenter I had a look at this, There was an issue with converting the shell of a Polygonal Face to a solid which I have sorted in the develop branch release 5.1.252. In addition the generic Create method for geometries did not respect the Closed flag of PolygonalFaceSet. I have also add the interfaces into Essentials re #197. Can you please confirm this fixed
![image](https://user-images.githubusercontent.com/8222629/62057260-384be280-b217-11e9-9da8-ae121f963177.png)

**Comment by guenter1holzeder** [comment]
Great, I will apply this to our next sprint
