### ISSUE TITLE
IfcPolygonalFaceSet is not supported in IXbimGeometryEngine

### ISSUE THREAD

**Issue by guenter1holzeder** [xBimTeam/XbimGeometry#197]
Neither the creation of solids nor shells can be done by the Engine-Interface Xbim.Ifc4.Interfaces.IXbimGeometryEngine

(Maybe this issue is better targeted to XbimEssentials!?)

**Comment by SteveLockley** [comment]
Hi Guenter, we are just sorting this, but cant release just yet as BuildingSmart has changed all its xml namespaces and it is breaking essentials. Should be done early next week

**Comment by SteveLockley** [comment]
This is now released in the develop branch
