### ISSUE TITLE
Having troubles finding reference coordinates and vertices of building elements

### ISSUE THREAD

**Issue by tulip411** [xBimTeam/XbimGeometry#198]
Hi there,

I have some questions in reading the geometry data from an IFC file.

I simplified my code and attached below. I tried to read the reference coordinates and vertices of the slabs, and stored them in Positions and Points seperately. In the end I printed out the cartesian points.

I tried several files. the Poistions always has only one cartesian point and Points always has one point list(without openings in the slab) or two lists(with openings).

When there is openings in slab, the Positions will always be 0,0,0  even if it definitely has reference coordinates. And the Points also seems to be unreadable. And this also happened in other building elements(walls etc.).

I wonder if I'm using the right way reading the file, or if I have any mistakes.  I also included a simple ifc file I have tried.

Thank you so much!

ps. the CartesianPoint is a class I defined only to memerize the coordinates. 

Sincerely
Maggie

```csharp

var _model = IfcStore.Open(fileNameOrPath, null, -1);
var _context = new Xbim3DModelContext(_model);
_context.CreateContext();
using (_geom = _model.GeometryStore.BeginRead())
{
    Slabs = new List<Slab>();
    var allSlabs = _model.Instances.OfType<IIfcSlab>();
    foreach (var slab in allSlabs)
    {
        Slabs.Add(new Slab(slab, _context, _geom));
    }
}


public Slab(IIfcSlab slab, Xbim3DModelContext context, IGeometryStoreReader geometryStoreReader)
{
    var AllPoints = new List<List<CartesianPoint>>();
    var instances = context.ShapeInstancesOf(TheSlab);
    var instancesList = instances.ToList();
    var _geometries = instancesList.Select(i => geometryStoreReader.ShapeGeometryOfInstance(i) as IXbimShapeGeometryData);
    if (_geometries.Any())
    {
        var Positions = new List<CartesianPoint>();
        var productShape = instances.Where(s =>
                s.RepresentationType != XbimGeometryRepresentationType.OpeningsAndAdditionsExcluded);
            foreach (var instance in productShape)
            {
                var globalPos = instance.Transformation.Translation;
                var p = new CartesianPoint(globalPos.X, globalPos.Y, globalPos.Z);
                p.SetLabel(instance.IfcProductLabel);
                Positions .Add(p);
            }
        foreach (var geometry in _geometries)
        {
            XbimShapeTriangulation mesh;
            using (var ms = new MemoryStream(geometry.ShapeData))
            using (var br = new BinaryReader(ms))
            {
                mesh = br.ReadShapeTriangulation();
            }
            var pointList = new List<CartesianPoint>();
            foreach (var meshVertex in mesh.Vertices)
            {
                pointList.Add(new CartesianPoint(
                    Math.Round(meshVertex.X, 4),
                    Math.Round(meshVertex.Y, 4),
                    Math.Round(meshVertex.Z, 4)));
            }
            AllPoints.Add(pointList);
        }
    }
}

```

[samplelittleroom.zip](https://github.com/xBimTeam/XbimGeometry/files/3344718/samplelittleroom.zip)

**Comment by martin1cerny** [comment]
Hi Maggie, I appreciate you have invested some time already to investigate this but it is still hard to find your problem. Looking at the file in our viewer it seems to be all right:

![image](https://user-images.githubusercontent.com/773078/60431479-32ef7e00-9c00-11e9-870d-e1c51953cb63.png)

This means that you are either nor reading the right data or you expect something different to what is in the data. Can you try to post an example which would better expose your issue?

**Comment by tulip411** [comment]
> Hi Maggie, I appreciate you have invested some time already to investigate this but it is still hard to find your problem. Looking at the file in our viewer it seems to be all right:
> 
> ![image](https://user-images.githubusercontent.com/773078/60431479-32ef7e00-9c00-11e9-870d-e1c51953cb63.png)
> 
> This means that you are either nor reading the right data or you expect something different to what is in the data. Can you try to post an example which would better expose your issue?

Hi! Thank you for reply! I didn't mean I couldn't open it in the windouwsUI, I want only the vertices of the elements, and use them in other programme.  So I used Geometry engine as a reference, and just get the list of the cartesian points.

**Comment by tulip411** [comment]
I could show more in detail, the first figure is the output, and the second figure is the ifc file. from the file, the reference coordinates shoule be the one shown in the line 938, but it is 0,0,0 in the output.

And also the points from output are not really understandable.
 
![1](https://user-images.githubusercontent.com/46897676/60434707-17887100-9c08-11e9-9ee9-a70594c5645e.PNG)

![2](https://user-images.githubusercontent.com/46897676/60434715-1d7e5200-9c08-11e9-996b-cf7aed7843fd.PNG)

**Comment by SteveLockley** [comment]
Maggie you are assuming that the transformations translation is the origin of the geometry, this is incorrect. 
`var globalPos = instance.Transformation.Translation;
  var p = new CartesianPoint(globalPos.X, globalPos.Y, globalPos.Z);
  p.SetLabel(instance.IfcProductLabel);
  Positions .Add(p);`
You need to apply the transformation to every point of the geometry data you retrieve. So the globalPos above is not the point. The transformation contains all kinds of operations, mirror, move, scale etc

**Comment by tulip411** [comment]
> Maggie you are assuming that the transformations translation is the origin of the geometry, this is incorrect.
> `var globalPos = instance.Transformation.Translation; var p = new CartesianPoint(globalPos.X, globalPos.Y, globalPos.Z); p.SetLabel(instance.IfcProductLabel); Positions .Add(p);`
> You need to apply the transformation to every point of the geometry data you retrieve. So the globalPos above is not the point. The transformation contains all kinds of operations, mirror, move, scale etc

Thank zou for your reply! Could you tell me more in detail how to apply the transformation to every point of the geometry data? And further more, I found a interesting thing, the position is incorrect as I shown when the element(wall or slab etc.) has any openings, and it is correct when it doesn't has openings.

Sincerely 
Maggie

**Comment by tulip411** [comment]
> Maggie you are assuming that the transformations translation is the origin of the geometry, this is incorrect.
> `var globalPos = instance.Transformation.Translation; var p = new CartesianPoint(globalPos.X, globalPos.Y, globalPos.Z); p.SetLabel(instance.IfcProductLabel); Positions .Add(p);`
> You need to apply the transformation to every point of the geometry data you retrieve. So the globalPos above is not the point. The transformation contains all kinds of operations, mirror, move, scale etc

Thank you for your reply! Could you please tell me more in details that how to apply the transformation to every point of the geometry data? And further more, I found a interesting thing, the position is incorrect as I shown when the element(wall or slab etc.) has any openings, and it is correct when it doesn't has openings.

Sincerely
Maggie

**Comment by SteveLockley** [comment]
You simply multiply every point by the transform matrix. There are a number of ways to do this. You are working on the already triangulated model so just use the  Transform(XbimPoint3D p) method of the XbimMatrix3D with the XbimPoint3D as an argument. The reason you are getting different results with and without openings is simply because you are not applying the matrix transform correctly.
You can also more accurately work on the underlying geometry engine, this gives better results and more control.
Please look at some of the unit tests to see how to do this correctly, specifically SubtractionResultsInClosedWindow() test in https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Interop.Tests/IfcBooleanTests.cs 
The unit tests contain a lot of examples to help you here. I am closing this as it is not really an issue with the XbimGeometry engine

**Comment by tulip411** [comment]
> You simply multiply every point by the transform matrix. There are a number of ways to do this. You are working on the already triangulated model so just use the Transform(XbimPoint3D p) method of the XbimMatrix3D with the XbimPoint3D as an argument. The reason you are getting different results with and without openings is simply because you are not applying the matrix transform correctly.
> You can also more accurately work on the underlying geometry engine, this gives better results and more control.
> Please look at some of the unit tests to see how to do this correctly, specifically SubtractionResultsInClosedWindow() test in https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine.Interop.Tests/IfcBooleanTests.cs
> The unit tests contain a lot of examples to help you here. I am closing this as it is not really an issue with the XbimGeometry engine

Ok! I will try out. Thank you so much!

Sincerely
Maggie
