### ISSUE TITLE
How can I calculate inner wall length?

### ISSUE THREAD

**Issue by reasonconsequence** [xBimTeam/XbimGeometry#199]
I need get inner length of each wall(separately).
![image](https://user-images.githubusercontent.com/51324613/60720548-ce039300-9f33-11e9-8334-1b3df757d053.png)

Previously, I used to get length of wall in such way:
```
var wallLength= wall.Representation.Representations.FirstOrDefault(x => x.RepresentationType == "Curve2D")?.Items.OfType<IfcPolyline>().FirstOrDefault()
                    ?.Points.LastOrDefault()?.X;
```

**Comment by bekraft** [comment]
Hi,
the “inner” length is a property at the contact of space (not shown here) and the adjacent walls. The only way to retrieve this directly, is to compute the floor length (perimeter) of the enclosed room. Otherwise you have to compute the contact length.

**Comment by SteveLockley** [comment]
In addition you should look at the Ifc class IfcRelSpaceBoundary which may provide a route
