### ISSUE TITLE
How I can retrieve the inner direction of wall?

### ISSUE THREAD

**Issue by whiteamerica** [xBimTeam/XbimGeometry#200]
![image](https://user-images.githubusercontent.com/52708355/60963660-0df2bd80-a31a-11e9-8a86-fdc50b154b63.png)
Not just a direction of wall, but the direction that show which side of wall is inside the room.

**Comment by CamChatHel** [comment]
Hey, I would be interested in how you solved this problem because I also need this information. Can you shortly describe it?
