### ISSUE TITLE
How to retrieve openings(or child element) of specified wall?

### ISSUE THREAD

**Issue by whiteamerica** [xBimTeam/XbimGeometry#203]

**Comment by SteveLockley** [comment]
You would use the Ifc structure (IfcOpeningElement) to select the opening you want, then use the geometry engine to calculate the specific geometry for this opening. Note in the normal processing of the whole file we subtract openings from the wall so they become an integral part of the wall geometry. However, if you look at the code in Geometry.Scene to can see how to do this and retain information about the opening. The unit tests contain perhaps a simple example in SubtractionResultsInClosedWindow
