### ISSUE TITLE
How can I retrieve walls in specified IfcSpace?

### ISSUE THREAD

**Issue by whiteamerica** [xBimTeam/XbimGeometry#204]
Previously I do it using bounding box of ifcSpace and just calculate walls in the bounding box.
But how can I do it in this case?
![image](https://user-images.githubusercontent.com/52708355/62044664-2add2b00-b20c-11e9-98a7-8725e3a9d7f1.png)

**Comment by martin1cerny** [comment]
You can use one of many semantic relations in the model. These are easy to obtain but might not be present in the model.

![Simple_floor_plan_relations](https://user-images.githubusercontent.com/773078/62046160-848f2680-b207-11e9-910b-d8d178925173.png)

Geometric calculations are more reliable when implemented correctly which is not trivial. This is not specific to xBIM so I suggest you try to have a look at general geometric analysis. Proximity analysis of the space bounding faces might be one.

**Comment by SteveLockley** [comment]
I think this is now explained clearly thanks Martin so I am closing the issue
