### ISSUE TITLE
Error creating context

### ISSUE THREAD

**Issue by whiteamerica** [xBimTeam/XbimGeometry#205]
[IFC file link](https://we.tl/t-yYJqpuZrRb) 

```
this.m_context = new Xbim3DModelContext(this.m_ifcModel);
            this.m_context.CreateContext();
```

**Comment by martin1cerny** [comment]
![image](https://user-images.githubusercontent.com/773078/62205424-b29f7280-b38f-11e9-8eeb-64f52bc209de.png)

**Comment by whiteamerica** [comment]
@martin1cerny 
I'm using BIM Vision.
![image](https://user-images.githubusercontent.com/52708355/62205701-aff54b00-b398-11e9-8176-ae234e268527.png)
So this model has some unsupported stuff?

**Comment by martin1cerny** [comment]
When you say

> Error creating context

You need to post that error as well.

**Comment by martin1cerny** [comment]
Also, our viewer is not showing spaces geometry by default. 
![image](https://user-images.githubusercontent.com/773078/62206289-c055f780-b391-11e9-9c81-4b0d8e6dfdeb.png)

**Comment by whiteamerica** [comment]
@martin1cerny 
![image](https://user-images.githubusercontent.com/52708355/62207178-2e072100-b39c-11e9-983d-e3d43c15ae28.png)
But currently, I download nuget package. I'll try using sources

**Comment by martin1cerny** [comment]
...or have a look at the inner exception details for start. Also make sure you are using the latest version of xBIM.

**Comment by andyward** [comment]
Can you retest with the latest 5.1.307 geometry?

**Comment by andyward** [comment]
Closing as not heard back
