### ISSUE TITLE
Questions reading IfcMappedItem

### ISSUE THREAD

**Issue by tulip411** [xBimTeam/XbimGeometry#207]
Hello everyone,

By using IXbimGeometryEngine, an RepresentationItem can be created into IXbimSolid. But in the case of IfcMappedItem, are there any method reading it?

For example:
```csharp
var eas = model.Instances[272261] as IIfcExtrudedAreaSolid;
var geom = geomEngine.CreateSolid(eas);
```
I wonder if there are any similar procedure dealing with IfcMappedItem.

Looking forward to your reply and help.

Sincerely 
Maggie

**Comment by tulip411** [comment]
Well, I tried the method bellow:

```csharp
var theBeam= model.Instances[37582] as IIfcBeam;
var geometries = theBeam.Representation.Representations;
foreach (var geometry in geometries)
{
    var solids = geometry.Items;
    foreach (var solid in solids)
    {
        if (geometry is IIfcMappedItem mappedItem)
        {
            var mappingSource = mappedItem.MappingSource;
            var mappingTarget = mappedItem.MappingTarget;

            var representation = mappingSource.MappedRepresentation;
            var origin = mappingSource.MappingOrigin;

            var item = representation.Items.FirstOrDefault() as IIfcGeometricRepresentationItem;
            var geo = GeomEngine.Create(item, (IIfcAxis2Placement3D)origin);
            var xbimSolid = GeomEngine.Transformed(geo, mappingTarget) as IXbimSolid;
        }
    }
}

```

But the xbimSolid returned out to be null. I attached the file of the only the Beam from the project file. And the file can not be displayed in the WindowsUI. Does anyone know the reason?

Sincerely
Maggie
[beam.zip](https://github.com/xBimTeam/XbimGeometry/files/3476083/beam.zip)

**Comment by martin1cerny** [comment]
Well, the file you are posting is incomplete:
![image](https://user-images.githubusercontent.com/773078/62619280-acbd0a80-b916-11e9-9667-b773e251d838.png)
The geometry is defined in the context which doesn't exist in the file.
When I repointed the geometry to the 'Model' context, it worked fine:
![image](https://user-images.githubusercontent.com/773078/62619338-ccecc980-b916-11e9-8681-79e05f627c11.png)

To your actual question - try to have a look here: https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L1223

**Comment by tulip411** [comment]
Ah Ok, I think I missed some lines. But thank you so much. I would close the issue.

Sincerely
Maggie
