### ISSUE TITLE
Swapped width and height

### ISSUE THREAD

**Issue by whiteamerica** [xBimTeam/XbimGeometry#208]
![image](https://user-images.githubusercontent.com/52708355/62763399-23334700-ba94-11e9-921a-6eb861f9ca9a.png)
On the screenshot you can see that height must be longer than width
[ifc file](https://we.tl/t-PFtGuzaZZi)

In which cases height and width can swap?

**Comment by martin1cerny** [comment]
Ask the authoring SW.
