### ISSUE TITLE
How to get the final matrix for an element?

### ISSUE THREAD

**Issue by michealChin** [xBimTeam/XbimGeometry#21]
Hi,

The code is as below:

IEnumerable<IfcProduct> toDraw = refModel.InstancesLocal.OfType<IfcProduct>().Where(t => !(t is IfcFeatureElement));
TransformGraph graph = new TransformGraph(refModel);
graph.AddProducts(toDraw); //load the products as we will be accessing their geometry

    public static void ReadBuilding(IfcBuildingStorey f)
        {
            foreach (IfcRelContainedInSpatialStructure p in f.ContainsElements)
            {
                foreach (IfcProduct t in p.RelatedElements)
                {
                    if (t is IfcColumn)
                    {
                             XbimMatrix3D matrix = graph[t].WorldMatrix();
                             .....
                    }
                     else if (t is IfcBeam)
                     {
                     
                     }
                     else if (t is IfcSlab)
                     {
                     
                     }
                  }
              }
       }

I use graph[t].WorldMatrix() to access the matrix of the element and it is working fine for every elements such as IfcColumn, IfcBeam and IfcWall. Except the IfcSlab where after multiply the geometry with graph[t].WorldMatrix() it returns a wrong orientation. May I know what is the problem? Is there any alternative way to get the final matrix or geometry correctly? Thanks in Advance.

**Comment by SteveLockley** [comment]
You should look in the geometry engine. Look at the XbimPlacementTree.cs file in Xbim.Geometry.Scene to see how to build placement trees, or just use it
