### ISSUE TITLE
IIfcFacetedBrep failed to be created as IXbimSolid by using XbimGeometryEngine

### ISSUE THREAD

**Issue by tulip411** [xBimTeam/XbimGeometry#210]
Hi there,

I recently met an ifc item that can not be created as IXbimSolid. I used the following code and the "solid" turned out to be null. Can anyone explain this? I have attached the ifc file.

Looking forward to reply! Thank you.

Sincerely 
Maggie

```csharp
public static void Main(string[] args)
{
    var geomEngine = new XbimGeometryEngine();
    using (var model = IfcStore.Open(@"C:\Users\Tester\Desktop\new 1.ifc"))
    {
        var slab = model.Instances[6320] as IIfcSlab;
        var geometries = slab.Representation.Representations;
        var geometryItem = geometries.FirstOrDefault().Items.FirstOrDefault();
        if (geometryItem  is IIfcFacetedBrep factedBrep)
        {
            var solid = geomEngine.CreateSolidSet(factedBrep).First;
        }
    }
}
```

[new 1.zip](https://github.com/xBimTeam/XbimGeometry/files/3508668/new.1.zip)

**Comment by martin1cerny** [comment]
Watch the log:
```
ERR GeomEngine: #6315="IfcClosedShell" ["Failed to create a valid solid from an IfcClosedShell"]
WRN GeomEngine: #6315="IfcClosedShell" ["Very small closed IfcClosedShell has been ignored"]
WRN GeomEngine: #6316="IfcFacetedBrep" ["Empty or invalid solid"]
```

This means that the geometry of this shape is not valid. However, as a faceted brep it can still be tessellated and visualised (we use `XbimTesselator` for this):

![image](https://user-images.githubusercontent.com/773078/63156675-7b7ac380-c015-11e9-9c73-601a854c7749.png)

But this can't be used for any subsequent geometrical operations/analyses.

**Comment by tulip411** [comment]
> Watch the log:
> 
> ```
> ERR GeomEngine: #6315="IfcClosedShell" ["Failed to create a valid solid from an IfcClosedShell"]
> WRN GeomEngine: #6315="IfcClosedShell" ["Very small closed IfcClosedShell has been ignored"]
> WRN GeomEngine: #6316="IfcFacetedBrep" ["Empty or invalid solid"]
> ```
> 
> This means that the geometry of this shape is not valid. However, as a faceted brep it can still be tessellated and visualised (we use `XbimTesselator` for this):
> 
> ![image](https://user-images.githubusercontent.com/773078/63156675-7b7ac380-c015-11e9-9c73-601a854c7749.png)
> 
> But this can't be used for any subsequent geometrical operations/analyses.

Hi! 

Thank you so much!

As for the XbimTesselator, is that possible for me to instantiation this class from this IfcFacetedBrep? So that I could obtain geometric information. I don't need to make any operations and analysis.

Sincerely 
Maggie

**Comment by martin1cerny** [comment]
Yes, see `Xbim3DModelContext` for more details about how it can be used.

**Comment by tulip411** [comment]
> `Xbim3DModelContext`

Ok! Thank you so much! I would close this issue.
