### ISSUE TITLE
Need to be able to drill down into Relspaceboundaries 

### ISSUE THREAD

**Issue by Cymap-NZ** [xBimTeam/XbimGeometry#211]
I can drill down from Relspaceboundary-IfCconnectionGeometry.  But beyond that relationship (at least in code) none of the other properties or relations are visible.  
Essentially I need to access the Internal (IfcPolyline) and external boundaries (IfcPolyline).  So I can determine the exact internal surface areas of internal faces of spaces.  It appears these are all non-public properties.   Without direct access to those properties it is almost impossible to determine the surface areas of interior walls/floors/ceilings etc.  I need those values in order to to calculate heat-loss for a given space. 

When running code, you can see some of these items in in non-public properties.  Potentially I could use system reflection to perhaps iterate thru the hidden types. But am wondering why those relations/properties are not accessible even if they are read only?

**Comment by martin1cerny** [comment]
I'm not sure what you think is hidden. xBIM exposes 100% of IFC when it reads it. You can drill up and down in the IFC structures at your will. Can you post a code example to demonstrate your issue please?

**Comment by Cymap-NZ** [comment]
var faces = space.BoundedBy.ToList(); //these will be the Relspaceboundaires in the IFC file
            foreach (var face in faces)
            {
                if (face.RelatedBuildingElement != null)
                {        // get the name of the element and its Transmittance
                  if (face.ConnectionGeometry != null)
                    {       
                          var ConnGeom = face.ConnectionGeometry;  

//cant drill down here to get to the Surface on Relating Elements/IFCcurve (inner/outer boundaries and the polylines that define them?               
                   
                   However If I place a breakpoint at this point in my code and then view the properties SurfaceOnRelatingElement is shown?  But pro-grammatically you cant directly access them.   Was wondering why they are hidden properties?   I was considering using system reflection to drill down to those values? 

![image](https://user-images.githubusercontent.com/32688638/63298714-48437780-c328-11e9-89b3-17befd013375.png)

**Comment by martin1cerny** [comment]
`IfcRelSpaceBoundary.ConnectionGeometry` is of type `IfcConnectionGeometry`. That is [an abstract super-type](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcconnectiongeometry.htm). To access specific properties (of [IfcConnectionSurfaceGeometry](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcconnectionsurfacegeometry.htm) in your case), you need to cast it to a specific type. This is not an xBIM feature but a matter of inheritance in any object model.

```cs
var relBoundary = space.BoundedBy.FirstOrDefault();
if (relBoundary.ConnectionGeometry is IfcConnectionSurfaceGeometry csg)
{
    var relatingSurface = csg.SurfaceOnRelatingElement;
    if (relatingSurface is IfcCurveBoundedPlane plane)
    {
        var boundary = plane.OuterBoundary;
    }
}
```

**Note:** This code is only for demonstration purpose. It doesn't do any safety checks for nulls and is only specific to types used in your example.

**Comment by Cymap-NZ** [comment]
@martin1cerny .  Thanks I've used something similar to your code to drill right down to the IfcPolyline of each Internal surface of the space. 

I can now evaluate those co-ordinates to get the internal surface areas of each Relspaceboundary.   Which is at least the Geometric problem solved.   You have been most helpful.
