### ISSUE TITLE
Numeric inprecision with dislocated models

### ISSUE THREAD

**Issue by Tpullmann** [xBimTeam/XbimGeometry#213]
Attached there is an IFC with a single element. The location if the element is widely shifted, so the mantissa seems not to be large enough to keep the reqired numeric precision. When converting to WexBim (also attached) or XBim, the model looks pretty ugly. 
In XBimExplorer and many other tools the IFC is ok. 

Is there a bestPractice how to convert these models to reduce the numeric truncation? A general transformation before exporting for instance?

[Wall shifted.zip](https://github.com/xBimTeam/XbimGeometry/files/3556482/Wall.shifted.zip)

**Comment by martin1cerny** [comment]
This is exactly the problem described in https://github.com/xBimTeam/XbimWebUI/issues/240

There is a possibility to transform the wexBIM daa with certain translation like this:

```cs
var context = new Xbim3DModelContext(model);
context.CreateContext(null, false);

IVector3D translation = null;
using (var store = model.GeometryStore.BeginRead())
{
    var regions = store.ContextRegions.SelectMany(r => r).ToList();
    var biggest = regions.OrderByDescending(r => r.Population).FirstOrDefault();
    if (biggest != null)
    {
        var c = biggest.Centre;
        translation = new XbimVector3D(-c.X, -c.Y, -c.Z);
    }
}

var wexBimFilename = Path.ChangeExtension(fileName, "wexbim");
using (var wexBimFile = File.Create(wexBimFilename))
{
    using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
    {
        model.SaveAsWexBim(wexBimBinaryWriter, null, translation);
        wexBimBinaryWriter.Close();
    }
    wexBimFile.Close();
}
```

The result seems to be OK:
![image](https://user-images.githubusercontent.com/773078/64001898-2193f680-cb09-11e9-869c-0ac242f4ce6e.png)

Also, note you need to use the latest version of XbimGeometry where the data is handled with improved precision internally.

**Comment by Tpullmann** [comment]
Thanks a lot! For the prevoius sample (and many others) that works, but for attached strange column it doesn't. Do you have an idea?
[column_shifted.zip](https://github.com/xBimTeam/XbimGeometry/files/3584063/column_shifted.zip)

**Comment by andyward** [comment]
Closing this. Please raise another issue if there's a follow-on case to investigate.
