### ISSUE TITLE
Please help to could not load file or assembly Xbim.Geometry.Engine64 or one of its dependencies

### ISSUE THREAD

**Issue by castronelson** [xBimTeam/XbimGeometry#215]
#### Minimal code (or steps) to reproduce the issue:
```js
var viewer = new Viewer(canvas);
(...)
```

#### Minimal file to reproduce the issue:
*(IFC files need to be zipped to be uploaded. Than just drag & drop here)*

**Comment by andyward** [comment]
Make sure the `Xbim.Geometry.Engine64.dll` DLL is being copied into your websites's bin\[Config] folder.

**Comment by castronelson** [comment]
Dear all,

 

I have copied that dll into websites bin folder and also added in reference, even though we have the problem please help me regarding

 

Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation.

 


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/>

**Comment by castronelson** [comment]
Dear all, 

 

The below error showing ,please provide any solutions or sample code for converting IFC file to WEXBIM



 


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/> 

 

 

From: Castro Nelson D, SIERRA [mailto:castro.nelson@sierratec.com] 
Sent: 11 September 2019 10:18
To: 'xBimTeam/XbimGeometry' <reply@reply.github.com>; 'xBimTeam/XbimGeometry' <XbimGeometry@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [xBimTeam/XbimGeometry] Please help to could not load file or assembly Xbim.Geometry.Engine64 or one of its dependencies (#215)

 

Dear all,

 

I have copied that dll into websites bin folder and also added in reference, even though we have the problem please help me regarding

 

Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation.

 


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/>

**Comment by martin1cerny** [comment]
Please, refer to issues already resolved:
#153 #159 #189 #193 #195

**Comment by castronelson** [comment]
Dear all,

 

We had a problem that is

 

Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation

 

The solution you provided here are related to assembly loading of Xbim.Geometry.Engine64.

Why there get_logger Error,

Please let me know any solution

**Comment by martin1cerny** [comment]
Please, use the package manager to keep the right version dependencies of all packages and dlls.

**Comment by castronelson** [comment]
Hi ,

 

Could you please suggests some sample or blog for convert IFC to WEXBIM using C#

Else samples which used Xbim.Geometry.Engine64.dll (64 bit dll)   , because we are facing below issue even though if we’re created from new project

 

Method 'get_Logger' in type 'Xbim.Geometry.XbimGeometryCreator' from assembly 'Xbim.Geometry.Engine64, Version=0.0.0.0, Culture=neutral, PublicKeyToken=11e3655e576ec5a9' does not have an implementation

**Comment by martin1cerny** [comment]
http://docs.xbim.net/examples/creating-wexbim-file.html

**Comment by castronelson** [comment]
Okay fine. These coding are we developed and facing issues, 

Do you know any other method to convert IFC to WEXBIM except below

http://docs.xbim.net/examples/creating-wexbim-file.html

**Comment by castronelson** [comment]
Any source code for IFC to WEXBIM conversion?

 


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/> 

 

 

From: Castro Nelson D, SIERRA [mailto:castro.nelson@sierratec.com] 
Sent: 12 September 2019 12:04
To: 'xBimTeam/XbimGeometry' <reply@reply.github.com>; 'xBimTeam/XbimGeometry' <XbimGeometry@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [xBimTeam/XbimGeometry] Please help to could not load file or assembly Xbim.Geometry.Engine64 or one of its dependencies (#215)

 

Okay fine. These coding are we developed and facing issues, 

Do you know any other method to convert IFC to WEXBIM except below

http://docs.xbim.net/examples/creating-wexbim-file.html

**Comment by castronelson** [comment]
Dear all,

 

Could you check if we share our coding and dll using in project to converting IFC to WEXBIM only

 


Best Regards,

Castro Nelson D

Software Engineer

Email:  <mailto:castro.nelson@sierratec.com> castro.nelson@sierratec.com | Voice: +91-422-711 5566, +91 93632-20483 | Ext. 508


 <http://www.greenestbuilding.com/> 

WORLD'S SECOND HIGHEST RANKING GREEN BUILDING

rated by GBCI under LEED NC v2009

                                <https://www.greenestbuilding.com/efacility-building-walkthrough-worlds-second-greenest-building/>

**Comment by andyward** [comment]
Can you take this over to https://github.com/andyward/XbimWebDemo/issues

**Comment by Rachvel** [comment]
See solution in [#312](https://github.com/xBimTeam/XbimGeometry/issues/312#issuecomment-2312640981), you may interest.
