### ISSUE TITLE
Exception while converting ifc to wexbim 

### ISSUE THREAD

**Issue by Princepra** [xBimTeam/XbimGeometry#219]
while running the code, got exception like :- 

Exception thrown: 'System.IO.FileLoadException' in Xbim.Geometry.Engine.Interop.dll
The program '[20300] 12test.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.

and file not converted.

**here are my codes:-**

using System;
using System.IO;
using Xbim.Ifc;
using Xbim.ModelGeometry.Scene;
using Xbim.Geometry.Engine.Interop;

namespace _12test
{
    class Program
    {
        public static void Main(string[] args)
        {
            var fileName = "Ar.ifc";
            using (var model = IfcStore.Open(fileName))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(fileName, "wexBIM");
                using (var wexBiMfile = File.Create(wexBimFilename))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }  
            }

            Console.WriteLine();   
        }
    }
}

**Comment by martin1cerny** [comment]
Please, search closed issues for this.
