### ISSUE TITLE
XbimGeometry v5.0.163 Source

### ISSUE THREAD

**Issue by jcochrane007** [xBimTeam/XbimGeometry#221]
Is the source code for XbimGeometry v5.0.163 available?  I don't see a release or a tag for that version.

**Comment by andyward** [comment]
Sorry, it looks like we didn't tag it for Geometry. But I think you should be able to get the source from https://github.com/xBimTeam/XbimGeometry/commit/fcce2266cb75e4bc53c5679b8941eaa944a218b0 which was the last master commit from the release
