### ISSUE TITLE
ifcstore.saveasifc(stream) not working 

### ISSUE THREAD

**Issue by divyanatsteel** [xBimTeam/XbimGeometry#229]
Hi,
I have code:    

``` csharp
public ActionResult AddProperty(string id, string comments, string fileName)
        {
            var authManager = new OfficeDevPnP.Core.AuthenticationManager();

            var ctx = authManager.GetWebLoginClientContext("https://natsteel.sharepoint.com/sites/BIM-Models");
            Uri bUri = new Uri(site);
            Uri ifcModel = new Uri(bUri, fileName);

            string strTemp = Path.GetExtension(ifcModel.ToString()).ToLower();

            string geometryFileName = Path.ChangeExtension(fileName, ".wexbim");
            string xbimFileName = Path.ChangeExtension(fileName, ".xbim");

            var web = ctx.Web;

            ctx.Load(web);
            ctx.ExecuteQuery();
            List docs = web.Lists.GetByTitle("Documents");
            Folder folder = docs.RootFolder.Folders.GetByUrl("BIM_Test");
            ctx.Load(folder);
            ctx.ExecuteQuery();
            ctx.Load(folder.Files);
            ctx.ExecuteQuery();
            //  string geometryFileName =Uri.ch(ifcModel, ".wexbim");
            if (folder.Files.Count > 0)
            {

                foreach (Microsoft.SharePoint.Client.File file in folder.Files.ToList())
                {
                    if (file.Name == fileName)
                    {
                        using (var xml = Microsoft.SharePoint.Client.File.OpenBinaryDirect(ctx, file.ServerRelativeUrl).Stream)
                        {
                            byte[] binary = ReadFully(xml);
                            Stream final = new MemoryStream();
                            MemoryStream stream1 = new MemoryStream(binary);

                            using (var model = IfcStore.Open(stream1, Xbim.IO.StorageType.Ifc, Xbim.Common.Step21.XbimSchemaVersion.Ifc2X3, XbimModelType.MemoryModel))
                            {
                                using (var txn = model.BeginTransaction("Properties"))
                                {

                                    var entity = model.Instances.FirstOrDefault<Xbim.Ifc2x3.Kernel.IfcProduct>(d => d.GlobalId == id);
                                    var prop = model.Instances.New<Xbim.Ifc2x3.PropertyResource.IfcPropertySingleValue>(p =>
                                    {
                                        p.Name = "comment";
                                                // IfcValue valeur = "0";
                                                //p.NominalValue = valeur;
                                                p.NominalValue = new Xbim.Ifc2x3.MeasureResource.IfcText(comments);
                                    });

                                    var pSet = model.Instances.New<Xbim.Ifc2x3.Kernel.IfcPropertySet>(ps =>
                                    {
                                        ps.Name = "comments"; //this SHOULDN'T start with 'Pset_'
                                                              //ps.HasProperties.Add_Reversible(prop);
                                                ps.HasProperties.Add(prop);
                                    });
                                    entity.AddPropertySet(pSet);
                                    txn.Commit();

                                    ExportGeometryData(fileName,model);

                                }
```
I try to save model mean 's ifcstore saveas ifc file empty ifcfile is creating how overcome this problem

**Comment by divyanatsteel** [comment]
private static void ExportGeometryData(string geometryFileName, IModel model)
        {
            using (var wexBimFileStream = new MemoryStream())

            {
                var authManager = new OfficeDevPnP.Core.AuthenticationManager();
                var ctx = authManager.GetWebLoginClientContext("https://natsteel.sharepoint.com/sites/BIM-Models");

                FileCreationInformation fileCreationInfo = new FileCreationInformation();
             
                string extension = Path.GetExtension(geometryFileName);
                if(extension ==".ifc")
                {
                    BinaryWriter writer = new BinaryWriter(wexBimFileStream);
                    model.SaveAsWexBim(writer);
                    fileCreationInfo.ContentStream = wexBimFileStream;
                    writer.Flush();
                    model.SaveAsIfc(wexBimFileStream);
                }
                else
                {
                    BinaryWriter writer = new BinaryWriter(wexBimFileStream);
                    model.SaveAsWexBim(writer);
                    fileCreationInfo.ContentStream = wexBimFileStream;
                    writer.Flush();
                }
               

                //You have to rewind the MemoryStream before copying
                wexBimFileStream.Seek(0, SeekOrigin.Begin);

                fileCreationInfo.Url = Path.GetFileName(geometryFileName);
                fileCreationInfo.Overwrite = true;
                Web myweb = ctx.Web;
                List docs = myweb.Lists.GetByTitle("Documents");
                Folder folder = docs.RootFolder.Folders.GetByUrl("BIM_Test");
                File uploadFile = folder.Files.Add(fileCreationInfo);
                ctx.Load(uploadFile);
                ctx.ExecuteQuery();


            }

**Comment by andyward** [comment]
1. You're not generating any Geometry so `SaveAsWexBim` will not output anything

If you want geometry, you need to add this before calling Save:
``` csharp
  var context = new Xbim3DModelContext(model);
  context.CreateContext();
```

2. For the *.ifc path, in ExportGeometry it looks like you're trying to save the IFC to the same memory stream you've used for `SaveAsWexbim`

**Comment by divyanatsteel** [comment]
yes I too notify now why not working   model.SaveAsIfc(wexBimFileStream);

**Comment by andyward** [comment]
OK, Can we close then?

**Comment by divyanatsteel** [comment]
after  model.SaveAsIfc(wexBimFileStream); this line I am try to save a file I got exception"System.ObjectDisposedException: 'Cannot access a closed Stream."

**Comment by divyanatsteel** [comment]
fileCreationInfo.ContentStream = wexBimFileStream;
