### ISSUE TITLE
How to get top face of space(coordinates)?

### ISSUE THREAD

**Issue by whiteamerica** [xBimTeam/XbimGeometry#230]
Top face shape of space?
![image](https://user-images.githubusercontent.com/52708355/69433590-8cd61900-0d44-11ea-860b-1235699640c6.png)

**Comment by andyward** [comment]
Looks like you've got it all figured out by the screen shot...

**Comment by whiteamerica** [comment]
> Looks like you've got it all figured out by the screen shot...

But how I can retrieve this shape, I have all points retrieved via context.ShapeInstanceOf().

**Comment by andyward** [comment]
> Top face shape of space?

If you ask a clearer question you'll probably get a clearer answer. No one can answer this question as it's not clear what you want or what you've tried.

**Comment by bekraft** [comment]
What do you mean by retrieve? It is a face of a solid. Have a look into the meshing context. Or do you mean how to classify such a face in general? In this case a “top” face will have normals pointing mostly upwards (positive Z direction here). Compute the dot product of each and select all faces having a result value greater some positive tolerance. A basic knowledge of vector algebra will help you.
