### ISSUE TITLE
Certain IFC breaks CreateContext() without any change to code nor dependencies

### ISSUE THREAD

**Issue by Dakki97** [xBimTeam/XbimGeometry#232]
A certain .ifc causes CreateContext to crash, while others work. This issue was not present a week ago
#### Assemblies and versions affected:

I use XbimGeometry 4.0.11 and XbimEssentials 4.07 and those have worked for nearly a year now. Is there any reason why they should be breaking now if I did not update anything?

```csharp
using (var model = IfcStore.Open("BIM_MODELL_16.ifc"))
{
                Console.WriteLine("Creating Geometry");
                var context = new Xbim3DModelContext(model);
                context.CreateContext(); // breaks here System.Runtime.InteropServices.SEHException
                Console.WriteLine("Processing the BIM-Data");
            }

}
```
[BIM MODELL_16.zip](https://github.com/xBimTeam/XbimGeometry/files/3905504/BIM.MODELL_16.zip)
the exact .ifc that is breaking

**Comment by andyward** [comment]
I'm assuming the IFC model has not changed? 

I've just loaded in the latest version of v4 Xbim Xplorer and v5.1 and it opened OK with no warnings/errors, so I'm guessing it's something environmental. 

Is it just this model that stopped working?  
Have you tried it with the same code on another machine?

If you're still having issues it may help to have the stack trace (or see whats in the windows event log)

**Comment by Dakki97** [comment]
Using the newest version of XBimGeometry works, but it is still worrying that it stopped suddenly without any changes

**Comment by andyward** [comment]
Sounds like a runtime change of some kind. I know we've been impacted by newer versions of Windows 10 SDKs breaking things...
