### ISSUE TITLE
Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies.

### ISSUE THREAD

**Issue by manikandan0598** [xBimTeam/XbimGeometry#233]
Hi,
We have tried to convert the IFC file to Wexbim. we have received the below error.
We have used Visual Studio 2017 and  .Net framework 4.7.1.
We hosted our application in 64 bit.

We have used the below code for IFC to WexBim Conversion.
protected void ConvertIFCtoWEXBIM(string filePath)
{
var IfcTestFile = filePath;
using (var model = IfcStore.Open(IfcTestFile))
{
var context = new Xbim3DModelContext(model);
context.CreateContext();
         var wexBimFilename = Path.ChangeExtension(IfcTestFile, "wexbim");
         using (var wexBiMfile = File.Create(wexBimFilename))
         {
             using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
             {
                 model.SaveAsWexBim(wexBimBinaryWriter);
                 wexBimBinaryWriter.Close();
             }
             wexBiMfile.Close();
         }
     }
 }

We have received the below error
**Could not load file or assembly 'Xbim.Geometry.Engine.dll' or one of its dependencies. The system cannot find the file specified.** 

Also we have uploaded our solution in the below repository.
https://github.com/manikandan0598/BIMWebApp.git

In the above uploaded solution, the IFC file will be uploaded using browse control. After browsing the IFC file, the IFC to WexBim conversion handled in the button click.

Could you please help to resolve this issue.
Thank you in Advance.

**Comment by martin1cerny** [comment]
Please, see [issues already solved](https://github.com/xBimTeam/XbimGeometry/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+Xbim.Geometry.Engine).

**Comment by manikandan0598** [comment]
Hi,
Thank you for the suggestion.
We have checked the issue id 218 and we have tried all the steps suggested in the issue id 218.

But it will not help us. We have uploaded our sample application in GitHub. 
https://github.com/manikandan0598/BIMWebApp.git
We need to resolve this issue ASAP because of an urgency.
Could you please help on this.

**Comment by martin1cerny** [comment]
I'm sorry, but we don't have resources to debug complex solutions. If you can replicate the exception with a few lines of code or a simple minimal command line application, we will have a look.

**Comment by manikandan0598** [comment]
Hi,
Below is the exception lines.


**Server Error in '/' Application.

Could not load file or assembly 'Xbim.Geometry.Engine.dll' or one of its dependencies. The system cannot find the file specified. 
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.IO.FileNotFoundException: Could not load file or assembly 'Xbim.Geometry.Engine.dll' or one of its dependencies. The system cannot find the file specified.

Source Error: 

Line 46:             {
Line 47:                 var context = new Xbim3DModelContext(model);
Line 48:                 context.CreateContext();
Line 49: 
Line 50:                 var wexBimFilename = Path.ChangeExtension(IfcTestFile, "wexbim");
  
Source File:  D:\Sample Projects\WebApplication2\WebApplication2\IFCTest.aspx.cs

Assembly Load Trace: The following information can be helpful to determine why the assembly 'Xbim.Geometry.Engine.dll' could not be loaded.**

**Comment by martin1cerny** [comment]
This means that `Xbim.Geometry.Engine.dll` is not where xBIM expects it to be - in the binary folder. Please, make sure your deployment considers this dll. It is loaded in runtime so some deployment tools don't recognize it as a runtime dependency.

**Comment by manikandan0598** [comment]
Hi,
We have followed the below Steps:
1. We have copied the "Xbim.Geometry.Engine64.dll" into the bin folder.
2. Create virtual directory for the application.
3. In Application Pool - set the "Enable 32-Bit Applications" to "**False**" 
4. Run the application - **It is working fine without issues**

But it is not working while running the application via Visual Studio 2017 (debug mode). The below error will be occurred while loading the application.

**Server Error in '/' Application.

Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies. An attempt was made to load a program with an incorrect format.** 

Thank you in advance.

**Comment by andyward** [comment]
You're trying to load a 64bit DLL into a 32 bit process. I'd guess you're running under IIS Express? That defaults to 32bits...

If so you need to either:

1. deploy JUST the 32 bit Xbim.Geometry.Engine86.dll 
or
2. configure IIS express to run the 64 bit version. e.g.

![image](https://user-images.githubusercontent.com/923699/70548599-c099a700-1b6a-11ea-95b9-2bf1f73ff4cc.png)
