### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void Xbim.ModelGeometry.Scene.Xbim3DModelContext

### ISSUE THREAD

**Issue by kiran-Ankappa** [xBimTeam/XbimGeometry#238]
I am trying to convert ifc file into wexBIM formate with the following code.

var resp = @"test.ifc";
string ifcFilePath = resp;
	using (var model = IfcStore.Open(ifcFilePath))
	{
		var context = new Xbim3DModelContext(model);
		context.CreateContext();
		var wexBimFilename = Path.ChangeExtension(ifcFilePath, "wexBIM");
		
		using (var wexBiMfile = System.IO.File.Create(wexBimFilename))
		{
			using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
			{
				model.SaveAsWexBim(wexBimBinaryWriter);
				wexBimBinaryWriter.Close();
			}
			wexBiMfile.Close();
		}
	}
                

but on execution i am getting following run time error. 

System.MissingMethodException: Method not found: 'Void Xbim.ModelGeometry.Scene.Xbim3DModelContext..ctor(Xbim.Common.IModel, System.String, System.String, Microsoft.Extensions.Logging.ILogger)'.

I add the latest xbim packages from nuget. Please help me with this error.

**Comment by andyward** [comment]
You must have some mis-matched assembly versions. 

Make sure you're on the latest. 

Can you specify exactly what versions of the nuget packages you're using, and confirm the FileVersions on the XBIM assemblies?

**Comment by kiran-Ankappa** [comment]
Thank you for the quick response 

packages i have installed: 
Xbim.Exchange -Version 5.1.179
Xbim.Cobie -Version 5.1.179
Xbim.Geometry -Version 5.1.288
Xbim.Essentials -Version 5.1.274

Assembly version of packages installed

Xbim.Ifc2x3
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
   
----------------------------------------
Xbim.Geometry.Engine.Interop
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.288.0
    
----------------------------------------
Xbim.IO.MemoryModel
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
----------------------------------------
Xbim.ModelGeometry.Scene
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.288.0
----------------------------------------
Xbim.Ifc4
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
----------------------------------------
Xbim.Ifc
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
----------------------------------------
Xbim.Common
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
----------------------------------------
Xbim.Ifc4
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.Ifc2x3
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.Ifc
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.Common
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.Ifc
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.Common
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------
Xbim.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
----------------------------------------

**Comment by kiran-Ankappa** [comment]
Thank you for quick response

packages i have installed:
Xbim.Exchange -Version 5.1.179
Xbim.Cobie -Version 5.1.179
Xbim.Geometry -Version 5.1.288
Xbim.Essentials -Version 5.1.274


package assembly version I got in in exception 

Xbim.Ifc
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
	
Xbim.Common
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
	
Xbim.IO
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
	
Xbim.Ifc4
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
	
Xbim.Ifc2x3
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.1711.28493
	
Xbim.Ifc
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
	
Xbim.Common
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
	
Xbim.ModelGeometry.Scene
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.288.0
	
Xbim.Ifc4
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
	
Xbim.IO.MemoryModel
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
	
System.IO.Compression
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
	
Xbim.Ifc2x3
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.274.0
	
Xbim.Geometry.Engine.Interop
    Assembly Version: 5.1.0.0
    Win32 Version: 5.1.288.0

**Comment by andyward** [comment]
Here's your problem:

> Xbim.Ifc
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.1711.28493
> 
> Xbim.Common
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.1711.28493
> 
> Xbim.IO
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.1711.28493
> 
> Xbim.Ifc4
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.1711.28493
> 
> Xbim.Ifc2x3
> Assembly Version: 4.0.0.0
> Win32 Version: 4.0.1711.28493

These are v4 Xbim assemblies somehow running along side v5.1 Geometry. There are breaking changes between these 2 releases., hence the missing method exception. It looks like you may even have multiple versions if some assemblies loaded which will cause all kinds of issues. Are you using the GAC or referencing from a private lib folder?

I'd clean down all your bin folders and work out where you're referencing xbim dlls from

**Comment by kiran-Ankappa** [comment]
Actually. My project is a class library. Add on created for revite. In that
add-on i am trying to use your library. If i create Console application it
is working fine. But if try to implement it in add-on it throws error.

I tried many things like clearing bin file, manually replacing dll file in
bin. I even created  new project from scratch and added only code to
convert from IFC to wexbim format still it is not working.

Is there anything else I could try?
