### ISSUE TITLE
xBimGeometry with wine and dotnet472

### ISSUE THREAD

**Issue by tloesch** [xBimTeam/XbimGeometry#239]
Iam not able to run xBimGeometry with wine on linux.
Has someone already tried this? And what were the results?

#### Assemblies and versions affected:

xBimGeometry v5.1.288

#### Steps (or code) to reproduce the issue:

Linux (Ubuntu) Wine with dotnet742 and a test binary that utilize the xBimGeometry Library

#### Expected behavior:

Execute the binary without errors

#### Actual behavior or exception details:

**Errormessage:**
0009:fixme:mscoree:parse_supported_runtime sku=L".NETFramework,Version=v4.7.2" not implemented

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Xbim.Ifc.IfcStore' threw an exception. ---> System.TypeLoadException: Could not load type of field 'Xbim.Common.XbimLogging:_loggerFactory' (0) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>
  at Xbim.Ifc.IfcStore..cctor () [0x00000] in <c805b7b3216949a5a57e6251db7460de>:0
   --- End of inner exception stack trace ---
  at xBimGeometryTest.Program.Main (System.String[] args) [0x00020] in <7c51d9f7749f4454bc1193f5d35cabd7>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'Xbim.Ifc.IfcStore' threw an exception. ---> System.TypeLoadException: Could not load type of field 'Xbim.Common.XbimLogging:_loggerFactory' (0) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:<none>
  at Xbim.Ifc.IfcStore..cctor () [0x00000] in <c805b7b3216949a5a57e6251db7460de>:0
   --- End of inner exception stack trace ---
  at xBimGeometryTest.Program.Main (System.String[] args) [0x00020] in <7c51d9f7749f4454bc1193f5d35cabd7>:0

**Comment by andyward** [comment]
I'm not familiar with running under Wine. The issue here doesn't look like geometry - looks like you're missing the .netcore runtime/SDK.

Assuming you get Essentials running then I guess the next challenge will be Geometry (which uses Mixed Mode Assemblies ). I'm not 100% how this will work under Wine - it may just work, or it could be a world of pain!

Please keep us informed on how you get on
