### ISSUE TITLE
ShapeGeometryMeshOf bug based on CultureInfo

### ISSUE THREAD

**Issue by bartekzgo** [xBimTeam/XbimGeometry#24]
Hi.
I'm trying to convert ifc file into Vertices, Triangles structure. I'm using ShapeGeometryMeshOf. I discover that on some machines this is working perfectly on other I obtain point list that is corrupted. After hours of research I found that I can simulate this problem by changing number format in windows settings. If the decimal separator is set to ".", it is working. When I change id to "," (like it is used in many countries) the point list is broken. So in some part of code (I do not have any idea where) numbers are parsed badly if decimal separator is set to "," ("Control Panel" -> "Change date, time, or number formats" -> "Additional Settings" -> "Decimal Separator"). If you need my code to reproduce the error let me know. If some languages settings can be passed into library, let me know.

**Comment by bartekzgo** [comment]
Hi,
more information. I'm analyzing XbimShapegeometry.ShapeData. This data are corrupted. The vertex list format is "x,y,z x,y,z". When Decimal Separator is set to ',' this data are written badly. I see "1,2,1,2,1,2 1,5,1,5,1,5" instead of "1.2,1.2,1.2 1.5,1.5,1.5". Please tell me where this structure is populated.

**Comment by bartekzgo** [comment]
I found the bug!
Xbim.ModelGeometry.Scene.XbimTessellator line 144
old: textWriter.Write(" {0},{1},{2}",p.X, p.Y, p.Z)
new: textWriter.Write(" {0},{1},{2}", p.X.ToString(System.Globalization.CultureInfo.InvariantCulture), p.Y.ToString(System.Globalization.CultureInfo.InvariantCulture), p.Z.ToString(System.Globalization.CultureInfo.InvariantCulture));

**Comment by bartekzgo** [comment]
Guys/Girls....
that was not the only place with this error. There are some other in c++ lib. I do not have a time to search all of them. I found workaround - I placed System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture; in loops Parallel.ForEach in Xbim3DModelContext. I'm sure about loops in WriteShapeGeometries and WriteFeatureElements. I've added also in WriteProductShapes. Please let me know when you solve all bugs.

**Comment by mwymwy** [comment]
Hi, 
I up this post, as I'm facing pretty similar problem when using Andy Ward's XbimDemo.
I made few changes to create .ply files for each ShapeGeometry found in my Ifc.

It happens that every vertex definition is separated by comas (expected) but decimal separator is also coma (aaaaarg ... )

my pc is configured in french culture.

Do anyone have a workaround other than modifying c++ libs ?

**Comment by mwymwy** [comment]
I just found a way : I added this line at the start of my geometry context generation process
System.Globalization.CultureInfo.DefaultThreadCurrentCulture = System.Globalization.CultureInfo.InvariantCulture;

It still looks like a patch though. 
bartekzgo correction seems more reliable for it doesn't impact culture outside of the geometry threads.
lib behaviour still shouldn't be culture-dependant.

**Comment by bartekzgo** [comment]
Hi,
this will not work. Be careful. Xbim is multithread. It creates new 
threads in different places, and each new thread will have default 
cultureinfo. I had this idea too. But in some cases it was not working. 
That is why I added this line in many places. For example in each 
|Parallel.ForEach

||Best regards,|
|Bartosz

|||
W dniu 16.09.2016 o 13:10, mwymwy pisze:

**Comment by mwymwy** [comment]
This works pretty weel.
It is because I use **CultureInfo.DefaultThreadCurrentCulture** and not **CurrentThread.CurrentCulture**. Mine defines the default culture to use for every thread created later by app. For example when creating geometry context.

unless your threads have a specific culture management (but that seems like a conception hole to me), it will work without needing to set CurrentCulture in every place where you parse or stringify numeric values.

**Comment by bartekzgo** [comment]
You are right! Thanks. I've seen that you are talking about 
defaultThread. I didn't found that!

W dniu 22.09.2016 o 15:37, mwymwy pisze:

**Comment by mwymwy** [comment]
I'm quite lazy when it comes to make changes in lot of places ... ;)

**Comment by SteveLockley** [comment]
I am closing this as it seems to be understood

**Comment by mwymwy** [comment]
Well it might be understood, it still seems like an issue to me as "ShapeGeometryMeshOf" and similar processes shouldn't be "platform/culture"-dependant, or should they ?

Though the solution bartekzgo and I found is an acceptable workaround for most of cases, but if in any case one should purposely use "CultureInfo.DefaultThreadCurrentCulture" another way it may cause problems.
