### ISSUE TITLE
Context.CreateContext() Crashing With IFC4 File

### ISSUE THREAD

**Issue by zohelfer** [xBimTeam/XbimGeometry#243]
When I try to open the attached file I get a System.Runtime.InteropServices.SEHException. My code works fine with other IFC files but this one is causing issues. Any help would be greatly appreciated.

#### Assemblies and versions affected:
XBim.Essentials - v5.1.274
XBim.Geometry - v5.1.288

#### Steps (or code) to reproduce the issue:

```
 using (var model = IfcStore.Open("testHouse.ifc"))
 {
                 var context = new Xbim3DModelContext(model);
                 context.CreateContext(); // breaks here System.Runtime.InteropServices.SEHException

}
```

#### Minimal file to reproduce the issue:
[testHouse.zip](https://github.com/xBimTeam/XbimGeometry/files/4105981/testHouse.zip)

**Comment by CBenghi** [comment]
I've not been able to reproduce this issue.
The file opens in Xplorer and Meshes with geometry for me.

Can you reproduce the issue perhaps testing it with the XbimRegression project in Geometry?
Try the develop branch code, it might be something that we have changed recently.

Thanks,
Claudio

**Comment by zohelfer** [comment]
Hey Claudio,

Thank you for getting back to me. Using the tools you described above I got the following results.

![repro1](https://user-images.githubusercontent.com/4202875/73210189-fa1c7680-4106-11ea-9575-781f1e7048fa.jpg)

![repo3](https://user-images.githubusercontent.com/4202875/73210207-03a5de80-4107-11ea-9547-ed9fdaa57187.jpg)

Xplorer for version for reference:
![repo2](https://user-images.githubusercontent.com/4202875/73210247-15878180-4107-11ea-911e-977948074bbc.jpg)

I am currently having issues building the Develop branch locally. Is there a estimated time when that might be released for download via NuGet?

Thank you,
Zacc

**Comment by zohelfer** [comment]
Any update on a fix for this being released?

**Comment by CBenghi** [comment]
Hi @zohelfer,
see under the "Compilation" header at http://docs.xbim.net/ to get internal versions of the precompiled binaries via nuget.
Best,
Claudio

**Comment by zohelfer** [comment]
Thank you so much Claudio. That resolved the issue.
