### ISSUE TITLE
Out of heap space at compiling XbimGeometry.engine

### ISSUE THREAD

**Issue by Noranius** [xBimTeam/XbimGeometry#244]
Building XbimGeometry.Engine on a work station with 64 GB RAM and only 6 GB used of them, leads to an out of heap exception.

#### Assemblies and versions affected:

Current Version of XbimGeometry.Engine from the master branch

#### Steps (or code) to reproduce the issue:

I've adjusted XbimEssentials in my own fork (https://github.com/Noranius/XbimEssentials). For this, I changed the version to an hypothetical Version 5.2 to distuingish to the old one. I created the package and uploaded it to a network directory.
I used this netweork directory as source within Nuget and updated the references in XbimGeometry to the new version 5.2. Finally, when I try to build XbimGeometry, the compiler throws the out of heap error at multiple files, i.e. FilletSurf_Builder.cxx.

#### Minimal file to reproduce the issue:
https://github.com/Noranius/XbimEssentials

#### Expected behavior:

successful build

#### Actual behavior or exception details:

Out of heap exception at multiple files, i.e. FilletSurf_Builder.cxx.

#### Additional Details

Workstation with 64 GB RAM, whereas 6 GB are used only.
This is related to #240. Where a build with original sources worked well. However, now i want to adjust them.

**Comment by andyward** [comment]
I can only think your Visual Studio install is not complete / up to date. We don't see this issue on our machines with much lower amounts of RAM, or the Azure build server with 8GB. Make sure you've got the correct C++ dependencies installed with Visual Studio:

- Visual C++ Core desktop features
- VC++ v141 tools
- Windows 10 SDK (10.0.17134.0)

I can't see anything obvious in your branch of Essentials or geometry that would cause any issues.

**Comment by Noranius** [comment]
Hi Andy,
yes Windows SDK is missing. 

Which build tools do you mean? See list below

- c++/CLI Support for v141 build tools
- MSVC v141 VS 2017 c++ arm64 build tools
- MSVC v141 VS 2017 c++ x64/x86 build tools
- c++ ATL for v141 build tools (ARM)
- c++ ATL for v141 build tools (ARM64)
- c++ ATL for v141 build tools (x86 & x64)
- c++ MFC for latest v141 build tools (ARM)
- c++ MFC for latest v141 build tools (ARM64)
- c++ MFC for latest v141 build tools (x86 & x64)

**Comment by andyward** [comment]
It's been a while since I've repaved this machine so I have some different SDK versions installed, but this is what I have installed with VS 2019 16.4.2:

![image](https://user-images.githubusercontent.com/923699/73290342-2fec5880-41f6-11ea-811c-fd64788edfc4.png)

I believe the important one is the highlighted **MSVC v141 VS 2017 c++ x64/x86 build tools**

**Comment by Noranius** [comment]
unfortunately, i didn't have success. After 3 hours I stopped the build process. I'll go on searching.

**Comment by andyward** [comment]
Yep looks like there could be an issue. We're having similar problems getting builds thought the CI server

Nothing significant has changed in source so I'm pointing the finger at a tooling update. Will investigate...

**Comment by Noranius** [comment]
Good news: Success

What I made: Currently 
1) I use VS 2019. Unfortunately 2019 has retarget the project. Hence, I had to change that to VS 2017 again. Right click on the project XbimGeometry.Engine and select "Retarget Project". Select the proper Windows SDK (10.0.17134.0) and for the platform toolset select "no upgrade". Click ok. 

2) Further, open the project properties and select General. Select Visual Studio 2017 (v141) for the platform toolset.

After that i was able to build it again. Can you verify that Andy?

**Comment by andyward** [comment]
Let me give that a go. Looks positive - because we're targeting the 'latest' SDK it looking like a newer version has come out that breaks us.

For info, I've ruled out an optimisation issue - ran with /Od and it still hung at the same place

**Comment by andyward** [comment]
Nope. Didn't fix it for me. Will write up my notes on the other ticket

**Comment by andyward** [comment]
Fixed with #240

**Comment by Belrius** [comment]
I found this to have some helpful tips in building the source - most specifically where to install the msvc 141 tools from.

However the last thing that I needed was to run VS in administrator mode.

Otherwise it can't sign the DLL's. Alternately you can give complete control to 

C:\Users\All Users\Application Data\Microsoft\Crypto\RSA\MachineKeys

to Everyone. Although that's probably not the best idea.
