### ISSUE TITLE
Not able to install Xbim.Geometry.Engine.Interop 5.1.288 dll from Nuget with .NET Framework 4.6.1

### ISSUE THREAD

**Issue by Nandhakumar2187** [xBimTeam/XbimGeometry#247]
Hi, 
Currently we are implementing the XBIM Viewer in our ASP.NET web application. The application contains the .NET Framework version 4.6.1.
We have installed Xbim dlls from "Manage Nuget Packages".
While adding the  "Xbim.Geometry.Engine.Interop.dll" (Version : 5.1.288) we have received the below error.
**"Could not install package 'Xbim.Geometry.Engine.Interop 5.1.288'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."**

Please help to resolve this issue.

![Xbim_Geometry_Framework_error](https://user-images.githubusercontent.com/49026188/74530462-2120d800-4f50-11ea-9bbb-7eb2e8c65010.png)

Thank you in advance.

**Comment by martin1cerny** [comment]
Can you target .NET 4.7 in your project?

**Comment by Nandhakumar2187** [comment]
Hi,
Currently our web application is working in .NET Framework 4.6.1.
Should I change the application framework version to 4.7.1 ?

**Comment by Nandhakumar2187** [comment]
Hi martin1cerny,
Shall I change the  application .NET framework version to 4.7.1 ?

**Comment by CBenghi** [comment]
Hello,
yes, if you can change the target version, that would fix your problem.
Best,
Claudio

**Comment by Nandhakumar2187** [comment]
Hi,
We have changed the .NET Framework Version as 4.7.1.
The issue resolved.
Thank you very much.
