### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [xBimTeam/XbimGeometry#256]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [BSB_T3Bits](https://github.com/xBimTeam/XbimGeometry/blob/0e2cbdca091218b70be1c6650bb8e34442a5f210/Xbim.Geometry.Engine/OCC/src/Bnd/Bnd_BoundSortBox.cxx#L192 "Destructor for BSB_T3Bits")
- [BRepAlgoAPI_BuilderAlgo::Clear](https://github.com/xBimTeam/XbimGeometry/blob/62d405825285aec9ec27191ed13f36f9d4db14bc/Xbim.Geometry.Engine/OCC/src/BRepAlgoAPI/BRepAlgoAPI_BuilderAlgo.cxx#L96 "BRepAlgoAPI_BuilderAlgo::Clear function")
- [NCollection_UtfStringTool::FromLocale](https://github.com/xBimTeam/XbimGeometry/blob/0e2cbdca091218b70be1c6650bb8e34442a5f210/Xbim.Geometry.Engine/OCC/src/NCollection/NCollection_UtfString.cxx#L36 "NCollection_UtfStringTool::FromLocale function")

**Comment by andyward** [comment]
This is actually 3rd party OCC code. Would need logging over here: https://tracker.dev.opencascade.org/view_all_bug_page.php

**Comment by elfring** [comment]
:crystal_ball: Can it become easier to identify and improve bundled software components?

**Comment by andyward** [comment]
I think it's only OCC that's bundled. i.e. everything under https://github.com/xBimTeam/XbimGeometry/tree/master/Xbim.Geometry.Engine/OCC
