### ISSUE TITLE
Required VC++ redistributable version

### ISSUE THREAD

**Issue by bexelconsulting** [xBimTeam/XbimGeometry#257]
Hello Xbim team,

I've noticed you moved on to VS2017 and VS2019.
Just wanted to check if VC++ 2013 is still the required redistributable at runtime?

Looking at the following line, it seems like it:
https://github.com/xBimTeam/XbimGeometry/blob/8c5db8c8ea02662bfac6639b6136d478471b62cf/Xbim.ModelGeometry.Scene/XbimEnvironment.cs#L66

Anyhow, it would be nice to disclose this information in the README.

Regards

**Comment by andyward** [comment]
I think that code is now unused. 

We should make the runtime requirements clearere though - you are right.
