### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by kozintsev** [xBimTeam/XbimGeometry#26]
Hello!

Where can I download NuGet package with XbimGeometry?
I did not find.
https://www.myget.org/F/xbim-develop/api/v2
https://www.myget.org/F/xbim-master/api/v2
Here...

Thank you!

**Comment by CBenghi** [comment]
Hi,
the urls that you list are package sources, they need to be added to the visual studio nuget repository list.
Please read the compilation section of https://github.com/xBimTeam/XbimEssentials.
I hope this helps,
Claudio

**Comment by kozintsev** [comment]
Thank you! I found the answer to your question.
