### ISSUE TITLE
Question:  method to Check if volume is Closed?

### ISSUE THREAD

**Issue by michaldengusiak** [xBimTeam/XbimGeometry#262]
*Short summary describing the issue. (3-5 sentences)*

Your library looks interesting. 
Do you have a method to check if bounding volumes made from Polygons 3D are Closed?

**Comment by bekraft** [comment]
The short answer is: Yes, but ...

 - it first depends on whether we are talking about geometrically closed figures:
Most of the checking method are part of the Open Cascade engine. XbimGeometry uses OC community (OCC) edition. Once the BREP building is done, a volume measure is available. If not, the shell has geometrical gaps. But this information isn't delegated to the meshed geometry in Xbim (except for some logging messages shown in the XbimXplorer)

 - if we are talking about the IFC information:
The IFC does not know about this problem in an analytical way. It only states that an object is closed (see IfcClosedShell) or open (see IfcOpenShell). Triangulation (see IfcTriangulatedFacetSet) holds only a "isClosed" flag. But actually, you can on rely on this information as an intention of the authoring platform. There's an ongoing discussion about tolerances (see #254)

**Comment by CBenghi** [comment]
@michaldengusiak,

further to @bekraft's excellent answer you can have a look at the GetSolids helper function that we have in WindowsUI https://github.com/xBimTeam/XbimWindowsUI/blob/3e2ecebd95bb9e0988b8cc46b1b131c16d0eda58/XbimXplorer/Commands/wdwCommands.xaml.cs#L1170

It uses reflection to show the resulting solids for all available geometryengine creation functions available for a type.
It's far-far-far from optimised, but it might give you a hint to the functions that could be useful for your purposes.

Best,
Claudio

**Comment by michaldengusiak** [comment]
ok thanks a lot,
