### ISSUE TITLE
.Net Standard

### ISSUE THREAD

**Issue by N30Pr1nc3** [xBimTeam/XbimGeometry#268]
hi im planing to create a Libary which uses Xbim to create ifc files. I Want to use .NetStandard 2.1 but i can not import xBim Geometry. Are there any plans to port this libary to .NetStandard?

**Comment by martin1cerny** [comment]
If you are going to create IFC files, you don't need XbimGeometry at all. You only need it if you want to use xbim for visual presentation.

**Comment by andyward** [comment]
Also see #248 which is tracking the .net standard 2 port
