### ISSUE TITLE
Creating Geometry with attached file causes geometry engine to get stuck in an infinite loop

### ISSUE THREAD

**Issue by zohelfer** [xBimTeam/XbimGeometry#270]
Opening the attached file in the most recent version of XbimWindowsUI's Xplorer will hang the program on the "Creating Geometry" step. Looking at the created threads, it appears that the geometry engine is stuck on an initialize geometry step. The engine will keep attempting to spawn threads until the user's processor is maxed out. My best guess is there is a circular dependency that is causing the engine's code to get stuck in a infinite loop.

#### Assemblies and versions affected:
XbimGeometry v5+

#### Steps (or code) to reproduce the issue:
Open attached file in newest Xplorer release.

#### Minimal file to reproduce the issue:
[CADSoft Example House.zip](https://github.com/xBimTeam/XbimGeometry/files/4973322/CADSoft.Example.House.zip)

#### Expected behavior:
File opens and 3D geometry is created

#### Actual behavior or exception details:
File gets stuck on the Creating Geometry Step

#### Additional Details
This file works in XBimGeometry v4 and Xplorer application that can be downloaded from the xBim website

**Comment by bekraft** [comment]
What version is your "most recent" Xplorer? Doing the same from the dev branches for XbimGeometry and XbimWindowsUI works fine for me. There's a dialog popup in "About". The tab "Assemblies" will show the assembly and file versions in use.

**Comment by zohelfer** [comment]
![image](https://user-images.githubusercontent.com/4202875/88962402-9fa1d580-d263-11ea-9614-acc91113e30a.png)

I pulled this on July 23rd from master. Is there a newer version on Develop?

Thank you so much,
Zacc

**Comment by bekraft** [comment]
There many changes done since last merge. I dont't know which changes effect the model (and whether it's really a problem of geometry engine). Maybe @SteveLockley knows more details. My recent develop branch build uses the head of 83158514c0edbe650c2c9d166c194481c2fbee80. And it works. See screenshot. 

![Issue270-Screenshot-develop](https://user-images.githubusercontent.com/10463824/89012392-72603080-d312-11ea-940d-e42af3f1d2a3.png)

**Comment by zohelfer** [comment]
Thank you so much for the help. Upgrading to the newest Develop fixed our issue as well.
