### ISSUE TITLE
How to extract geometric data such as number of walls, edges, faces and vertices from Revit files/BIM models? 

### ISSUE THREAD

**Issue by FrostbiteX11** [xBimTeam/XbimGeometry#276]

**Comment by martin1cerny** [comment]
I'm sorry, but this space is dedicated to [xbim toolkit](https://docs.xbim.net/), which you can use to analyse BIM models in IFC format. To learn about Revit API, you have to use Autodesk forums and resources. For example [Revit API documentation](https://www.revitapidocs.com/2019/).
