### ISSUE TITLE
Entity Faces and Edges

### ISSUE THREAD

**Issue by CBenghi** [xBimTeam/XbimGeometry#28]
_From @miosepayo on February 24, 2016 20:3_

Hi,

I plan to retrieve faces and edges (not triangulated) for physical entity (Wall, Beam etc ...). I guess this is releated to XBimShapeInstance but after searched the code for couple of day but don't get the best to way to achieve this. Any help ?

Is this related to MeshGeometry3DExtensions read method ? Case command for faces is empty ...

Thanks for your work on this project.

_Copied from original issue: xBimTeam/XbimWindowsUI#25_

**Comment by CBenghi** [comment]
_From @miosepayo on March 8, 2016 10:23_

Hello,

Any news/plans on this one ?

Best regards

**Comment by martin1cerny** [comment]
You can investigate [Xbim3DModelContext](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs) to see how xBIM handles geometry processing.

**Comment by SteveLockley** [comment]
If you look at the test cases in the geometry engine you will see how to get the BREP model for any shape in IFC, it is typically as simple as 

1) Create an instance of XbimGeometryEngine
2) Obtain an Ifc 3D geometry entity from the model
3) Call the appropriate geometry creator method for the 3D shape you have retrieved

In pseudo code
var geomEngine = new XbimGeometryEngine();
var extrudedSolid = model.Instances[123] as IIfcExtrudedAreaSolid;
IXbimSolid brepSolid = geomEngine.CrateSolid(extrudedSolid);

You will find IXbimSolid exposes all the properties you need for shell, face, edge, vertex exploration
