### ISSUE TITLE
failed to generate wexbim file

### ISSUE THREAD

**Issue by jFontoura** [xBimTeam/XbimGeometry#289]
problem started in the responses to the issue  #134 
*an error occurs in my program when I try to generate the wexbim file, the file can be opened in Xplorer*
*the compiler points the line "context.CreateContext ()"*

#### Assemblies and versions affected:

package id="Xbim.Common" version="5.1.297" targetFramework="net472"
package id="Xbim.Essentials" version="5.1.297" targetFramework="net472"
package id="Xbim.Geometry.Engine.Interop" version="5.1.328" targetFramework="net472"
package id="Xbim.Ifc" version="5.1.297" targetFramework="net472"
package id="Xbim.Ifc2x3" version="5.1.297" targetFramework="net472"
package id="Xbim.Ifc4" version="5.1.297" targetFramework="net472"
package id="Xbim.IO.Esent" version="5.1.297" targetFramework="net472"
package id="Xbim.IO.MemoryModel" version="5.1.297" targetFramework="net472"
package id="Xbim.ModelGeometry.Scene" version="5.1.328" targetFramework="net472"
package id="Xbim.Tessellator" version="5.1.297" targetFramework="net472"

#### Steps (or code) to reproduce the issue:

```csharp
            const string fileName = "C:\\Users\\const\\Documents\\projects\\construbim\\source.ifc";
            using (var model = IfcStore.Open(fileName))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var wexBimFilename = Path.ChangeExtension(fileName, "wexBIM");
                using (var wexBiMfile = File.Create(wexBimFilename))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }
            }
```

#### Minimal file to reproduce the issue:
*IFC file can only be shared via email*

#### Actual behavior or exception details:

*Xbim.Common.Exceptions.XbimException
HResult = 0x80131500
Message = Processing halted due to model error
Source = Xbim.ModelGeometry.Scene
StackTrace:
in Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries (XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType)
in Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext (ReportProgressDelegate progDelegate, Boolean adjustWcs)
in convertIfcToWexbim.Program.Main (String [] args) in C: \ Users \ const \ Documents \ code \ c # \ convertIfcToWexbim \ convertIfcToWexbim \ Program.cs: line 22

This exception was originally generated in this call stack:
[External Code]

Internal exception 1:
AggregateException: One or more errors.

Internal exception 2:
NullReferenceException: Object reference not defined for an instance of an object.*

**Comment by martin1cerny** [comment]
I confirm the exception is thrown the latest release of xbim but is OK with the latest develop version. A lot of work has recently gone into geometry processing. Can you temporarily use [pre-release MyGet packages please](https://docs.xbim.net/)?

```
<PackageReference Include="Xbim.Essentials" Version="5.1.310-develop" />
<PackageReference Include="Xbim.Geometry" Version="5.1.371-develop" />
```

**Comment by jFontoura** [comment]
worked, thank you. I suffered a little to be able to add the PackageReference, because the C # environment is not common for me.
