### ISSUE TITLE
Create IFC from sketchup (or convert IfcFacetedBrep to IfcExtrudedAreaSolid)

### ISSUE THREAD

**Issue by JohnO3535** [xBimTeam/XbimGeometry#290]
I apologize if this is not the right forum for this questions. (If not can someone point me in the right direction?)

I am trying to export from Sketchup to another program.  That program does not like the IfcFacetedBrep objects.  It prefers IfcExtrudedAreaSold/IfcArbitraryClosedProfileDef.

Is there a way to convert from one to the other.  Or is there a way to create the IFC directly from a sketchup file?  I am new to the geometry side of things so please bear with me.  But any help or links or examples would be greatly appreciated.  Thank you.

**Comment by CBenghi** [comment]
If I get your problem right you start from a SketchUp model, export that to IFC to be imported in another application that does not like IfcFacetedBreps that are produced by SU.

If this is the case it might be difficult for you to convert the geometries, depending on the SU exporter logic.

In principle not all IfcFacetedBreps can be expressed as extrudes (i.e. they might have irregular shapes that an extrude cannot express), and AFAIK there is no tool available to make that conversion for you.

However, 

1. if you are in control of the editing process, and/or 
2. if you know that all shapes in the model can be expressed as extrusions** 

then you could look into the files and see if it's possible to identify (amongst the faces) one that could be used as a seed for each extrusion.

In that case, you can then convert the files using the representation classes that you need.

This might not be trivial, but it's possible.

**Comment by JohnO3535** [comment]
I do have some control over the editing process.  In fact I need to create components for the various IFC elements (walls, beams, windows, doors, etc).  Are there examples I can refer to for creating extrusions?

**Comment by martin1cerny** [comment]
Here is an example: https://docs.xbim.net/examples/proper-wall-in-3d.html

**Comment by JohnO3535** [comment]
matic1cerny, thank you that (almost) works great.  What is the 2x3 equivalent of building.AddElement?

**Comment by martin1cerny** [comment]
Create an instance of [IfcRelConteinedInSpatialStructure](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcrelcontainedinspatialstructure.htm) and set the related and relating elements as you need.

**Comment by JohnO3535** [comment]
Again, that worked great.  What if I wanted to create IfcWall instead of IfcWallStandardCase?  Do you have any examples for that.  (I am not sure of the 3rd party application's support for IfcWallStandardCase.  But I know they support IfcWall.  And that is what they export.)

**Comment by martin1cerny** [comment]
```cs
var wall = model.Instances.New<IfcWall>();
```

**Comment by JohnO3535** [comment]
I will have to check to see what I am doing wrong.  When I replaced IfcWall with IfcWallStandardCase, BIM Vision crashed.  I'll give more info next week.  Thanks for your help.

**Comment by JohnO3535** [comment]
Is there any way to "debug" a file.  It looks good to me.  But it crashes BIM Vision.  Basically, I took a sketchup file (exported to IFC) and then my program examined the file and for each Wall that existed, I created a new wall using code from your example.  If I leave it there, it seems to work.  But I have 2 walls instead of 1.  When I try to remove the original wall from the storey reference, that is where I run into trouble. 

Is there a tool that, instead of crashing or throwing up an uninformative error, will say "Problem at line 47" or "Error with Element #47.  Illegal blah blah blah"?

**Comment by JohnO3535** [comment]
I have the following code to create an IfcWall element.  2 questions:
1.  Can you see anything wrong with the code.
2.  Is there an IFC file debugger to show what the problem is with a file?  When I try to load the resulting IFC file into BIM Vision, I get a popup to send BIM Vision more info.  I would like to know what is wrong with the file before sending more info.  Are there any programs out there that do that?

Here is my code:
		`
static private IfcWall CreateWall(IfcStore model, double length, double width, double height)
{
	// No need start a transaction.  This method is called from within a transaction
	//using (var txn = model.BeginTransaction("Create Wall"))
	{
		var wall = model.Instances.New<IfcWall>();
		wall.Name = "A Standard rectangular wall";
		// Make 4 points of the wall
		var point1 = model.Instances.New<IfcCartesianPoint>();
		point1.SetXY(0.0, 0.0);

		var point2 = model.Instances.New<IfcCartesianPoint>();
		point2.SetXY(0.0, 15000.0);

		var point3 = model.Instances.New<IfcCartesianPoint>();
		point3.SetXY(1040.0, 15000.0);

		var point4 = model.Instances.New<IfcCartesianPoint>();
		point1.SetXY(1040.0, 0.0);

		var point5 = model.Instances.New<IfcCartesianPoint>();
		point1.SetXY(0.0, 0.0);

		var polyline = model.Instances.New<IfcPolyline>();
		polyline.Points.Add(point1);
		polyline.Points.Add(point2);
		polyline.Points.Add(point3);
		polyline.Points.Add(point4);
		polyline.Points.Add(point5);

		var footprint = model.Instances.New<IfcArbitraryClosedProfileDef>();
		footprint.ProfileType = Xbim.Ifc2x3.ProfileResource.IfcProfileTypeEnum.AREA;
		footprint.OuterCurve = polyline;

		var direction = model.Instances.New<IfcDirection>();
		direction.SetXYZ(0.0, 0.0, 1.0);

		//model as a swept area solid
		var body = model.Instances.New<IfcExtrudedAreaSolid>();
		body.Depth = height;
		body.SweptArea = footprint;
		body.ExtrudedDirection = direction;

		//parameters to insert the geometry in the model
		var origin = model.Instances.New<IfcCartesianPoint>();
		origin.SetXYZ(0, 0, 0);
		body.Position = model.Instances.New<IfcAxis2Placement3D>();
		body.Position.Location = origin;

		//Create a Definition shape to hold the geometry
		var shape = model.Instances.New<IfcShapeRepresentation>();
		var modelContext = model.Instances.OfType<IfcGeometricRepresentationContext>().FirstOrDefault();
		shape.ContextOfItems = modelContext;
		shape.RepresentationType = "SweptSolid";
		shape.RepresentationIdentifier = "Body";
		shape.Items.Add(body);

		//Create a Product Definition and add the model geometry to the wall
		var rep = model.Instances.New<IfcProductDefinitionShape>();
		rep.Representations.Add(shape);
		wall.Representation = rep;

		//now place the wall into the model
		var lp = model.Instances.New<IfcLocalPlacement>();
		var ax3D = model.Instances.New<IfcAxis2Placement3D>();
		ax3D.Location = origin;
		ax3D.RefDirection = model.Instances.New<IfcDirection>();
		ax3D.RefDirection.SetXYZ(0, 1, 0);
		ax3D.Axis = model.Instances.New<IfcDirection>();
		ax3D.Axis.SetXYZ(0, 0, 1);
		lp.RelativePlacement = ax3D;
		wall.ObjectPlacement = lp;

		// Where Clause: The IfcWallStandard relies on the provision of an IfcMaterialLayerSetUsage 
		var ifcMaterialLayerSetUsage = model.Instances.New<IfcMaterialLayerSetUsage>();
		var ifcMaterialLayerSet = model.Instances.New<IfcMaterialLayerSet>();
		var ifcMaterialLayer = model.Instances.New<IfcMaterialLayer>();
		ifcMaterialLayer.LayerThickness = 10;
		ifcMaterialLayerSet.MaterialLayers.Add(ifcMaterialLayer);
		ifcMaterialLayerSetUsage.ForLayerSet = ifcMaterialLayerSet;
		ifcMaterialLayerSetUsage.LayerSetDirection = IfcLayerSetDirectionEnum.AXIS2;
		ifcMaterialLayerSetUsage.DirectionSense = IfcDirectionSenseEnum.NEGATIVE;
		ifcMaterialLayerSetUsage.OffsetFromReferenceLine = 150;

		// Add material to wall
		var material = model.Instances.New<IfcMaterial>();
		material.Name = "some material";
		var ifcRelAssociatesMaterial = model.Instances.New<IfcRelAssociatesMaterial>();
		ifcRelAssociatesMaterial.RelatingMaterial = material;
		ifcRelAssociatesMaterial.RelatedObjects.Add(wall);

		ifcRelAssociatesMaterial.RelatingMaterial = ifcMaterialLayerSetUsage;
		// IfcPresentationLayerAssignment is required for CAD presentation in IfcWall or IfcWallStandardCase
		var ifcPresentationLayerAssignment = model.Instances.New<IfcPresentationLayerAssignment>();
		ifcPresentationLayerAssignment.Name = "some ifcPresentationLayerAssignment";
		ifcPresentationLayerAssignment.AssignedItems.Add(shape);


		// linear segment as IfcPolyline with two points is required for IfcWall
		var ifcPolyline = model.Instances.New<IfcPolyline>();
		var startPoint = model.Instances.New<IfcCartesianPoint>();
		startPoint.SetXY(0, 0);
		var endPoint = model.Instances.New<IfcCartesianPoint>();
		endPoint.SetXY(4000, 0);
		ifcPolyline.Points.Add(startPoint);
		ifcPolyline.Points.Add(endPoint);

		var shape2D = model.Instances.New<IfcShapeRepresentation>();
		shape2D.ContextOfItems = modelContext;
		shape2D.RepresentationIdentifier = "Axis";
		shape2D.RepresentationType = "Curve2D";
		shape2D.Items.Add(ifcPolyline);
		rep.Representations.Add(shape2D);
		//txn.Commit();
		return wall;
	}
}
`

**Comment by martin1cerny** [comment]
You can open it in xbim [Xplorer](https://docs.xbim.net/downloads/xbimxplorer.html). When you open the debugging window, you will see any geometry issues which we couldn't deal with. This may be different to BIM Vision, but might give you a clue. There should not be any syntactic error in the file as we use early binding and code generation to cover this. To check schema constraints (also known as `WHERE` rules), you can use our [validator](https://github.com/KoncepceBIM/DSSTools/blob/master/LOIN/Validation/IfcValidator.cs#L25). Can you share your enhanced file?

**Comment by JohnO3535** [comment]
That's it!  Apparently it was a copy/paste error near the beginning of my code.  Instead of setting the xy values for point 4 and 5, I was creating point 4 and 5 and setting xy for point 1 twice.  I didnt notice it in the IFC file because the values for point 1 and 5 are the same.
Thank you so much for your patience and help!
