### ISSUE TITLE
Problem with Xbim3DModelContext.CreateContext().

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimGeometry#298]
Hello!
I have some problem with Xbim3DModelContext.CreateContext().
I see message, that there's no CreateShapeGeometry() method in
XBim.Geometry.Engine.Interop.XBimGeometryEngine in assembly
XBim.Geometry.Engine.Interop Version=5.1.0.0.

```csharp
using (var model = IfcStore.Open("C:\\Users\\Владислав\\Desktop\\CSoft\\Файлы IFC\\АР_модель 2х3.ifc"))
{
                var m_3DMdlContext = new Xbim3DModelContext(model);
                var conts = m_3DMdlContext.CreateContext();

                List<XbimShapeInstance> instances = m_3DMdlContext.ShapeInstances().ToList();
                List<XbimShapeGeometry> geometrys = m_3DMdlContext.ShapeGeometries().ToList();     
}
```     
I use xBbim.Geometry v.5.1.328. and can't install v.5.1.403 because of
"Unable to resolve dependencies. 'Xbim.ModelGeometry.Scene 5.1.328' is not compatible with 'Xbim.Geometry 5.1.403 constraint: Xbim.ModelGeometry.Scene (>= 5.1.403)
![Error](https://user-images.githubusercontent.com/77204365/104104788-467ea900-52bb-11eb-9c02-54f06637e65e.png)

**Comment by martin1cerny** [comment]
You need to sort out package dependencies first.

**Comment by GVladislavG** [comment]
But I added all assemblies needed by packages. And I still get error message
![Dependences](https://user-images.githubusercontent.com/77204365/104192658-2cb2a280-5430-11eb-90ae-6641d1f1cf49.png)

![Error](https://user-images.githubusercontent.com/77204365/104192784-5d92d780-5430-11eb-9d5f-1fc1faae4681.png)

**Comment by martin1cerny** [comment]
You should remove all the packages and just install `Xbim.Geometry` package. It will bring through all it's dependencies with right versions.
