### ISSUE TITLE
Joining walls with rectangular profiles

### ISSUE THREAD

**Issue by mahmouds12** [xBimTeam/XbimGeometry#30]
I created ifcWalls with ifcrectangleprofiledef... Now I want to join/trim the corners... Is there a simple way to do this?
Here's a screen shot for what it looks like
![image](https://cloud.githubusercontent.com/assets/15720804/20116376/afd7f0ea-a604-11e6-81b4-2e58127463d8.png)

**Comment by martin1cerny** [comment]
You simply can't use `IfcRectangleProfileDef` for this case. You will need to use other kind of profile like [IfcArbitraryClosedProfileDef](http://www.buildingsmart-tech.org/ifc/IFC4/final/html/link/ifcarbitraryclosedprofiledef.htm).

**Comment by CBenghi** [comment]
Another option would be to use a solid subtraction operation.
You could increase the size of the rectangles until the intersecting point and then subtract from each a custom solid with a vertical edge (maybe an halfspacesolid).

**Comment by martin1cerny** [comment]
@CBenghi is right but to create Boolean clipping you will need to get all the information anyway and it is better to avoid it if you can just define profile which will solve it. Boolean clipping is expensive operation in geometry processing where extruding appropriate profile is very easy and cheep.

**Comment by SteveLockley** [comment]
I am closing this as it is not an issue in xBIM, it can be resolved through appropriate construction of the Ifc Geometry using IfcArbitraryClosedProfileDef
