### ISSUE TITLE
Any known compile-time issue?

### ISSUE THREAD

**Issue by johnnyontheweb** [xBimTeam/XbimGeometry#316]
I used the code in XbimGeometry-5.1.288 release zip, and I'm trying to compile it. I tried several times with different toolsets under various versions of Visual Studio (2013 and 2019), but the code won't compile: compiler hangs during compilation of C++ project.

#### Assemblies and versions affected:

5.1.288 release

#### Steps (or code) to reproduce the issue:
devenv prints this and then hangs indefinitely:
```
1>Building Xbim.Geometry.Engine x32 and x64 Native Dlls
1>BOPDS_Iterator.cxx
1>BOPDS_SubIterator.cxx
1>BRepExtrema_DistShapeShape.cxx
```

**Comment by martin1cerny** [comment]
The build actually takes quite a long time initially. It might easily be 30+ minutes.

**Comment by johnnyontheweb** [comment]
Sorry, this is not the point, I waited for hrs ...

**Comment by andyward** [comment]
There were issues that a Visual Studio introduced a while ago but we fixed it: https://github.com/xBimTeam/XbimGeometry/issues/240

Any reason why you're building from 2 year old source rather than the latest master code? The latest master code is what is released in Nuget

**Comment by johnnyontheweb** [comment]
Thanks I read the previous thread, I'll give it a go.
I know I can have this from nuget - the best would be having all DLLs inside the nuget package, I cannot find them when uncompressing the manually-downloaded package (I just try to avoid to rely on internet connection every time I change pc).

**Comment by andyward** [comment]
To be clear, the Geometry engine native dlls and interop dll are in the Xbim.Geometry.Engine.Interop nuget package. 

You shouldn't need to build the package. And if you are building from source I would recommend building from the latest master source, cloned from this git repo. (github releases are tagged fairly infrequently - it's a bit ad hoc)

**Comment by johnnyontheweb** [comment]
thanks
