### ISSUE TITLE
How to generate more accurate solid of IfcBeam?

### ISSUE THREAD

**Issue by dawiddyrcz** [xBimTeam/XbimGeometry#318]
Your project Xbim is awesome, thank you for dooing this. 

I have a Question:

How can I generate more accurate solids with XbimGeometry? I mean for example H profiles with rounding. 

I am experimenting with volume measurements and I see that calculation with and without roundings are significantly different in steel structures (I am steel structures designer). The pipes and rectangular pipes are with roundings but H profiles have no roundings. The Ifc type of the element is IfcBeam, representation is by extrusion of IfcShapeProfile

I see that xbim xplorer generates the same geometry as my program - without H profile roundings. Is there any option for changing that? 

![image](https://user-images.githubusercontent.com/34553866/110161098-2e279800-7ded-11eb-82e1-26e98031fd91.png)

![image](https://user-images.githubusercontent.com/34553866/110161328-7e9ef580-7ded-11eb-8108-2f0c94ef9c17.png)

![image](https://user-images.githubusercontent.com/34553866/110161827-32a08080-7dee-11eb-97f3-8b89f50aab19.png)

![image](https://user-images.githubusercontent.com/34553866/110161751-18ff3900-7dee-11eb-9791-a52759989f99.png)

I am saving ifc model to WexBim format and later I am loading wexBim file. Here is my code for saving to wexBim Format:

```csharp
public void SaveToWexBim(string fileName, string wexBimFilename)
{
    System.Diagnostics.Debug.WriteLine("Saving ifc model to wexbim: " + new FileInfo(fileName).Name);
    var stopWatch = new System.Diagnostics.Stopwatch();
    stopWatch.Start();

    IfcStore.ModelProviderFactory.UseMemoryModelProvider();

    using (var model = IfcStore.Open(fileName))
    {
        var context = new Xbim.ModelGeometry.Scene.Xbim3DModelContext(model);
        context.CreateContext();   
        using (var wexBimFile = File.Create(wexBimFilename))
        {
            using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
            {
                model.SaveAsWexBim(wexBimBinaryWriter);
                wexBimBinaryWriter.Close();
            }
            wexBimFile.Close();
        }
    }

    stopWatch.Stop();
    System.Diagnostics.Debug.WriteLine($"Saved model to wexbim. Elapsed {(int)stopWatch.Elapsed.TotalMilliseconds} miliseconds");
}

```

I am using Nuget Package in version: Common 5.1.297, Engine 5.1.328 .net framework windows forms project, Windows 10

**Comment by jomijomi** [comment]
Have you tried changing the linear and angular deflection settings??

I think you can do that either through the app settings, i.e. :
ConfigurationManager::AppSettings["LinearDeflectionInMM"]
ConfigurationManager::AppSettings["AngularDeflectionInRadians"]

or by changing the ModelFactors before creating the 3DModelContext, i.e.:
model.ModelFactors.DeflectionAngle = ???;
model.ModelFactors.DeflectionTolerance = ???;
var context = new Xbim3DModelContext(model);

More info about what these settings actually do from OpenCascade docs:
[https://www.opencascade.com/doc/occt-7.1.0/overview/html/occt_user_guides__modeling_algos.html#occt_modalg_11_2](https://www.opencascade.com/doc/occt-7.1.0/overview/html/occt_user_guides__modeling_algos.html#occt_modalg_11_2)

I have those settings exposed in my own app, so if you can upload an example file (IFC) I could do a quick test with some different parameters and show you the result.

/Mikael

**Comment by jomijomi** [comment]
Minor update to my answer:
I just saw this comment in the XbimWire.cpp-code at a couple of places:
//TODO: SRL: Support for fillet radii needs to be added

So, that *might* mean that changing the deflection settings will not be the solution, after all...

Anyway, if you want, I can still check your file with different deflection settings in order to rule that out.

/Mikael

**Comment by jomijomi** [comment]
Second update...
Just checked with this file from the Open IFC Model Repository:
[Tekla_beams.zip](https://github.com/xBimTeam/XbimGeometry/files/6095385/Tekla_beams.zip)

Seems like we do get inner/outer fillet radius on the Rectangular Hollow Profile, but not on the I Profile. For what it's worth, Solibri doesn't do the fillet on the I Profile either.

Below are screenshots from xBIM, Solibri, and IFC Engine DLL (in that order)
![xBIM](https://user-images.githubusercontent.com/11835690/110208663-6fb55300-7e80-11eb-8507-e70ef804168d.png)
![Solibri](https://user-images.githubusercontent.com/11835690/110208668-75129d80-7e80-11eb-9ba2-38c794ac4b61.png)
![IFCEngineDLL](https://user-images.githubusercontent.com/11835690/110208672-78a62480-7e80-11eb-9366-4c5e8b5b898d.png)


/Mikael

**Comment by jomijomi** [comment]
Final update :)
Looking at the code in more detail it seems that if
ModelFactors.ProfileDefLevelOfDetail == 1
xBIM will *probably* try to add the fillet radius

Haven't tried this myself, though...
Still, I can fully understand why fillets are not added by default, as this will greatly increase the mesh complexity/density. I mean, Solibri also made that same decision...

/Mikael

**Comment by dawiddyrcz** [comment]
Thank you Mikael! You helped me a lot.
Now my steel shapes are more accurate and their volume is correct. 
I added:

```csharp
model.ModelFactors.ProfileDefLevelOfDetail = 1;
```
Now my code looks like this:

```csharp
public void SaveToWexBim(string fileName, string wexBimFilename)
{
    System.Diagnostics.Debug.WriteLine("Saving ifc model to wexbim: " + new FileInfo(fileName).Name);
    var stopWatch = new System.Diagnostics.Stopwatch();
    stopWatch.Start();

    IfcStore.ModelProviderFactory.UseMemoryModelProvider();
    
    using (var model = IfcStore.Open(fileName))
    {
        var context = new Xbim.ModelGeometry.Scene.Xbim3DModelContext(model);
        model.ModelFactors.ProfileDefLevelOfDetail = 1;
        context.CreateContext();   

        using (var wexBimFile = File.Create(wexBimFilename))
        {
            using (var wexBimBinaryWriter = new BinaryWriter(wexBimFile))
            {
                model.SaveAsWexBim(wexBimBinaryWriter);
                wexBimBinaryWriter.Close();
            }
            wexBimFile.Close();
        }
    }

    stopWatch.Stop();
    System.Diagnostics.Debug.WriteLine($"Saved model to wexbim. Elapsed {(int)stopWatch.Elapsed.TotalMilliseconds} miliseconds");
}
```

And my program shows roundings:

![image](https://user-images.githubusercontent.com/34553866/110217093-8f656f00-7eb2-11eb-8e4c-54fe80416472.png)

**Comment by martin1cerny** [comment]
Great to see you found the solution. Can we close this issue now?

**Comment by dawiddyrcz** [comment]
Yes, thank you
