### ISSUE TITLE
fedaration model show /hide problem

### ISSUE THREAD

**Issue by yinweib** [xBimTeam/XbimGeometry#341]
when model combined ,the intances selected can't be hide using "hide the selected object" xbim windowsUI,anyone knows Why?

**Comment by andyward** [comment]
Duplicate of https://github.com/xBimTeam/XbimGeometry/issues/341

**Comment by andyward** [comment]
Duplicate of https://github.com/xBimTeam/XbimWindowsUI/issues/169
