### ISSUE TITLE
[Question] Geometry Engine Circular Sweppt

### ISSUE THREAD

**Issue by oscarcardenas1** [xBimTeam/XbimGeometry#347]
[Question] Geometry Engine
Hi Xbim team.
I'm new to Xbim, and I have a question about how to obtain the geometric coordinates of triangulated circular Swept solids, like the blue solid in the photo. Or to know if I can get the coordinates of the triangulated circular extruded area solid because the geometry engine doesn't retrieve faces when I use the CreateSolid method.

![image](https://user-images.githubusercontent.com/82678665/121104538-e0de0c80-c7c7-11eb-8f27-5fb735bd1d54.png)

**Comment by CBenghi** [comment]
Hi @oscarcardenas1,
indeed this might not be trivial, the reason being that there are so many meshing formats out there that we've tried to keep it generic.

Once you get the returned object from 	`CreateSolid` you can pass it to the `void Mesh(IXbimMeshReceiver receiver, IXbimGeometryObject geometryObject, double precision, double deflection, double angle = 0.5);` function in the engine to get it triangulated.

You will have to implement the IXbimMeshReceiver interface, and receive the resulting mesh information there.

**Comment by oscarcardenas1** [comment]
Thanks for the answer. It was really useful.
