### ISSUE TITLE
Impossible de charger le fichier ou l'assembly 'Xbim.Geometry.Engine64'

### ISSUE THREAD

**Issue by oliviersaintgobain** [xBimTeam/XbimGeometry#35]
hello,
I have read the topic "Problem trying to run XbimGeometryEngine" and I saw that it wrks for him after installing c++ runtime.
I did it but I still have the issue...
I got the message : 
![image](https://cloud.githubusercontent.com/assets/22198623/21094486/8c9c287c-c057-11e6-834a-2ec06aba8816.png)

even if I have the visual c++ installed :
![image](https://cloud.githubusercontent.com/assets/22198623/21094534/aa469ef2-c057-11e6-83c4-d8c70bbf2735.png)

and the engine dll in reference (manually) :
![image](https://cloud.githubusercontent.com/assets/22198623/21094572/d35b6f20-c057-11e6-8c66-7421a0e09019.png)

if I don't add them manually in reference, I have the error message of missing visual c++....

thanks

olivier

**Comment by oliviersaintgobain** [comment]
when I remove the reference to engine32 and engine64, I got this message :
![image](https://cloud.githubusercontent.com/assets/22198623/21095003/ded9ca48-c059-11e6-8af3-fe42ce0e3682.png)

**Comment by theebow** [comment]
Hello Olivier
try to référence Xbim.Geometry.Engine.Interop.dll
and copy in your output directory : 
XbimGeometry/Output/Debug/**x64/Xbim.Geometry.Engine64.dll**
XbimGeometry/Output/Debug/**x86/Xbim.Geometry.Engine86.dll**

**Comment by theebow** [comment]
![capture](https://cloud.githubusercontent.com/assets/17316045/21095600/7ff31b1c-c05c-11e6-9c7b-1def329b41ff.PNG)

**Comment by oliviersaintgobain** [comment]
thanks.
dll is reference of the project :
![image](https://cloud.githubusercontent.com/assets/22198623/21096371/f7c44c80-c05f-11e6-8e56-b92b16bc4362.png)

I copied the librarie as expected :
![image](https://cloud.githubusercontent.com/assets/22198623/21096406/13a9097c-c060-11e6-8b3c-3745cd27175d.png)

but, I still have the same issue on c++ :
![image](https://cloud.githubusercontent.com/assets/22198623/21096436/30ef29a8-c060-11e6-9d26-f90bfa91bbf8.png)

**Comment by mwymwy** [comment]
Your exception is unrelated to your previous Xbim.Geometry.Engine.Interop.dll issue.
Referencing Interop and having x86/ and x64/ folders with proper natives dlls is good.

Your specific exception is thrown when initializing Geometry Engine because of following registry key was not found : 
@"SOFTWARE\Microsoft\DevDiv\VC\Servicing\12.0"

Check if this key exists in your computer registry.

If not , you can try followings :
- try to repair VS2013 C++ redist package installation
or
- add msvcp120.dll and msvcr120.dll in your assembly folder and create a config file specifying that Xbim.Geometry shouldn't try to check for VCRefist existence :

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<appSettings>
		<add key="SuppressVCRuntimeWarning" value="true"/>
	</appSettings>
</configuration>
```

To check how your exception occured, you can take a look at  XbimPrerequisitesValidator.cs, line 34.

It works pretty fine for me.

**Comment by mwymwy** [comment]
referencing Interop and having x86/ and x64/ folders with proper dlls insides is Ok. Keep it this way cause it is no more related to this InvalidOperationException.

This one was throw after a registry check for VS2013 C++ redist package, with following key :
"HKLM\SOFTWARE\Microsoft\DevDiv\VC\Servicing\12.0"

Check if this registry key can be found at said location, if not you may have the choice of : 
* Repairing MS VC++ 2013 redist package install
* copy msvcr120.dll and msvcp120.dll in your exe directory, and specify to geometry engine to not check for registry key by adding a param in a config file :

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
	<appSettings>
		<add key="SuppressVCRuntimeWarning" value="true"/>
	</appSettings>
</configuration>
```

your config file must be named accordingly to your main assembly name. Simplest is to use Visual Studio to create it it it doesn't already exists.

To view what exact piece of code is throwing your exception, you can take a look at XbimPrerequisitesValidator, line 34.

**Comment by oliviersaintgobain** [comment]
hello,
by removing the warning, it's "working".
thanks
