### ISSUE TITLE
Door openings not generated & inverted faces

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimGeometry#36]
Hello,

Recently I've come across this problem using the latest release of XbimWindowsUI. No door openings have been generated for this wall (and couple more inside the building).  Also, some face inversion is noticeable with some walls when viewed in non-xBIM viewers (as shown in screenshot). I guess you cannot  see such artifacts in Xbim Explorer because of cull settings.

Any ideas what can be done here? I'm ok to go into the code myself, but I don't even know where to start looking. :D

IFC sample file and screenshots are below.

[BIMhouse_ARK_info4.zip](https://github.com/xBimTeam/XbimGeometry/files/672782/BIMhouse_ARK_info4.zip)
[screenshot-solibrimodelviewer](https://cloud.githubusercontent.com/assets/5221157/21479713/e2c6108c-cb56-11e6-9d13-4bd4f891c709.png)
[screenshot-xbimexplorer](https://cloud.githubusercontent.com/assets/5221157/21479712/e2c5ef9e-cb56-11e6-8ef5-441414974354.png)
[screenshot-customviewer-twosidedoff](https://cloud.githubusercontent.com/assets/5221157/21479714/e2c64c14-cb56-11e6-9050-84a23990d153.png)
[screenshot-customviewer-twosidedon](https://cloud.githubusercontent.com/assets/5221157/21479715/e2c69e62-cb56-11e6-83c6-66038b8a5c04.png)

**Comment by CBenghi** [comment]
Hello,
I've tried with the current version and the geometry is properly computed.
I've had to change the schema version in the file to IFC2X3 (it's currently IFC2X_FINAL) for it to work in xbim.

![image](https://cloud.githubusercontent.com/assets/5476273/22590034/41fd6efc-ea05-11e6-8956-627b59dc1f4e.png)

I'm closing the issue, reopen id needed.

Best,
Claudio
