### ISSUE TITLE
IfcSchemaVersion in latest 5.1.403

### ISSUE THREAD

**Issue by LubomirBucek** [xBimTeam/XbimGeometry#372]
I am sorry to trouble you.

I started (in Visual Studio 2019) a new project from xBim toolkit examples: Proper Wall in 3D.
I used common VS Tools / NuGet Package manager / Manage NuGet Packages for Solutin... installation.
If I use Xbim.Essentials and Xbim.Geometry version 5.1.403 (latest in the list), 
IfcSchemaVersion "does not exist in the current context".

The error shows on two code lines:
model.SaveAs("HelloWallIfc4.ifc", IfcStorageType.Ifc);
var model = IfcStore.Create(credentials, IfcSchemaVersion.Ifc4, XbimStoreType.InMemoryModel);

But if I use older Xbim.Essentials 4.0.32 and Xbim.Geometry 4.0.19, this error does not exist and compilation went successfully.

Is there a way, how to resolve this trouble?
Thank you very much for an answer.
Kind regards.
Lubomir.

**Comment by martin1cerny** [comment]
There is a minor change in naming between these major versions. Just change `IfcSchemaVersion` to `XbimSchemaVersion`.
