### ISSUE TITLE
How to get IfcCartesianPoint from IfcSite

### ISSUE THREAD

**Issue by Kanhoto** [xBimTeam/XbimGeometry#386]
Hello,
I'm trying to get a cartesian point from an IfcSite

I have this in my Ifc :

_#25=IFCSITE('2yQclfLkD14hyFBxuhcYbP',#1,'HAUT','Terrain Naturel',$,#26,#29,$,.ELEMENT.,$,$,0.,$,$);
#26=IFCLOCALPLACEMENT($,#27);
#27=IFCAXIS2PLACEMENT3D(#28,$,$);
#28=IFCCARTESIANPOINT((1993500.,5195500.,950.));_

With what i have done I have : 

` Debug.Log(model.Instances.FirstOrDefault<IIfcSite>());` --> _#25=IFCSITE('2yQclfLkD14hyFBxuhcYbP',#1,'HAUT','Terrain Naturel',$,#26,#29,$,.ELEMENT.,$,$,0.,$,$);_

`Debug.Log(model.Instances.FirstOrDefault<IIfcSite>().ObjectPlacement);` --> _#26=IFCLOCALPLACEMENT($,#27);_

And I can't go farther than this, tried to do it reverse way by getting cartesianPoint and finding IfcSite but don't have much results as well.

Thanks.

**Comment by martin1cerny** [comment]
You need to get the site object:
```cs
var sites = model.Instances.OfType<IIfcSite>();
```
Then you need to browse the object structure of [IfcSite](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcsite.htm).

**Comment by Kanhoto** [comment]
Hum I don't understand what you mean since it is what I already do

**Comment by martin1cerny** [comment]
You just need to inspect the right types:

```cs
var site = model.Instances.FirstOrDefault<IIfcSite>();
if (site == null)
{
    // handle no site
    throw new NotSupportedException();
}

if (!(site.ObjectPlacement is IIfcLocalPlacement placement))
{
    // handle null or other type of placement
    throw new NotSupportedException();
} 

if (!(placement.RelativePlacement is IIfcAxis2Placement3D a2p))
{
    // handle other axis placement type
    throw new NotSupportedException();
}

var point = a2p.Location;

```

**Comment by Kanhoto** [comment]
Ty for you reply, but I found a way to get it (kind of dirty but it works)

![image](https://user-images.githubusercontent.com/85866455/174059942-bac04d47-861c-4995-a777-e645dbe6da99.png)
