### ISSUE TITLE
Converting IFC to WexBIM error: "An operation is not legal in the current state. (0x80131509)"

### ISSUE THREAD

**Issue by struckl** [xBimTeam/XbimGeometry#387]
Hello,
Im trying to convert an IFC File  to a WexBim File via an Azure Function. The IFC File is given in the request Body of the request "ConvertToWexbimAndSendToWebserver".
When calling the line "context.CreateContext()" i get the error seen below.

#### Assemblies and versions affected:
.Net Framework: .NET 6.0
Xbim.Geometry: 5.1.437
Xbim.IFC: 5.1.341
Xbim.ModelGeometry.Scene: 5.1.437

#### Steps (or code) to reproduce the issue:

```csharp

[FunctionName("ConvertToWexbimAndSendToWebserver")]
public static async Task<IActionResult> Run(HttpTrigger(AuthorizationLevel.Function, "post", Route = null)]
HttpRequest req, ILogger log)
{
   byte[] bodyBytes = new byte[req.Body.Length];
   req.Body.Read(bodyBytes);

   MemoryStream wexbimFile= ConvertFileToWexbim(new MemoryStream(bodyBytes));

   // Do stuff with the wexBimFile
}



public MemoryStream ConvertFileToWexbim(MemoryStream ifcFileContent)
{
    MemoryStream retStream = new MemoryStream();

    using (var model = IfcStore.Open(ifcFileContent, StorageType.Ifc, XbimSchemaVersion.Ifc4, XbimModelType.MemoryModel))
    {
        Xbim3DModelContext context = new Xbim3DModelContext(model);
        context.CreateContext(); // The Error is thrown here

        var wexBimBinaryWriter = new BinaryWriter(retStream);
        model.SaveAsWexBim(wexBimBinaryWriter);
    }

    return retStream;
}
```

#### Minimal file to reproduce the issue:
SampleHouse.ifc: [SampleHouse.zip](https://github.com/xBimTeam/XbimGeometry/files/8938265/SampleHouse.zip)

#### Expected behavior:

The ifc file (given as a MemoryStream) is converted to a wexBim File and saved to a new MemoryStream.

#### Actual behavior or exception details:
Executed 'ConvertToWexbimAndSendToWebserver' (Failed, Id=265e115f-f156-464b-bfb4-5780eba071c8, Duration=2074ms)
[2022-06-20T06:34:43.397Z] System.Private.CoreLib: Exception while executing function: ConvertToWexbimAndSendToWebserver. Xbim.Geometry.Engine.Interop: Failed to load Xbim.Geometry.Engine64.dll. System.Private.CoreLib: Could not load file or assembly 'Xbim.Geometry.Engine.dll, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509). System.Private.CoreLib: Resolved assembly's simple name should be the same as of the requested assembly.

![image](https://user-images.githubusercontent.com/30601936/174543764-9d3ae9ef-017d-4c63-8fa3-55fd42d550d6.png)

**Comment by martin1cerny** [comment]
Which version of Azure Functions do you use?

**Comment by struckl** [comment]
I am using the Version 4.0

**Comment by struckl** [comment]
That seems to have fixed my Problem
