### ISSUE TITLE
IFCBOOLEANCLIPPINGRESULT geometry processing failure

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimGeometry#39]
Hello all,

I've got an IFC sample file (downloaded from http://openifcmodel.cs.auckland.ac.nz) which won't load correctly inside Xbim environment. I've isolated the only element which won't show in a separate .ifc file. Upon closer inspection, it is a wall which is represented by  IFCBOOLEANCLIPPINGRESULT. Said wall is shown correctly inside Solibri, Simplebim and Navisworks.

![wall-solibri](https://cloud.githubusercontent.com/assets/5221157/23413188/439b833e-fdd8-11e6-9ce2-3ec31569f636.PNG)
![wall-xbim](https://cloud.githubusercontent.com/assets/5221157/23413187/4397375c-fdd8-11e6-9843-5af5a32cf257.PNG)

[20160125Autodesk_Hospital_Parking Garage_2015.zip](https://github.com/xBimTeam/XbimGeometry/files/807401/20160125Autodesk_Hospital_Parking.Garage_2015.zip)

[wall.zip](https://github.com/xBimTeam/XbimGeometry/files/807404/wall.zip)

**Comment by urosjovanovic** [comment]
This seems to be a non-issue on current develop branch, but latest Nuget package (4.0.11) has this bug.

**Comment by CBenghi** [comment]
Ok, I'll close this then.
Thanks,
Claudio
