### ISSUE TITLE
Does xbim-engine support the gpu parallel version of opencascade (based on openCL)

### ISSUE THREAD

**Issue by chh320** [xBimTeam/XbimGeometry#392]
Hello！I am learning the model processing part of xbim recently, and would like to ask whether the current geometry engine uses the GPU parallel version of opencascade

**Comment by andyward** [comment]
Which version of open cascade are you talking about? Not sure I'm aware of anything that's not an experimental OCC version supporting any GPU operations

**Comment by chh320** [comment]
Sorry! I made a mistake. I saw in the early papers of OCC that OCC tried GPU parallel technology based on OpenCL, but later found in the OCCT forum that OCCT did not use this technology for portability and high performance. 
Again, I'm sorry for the trouble.

**Comment by andyward** [comment]
No worries. If the situation changes we'll revisit.
