### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by Ahmed-bendary** [xBimTeam/XbimGeometry#393]
Hello, 

i just have a question not an issue with function called readShapeTringulation(), i am using this function now and it produces accurate results in my opinion however i don't understand exactly how it works, how it formulates the tringulation for different geometrical shapes, it would be really apperciated if i can get small clarification about the concept behind this function.

best regards,
Ahmed

**Comment by martin1cerny** [comment]
You can use this function to read the triangulation of the shape after it has been processed. See this [sample code](https://docs.xbim.net/examples/creating-wexbim-file.html) where all the geometry is processed and then converted to our wexBIM format for web presentation. Wexbim serialiser uses `ReadShapeTriangulation()` and other related methods internally.
