### ISSUE TITLE
Some IfcProducts are duplicated in result IFC-file

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimGeometry#397]
Hi, xBim team!

I got such problem lately.
Resulting IFC-file has some elements twice. BimVision shows this message.
But, if I get elements from model
`var myList = model.Instances.OfType<IIfcBuildingElementProxy>().ToList();`
there are no duplicating elements in myList.
If I search duplicating elements in IFC-file manualy, thre are also no duplicating elements.
What's the problem and how can I fix it?
IFC-file is in attached archive.
[test.zip](https://github.com/xBimTeam/XbimGeometry/files/9674299/test.zip)

Thank you!

**Comment by andyward** [comment]
What's the error message you see in BIM Vision? What is the exact problem you're seeing? Is this a Geometry issue?

It's very hard to advise without a clearly defined problem.

**Comment by GVladislavG** [comment]
I see this message in BIM Vision.
![Ошибка](https://user-images.githubusercontent.com/77204365/193409889-4045db1b-752f-4c1b-81bf-55d5cb11cc1b.png)
In English:
"The object is located in the file twice.
#5017.Building Element Proxy. Оконный блок 12.12
The project may not be displayed correctly"
 I'm not really sure that it's Geometry problem.

You can replicate the problem by openning attached IFC
in BimVision

**Comment by andyward** [comment]
xbim Toolkit has a built in validator of its own that can help you here:

See https://github.com/xBimTeam/XbimEssentials/blob/master/Tests/ValidationTests.cs

... here it is in action in XbimXplorer

![image](https://user-images.githubusercontent.com/923699/193547018-c6427096-f724-4681-ac87-33b1768c50fc.png)

There are various issues with the Spatial breakdown in that model. I suspect the issue BimVision is highlighting is that element 5017 (and others) are defined as being **both** part of the Site and a BuildingStorey. It should be one or the other. 

Separately ensure the IfcBuildingStorey  is related to the IfcBuilding

**Comment by martin1cerny** [comment]
Can we close this issue @GVladislavG?

**Comment by GVladislavG** [comment]
Yes, thanks!
