### ISSUE TITLE
Moving all geometry element during federation ?

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimGeometry#40]
Hi team
We have problem in the federation loading file step
Ifc file are not correctly in the same place 
but they are in Revit : 
![xbimissue](https://cloud.githubusercontent.com/assets/17316045/23577412/ccacc942-00be-11e7-9522-cb84902785f4.PNG)

As you can see, some entities (IfcSpace, ifcDistributionElement...) are outside the building
![xbimissue2](https://cloud.githubusercontent.com/assets/17316045/23577503/07ea57e8-00c1-11e7-820a-1d9ba5bd2cf6.PNG)

we think problem due to Revit

we tryied to modify directly the ifc file with notePad++ 😄 without succes

the only way we think good could be to move the entire geometry during createContext

Do you have any idea to do it easily ?

Regards

[ifcFile.zip](https://github.com/xBimTeam/XbimGeometry/files/818494/ifcFile.zip)

**Comment by SteveLockley** [comment]
The file you have uploaded is not a valid zip file, if you have not resolved this could you please upload a newer version. This might be an issue with the Revit exporter, some versions did displace models if the shared coordinate systems are not setup correctly.
There is also an issue relating to Xbim and Federation of models which may be related.
I am closing this issue until we have further information
