### ISSUE TITLE
Processing halted due to model error

### ISSUE THREAD

**Issue by KageAkuma75** [xBimTeam/XbimGeometry#403]
Hello support team,

Using Xbim geometric operations throw "Processing halted due to model error" when creating context.

Assemblies and versions affected:
Xbim.Essentials Version=5.1.289
Xbim.Geometry Version=5.1.317

I've joinded an IFC containing the corrupted gemeotry

[sample.zip](https://github.com/xBimTeam/XbimGeometry/files/9849643/sample.zip)

Did i miss something ?
Best regards

**Comment by lyague** [comment]
Dear support I figure the same issue, do you have some inputs ?
Thx!

**Comment by martin1cerny** [comment]
The geometry of the space is defined in the geometry context which is **not related to the project**

![image](https://user-images.githubusercontent.com/773078/208898137-ddeedd2d-d59d-4190-a3bb-fc29b88970d5.png)

That means that the processing software cannot make sure the right units and other contextual information is applied.

**Comment by martin1cerny** [comment]
You can apply some custom logic to fix the file as part of pre-processing based on the originating system etc. But if you can, you should definitely provide a feedback to authors of the SW.
