### ISSUE TITLE
IfcCircularArcSegment2D can be instantiated in IFC 4x1, but not IFC 4?

### ISSUE THREAD

**Issue by WindingWinter** [xBimTeam/XbimGeometry#405]
It turns out that IfcCircularArcSegment2D can be instantiated in IFC 4x1, but not IFC 4. 

Any reason for this?

**Comment by andyward** [comment]
Yes, it was only introduced in IFC4x1. See https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/link/ifccirculararcsegment2d.htm

I believe it was part of the IFC4x1 standard, which has now been [withdrawn](https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/).  i.e. be aware this entity has been removed in the latest IFC4.3 schema so I'd avoid using it -  a lot of the alignment schema got overhauled in 4.3
