### ISSUE TITLE
Generating Solid objects for IFC product layers

### ISSUE THREAD

**Issue by ido-cu** [xBimTeam/XbimGeometry#409]
I have a model with elements that are composed of several layers.
I'd like to generate a solid object for each one of those layers (as if they were separate elements).
I access the Material property on the _IfcProduct_ and try to get the representation like this:

```cs
const string STYLE_REPRESENTATION_ID = "Style";

IIfcMaterialLayerSetUsage layerSet = element.Material as IIfcMaterialLayerSetUsage;

foreach (IIfcMaterialLayer currentlayer in layerSet.ForLayerSet.MaterialLayers)

{

    foreach (IIfcMaterialDefinitionRepresentation currentLayerRep in currentlayer.Material.HasRepresentation)

    {

        IIfcRepresentation elementRep = currentLayerRep.Representations?
			.FirstOrDefault(rep => rep.RepresentationIdentifier == STYLE_REPRESENTATION_ID);
...
```

But I get a _IfcStyledRepresentation_ object which does not implement _IIfcGeometricRepresentationItem_
so I can't create a solid using _XbimGeometryEngine.Create_.

What am I doing wrong?
Is it even possible with xbim? and if so, how can I do it?

Thanks!

**Comment by martin1cerny** [comment]
`IIfcMaterialDefinitionRepresentation` is about visual representation of the material itself, not about the material layer itself as you can read in [the documentation](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifcmaterialdefinitionrepresentation.htm). Walls geometry is usually defined as extruded area, where you can calculate individual layers of the wall only as an inferred shape based in the geometry of the wall and its layer composition and orientation. What do you need this for? Do you actually need the shape, or do you need to get calculated properties such as volume and area?

**Comment by ido-cu** [comment]
I can manage without the volume and area...
Are you saying that I need to get the solid of the wall, and then figure out how to split it according to the LayerThickness property of each layer?

**Comment by ido-cu** [comment]
Oh wait... did you mean that I can build my own IfcExtrudedAreaSolid with defined with of the layer and build a solid object from this? :)

**Comment by martin1cerny** [comment]
Yes, you can do that. You can take the profile and manipulate it on the fly to get a solid per layer. You are welcome to contribute the code. Others might find it useful as well.

**Comment by ido-cu** [comment]
ok, thanks!
(I'm currently just researching it, I'll be happy to contribute when it's ready)
