### ISSUE TITLE
An implementation of IXbimGeometryServicesFactory could not be found

### ISSUE THREAD

**Issue by neovinhtru** [xBimTeam/XbimGeometry#424]
Hi
I am working on Converting IFC to a webxBim file on .Net Core 6 with feature/netcore branch.
but I create Xbim3DModelContext(model) I am facing the exception "An implementation of IXbimGeometryServicesFactory could not be found\n\nEnsure you have registered the GeometryEngine with services.AddXbimGeometryEngine()".
![image](https://user-images.githubusercontent.com/5475753/237023164-4c31471f-4fa0-49c8-ad61-6bcde8a3da4d.png)
Thank you in advance!

**Comment by martin1cerny** [comment]
Have you tried to do what the message suggests?

**Comment by neovinhtru** [comment]
@martin1cerny . Yes, I have. I added with code 

![image](https://github.com/xBimTeam/XbimGeometry/assets/5475753/1cfba6ab-e031-4524-9130-5634bd40dd8c)
 
But isBuilt variable always is true. 

![image](https://github.com/xBimTeam/XbimGeometry/assets/5475753/95190b4b-4683-4cce-9566-823eabc45e67)
Do you have any suggestions? 

Thanks!

**Comment by andyward** [comment]
You need to call the DI code at application boot up. Try putting that line in your App.cs or an equivalent Startup

**Comment by namnguyen0705** [comment]
Thank you! @andyward. I tested and it is working as well.
