### ISSUE TITLE
Xbim.Geometry is not support the net core?

### ISSUE THREAD

**Issue by 6ther** [xBimTeam/XbimGeometry#435]
*Short summary describing the issue. (3-5 sentences)*

#### Assemblies and versions affected:

*Which assemblies/packages and their versions are known to be affected. E.g. __Xbim.Essentials 5.0.200__

#### Steps (or code) to reproduce the issue:

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

```csharp
using (var model = IfcStore.Open("file.ifc"))
{
    ...
}
```

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

#### Expected behavior:

*What would you expect to happen*

#### Actual behavior or exception details:

*What actually is happening*

#### Additional Details

*Optional, details of the root cause if known. 
Delete this section if you have no additional details to add.*

**Comment by 6ther** [comment]
I want to use the xbim.Geometry in netcore project, but it does not works.

**Comment by andyward** [comment]
Covered in #390 
Check out: the netcore branch at https://github.com/xBimTeam/XbimGeometry/tree/feature/netcore
