### ISSUE TITLE
Failed to Compile feature/netcore branch

### ISSUE THREAD

**Issue by 6ther** [xBimTeam/XbimGeometry#437]
*Short summary describing the issue. (3-5 sentences)*

#### Assemblies and versions affected:

*Which assemblies/packages and their versions are known to be affected. E.g. __Xbim.Essentials 5.0.200__

#### Steps (or code) to reproduce the issue:

*A simple set of steps to reproduce the issue. Provide a small sample file is required and/or 
a small sample of the failing code (or reference a commit / gist)*

```csharp
using (var model = IfcStore.Open("file.ifc"))
{
    ...
}
```

#### Minimal file to reproduce the issue:
*IFC files need to be zipped to be uploaded. Then just drag & drop here*

#### Expected behavior:

*What would you expect to happen*

#### Actual behavior or exception details:

*What actually is happening*

#### Additional Details

*Optional, details of the root cause if known. 
Delete this section if you have no additional details to add.*

**Comment by 6ther** [comment]
i clone the feature/netcore branch locally and try to compilate it, but it fail beacuse can not find the Xbim.Geomtry.Occt package.
![1692244437226](https://github.com/xBimTeam/XbimGeometry/assets/46700515/d3709cbc-5305-45fc-a23d-1b9a85c574dc)

**Comment by 6ther** [comment]
![1692244568339](https://github.com/xBimTeam/XbimGeometry/assets/46700515/afa5e35d-3d62-48f8-886d-64102e2a0a8a)

**Comment by 6ther** [comment]
can not find the Xbim.Essentials(>=6.0.414-develop) package either

**Comment by andyward** [comment]
The packages are definitely in Myget:

https://www.myget.org/feed/xbim-develop/package/nuget/Xbim.Geometry.Occt
https://www.myget.org/feed/xbim-develop/package/nuget/Xbim.Essentials/6.0.414-develop

<img width="1314" alt="image" src="https://github.com/xBimTeam/XbimGeometry/assets/923699/6d48bb9c-0374-4ecb-a73b-da4a3c399ac7">

You should not need to add a manual nuget source as the solution contains a nuget.config

**Comment by andyward** [comment]
Did you resolve this?

**Comment by andyward** [comment]
Ok, so environmental. Will close as there's not much we can do here.  I'd imagine some kind of Nuget cache may help
