### ISSUE TITLE
Error in ShapeGeometryMeshOf() method

### ISSUE THREAD

**Issue by ani-rudh** [xBimTeam/XbimGeometry#44]
Hello,
@martin1cerny @SteveLockley 
I am trying to extract triangulated meshes of all geometries in an IFC file using this code
I have already loaded the model with ifcstore.open...

`var context = new Xbim3DModelContext(model);
                context.CreateContext();

                //var geometries = context.ShapeGeometries();
                //XbimShapeTriangulation mesh = null;
                var geometries = context.ShapeInstances();

                foreach (var g in geometries)
                {
                    //var ms = new MemoryStream(((IXbimShapeGeometryData)g).ShapeData);
                    //var br = new BinaryReader(ms);
                    //mesh = br.ReadShapeTriangulation();
                    ////mesh = mesh.Transform(((XbimShapeInstance)g).Transformation);

                    //Console.WriteLine(g.Format + " | " + g.ShapeLabel);
                    //Console.WriteLine(mesh.Faces.Count() + " | " + mesh.Vertices.Count());

                    var tri = context.ShapeGeometryMeshOf(g);
                    Console.WriteLine(tri.TriangleIndexCount + " | " + tri.ToString());
                   
                }
`
If I'm using the commented part of the above code, the mesh returns without being triangulated. The format is PolyHedronBinary.

If I use the context.ShapeGeometryMeshOf() method, there is an exception thrown : invalid geometry type .

![image](https://cloud.githubusercontent.com/assets/15331399/23925625/66935fc2-0910-11e7-9395-c004a7432295.png)

Please help me with triangulating the geometries of the model.

I have also read about the method "read" in  XbimWindowsUI/Xbim.Presentation/MeshGeometry3DExtensions.cs, but I am not able to figure out what I have to pass as the "m3d" parameter ?

`/// <summary>
        /// Reads a triangulated model from an array of bytes and adds the mesh to the current state
        ///  </summary>
        /// <param name="m3D"></param>
        /// <param name="mesh">byte array of XbimGeometryType.PolyhedronBinary  Data</param>
        /// <param name="transform">Transforms the mesh to the new position if not null</param>
        public static void Read(this MeshGeometry3D m3D, byte[] mesh, XbimMatrix3D? transform = null)`

It will be great if anybody could provide/ point me to example usage of this method.

I need to rebuild the IFC model in Unity and hence I need the triangulated mesh data.

Also suggest if there is anyway to achieve this more efficiently and/or in a simpler way!

Many Thanks in advance,
Ani

**Comment by martin1cerny** [comment]
Have a look at source code for `IfcStore.SaveAsWexBim()` function. That uses triangulated geometry to create data for a web presentation.

**Comment by jv112602** [comment]
I had the same issue and used some code I posted in [https://github.com/xBimTeam/XbimGeometry/issues/34](url)
if you need more just let me know but I was able to get all the vertices and faces with that technique

Jay

**Comment by martin1cerny** [comment]
If you tried little bit more you would find that every of these faces has triangles as normals and indices inside.

```cs
var triangleCount = mesh.Faces.Aggregate(face => face.TriangleCount);
```

**Comment by ani-rudh** [comment]
Oh yes. Thank you so much :). Found it now.

**Comment by jv112602** [comment]
I tried your same cube example and got the following:
- 6 faces which are all the sides of the cube
- inside each cube side (face) you have 2 triangles
- then there are 6 indices inside each cube face representing the 6 indices for the sides of the 2 triangles
- I think you can group the indices into 3's and you have your triangle indices ?
triangle 1 has indices[0, indices[1], indices[2]
triangle 2 has indices[3, indices[4], indices[5]

make sense ?

jay

**Comment by ani-rudh** [comment]
Yes Jay,

I was quiet dumb not try one step further!

Thanks, it works.

On Mar 17, 2017 19:25, "jay vose" <notifications@github.com> wrote:

I tried your same cube example and got the following:

   - 6 faces which are all the sides of the cube
   - inside each cube side (face) you have 2 triangles
   - then there are 6 indices inside each cube face representing the 6
   indices for the sides of the 2 triangles
   - I think you can group the indices into 3's and you have your triangle
   indices ?
   triangle 1 has indices[0, indices[1], indices[2]
   triangle 2 has indices[3, indices[4], indices[5]

make sense ?

jay

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/xBimTeam/XbimGeometry/issues/44#issuecomment-287434554>,
or mute the thread
