### ISSUE TITLE
Exporting IFC from Existing model

### ISSUE THREAD

**Issue by Abdallah-BIM** [xBimTeam/XbimGeometry#441]
*Short summary describing the issue. (3-5 sentences)*

I am trying to export the IFC data after the creation of a comparison software and I want to include the changes between the two models in a new model and then this model should be saved as IFC file.

is there a way in the XBim libraries to do so?

#### Expected behavior:

*What would you expect to happen*
![TC1ChangeType](https://github.com/xBimTeam/XbimGeometry/assets/78498811/b6bd9861-c208-4851-b859-e9821bd1c91c)
I will add an export IFC button here to have this data as attributes for each element that has the changes 
#### Additional Details

*Optional, details of the root cause if known. 
Delete this section if you have no additional details to add.*

**Comment by andyward** [comment]
I think this is more of a question whether IFC supports this kind of concept. The closest concept I can think of is to adopt [IfcOwnerHistory](https://standards.buildingsmart.org/IFC/DEV/IFC4_2/FINAL/HTML/link/ifcownerhistory.htm) and make use the ChangeAction attribute to indicate Added/Deleted/Modified etc.
