### ISSUE TITLE
How to get color of IfcSpace?

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimGeometry#460]
Hello, xBim team!

How to How to get color of IfcSpace?
It doesn't have any material and StyleLabel of it's
ShapeInstance is 0.

Thank you.

**Comment by martin1cerny** [comment]
What do you mean by *"ShapeInstance is 0"* ? Bear in mind the space might not have any colour at all.

**Comment by GVladislavG** [comment]
I mean `ShapeInstance .StyleLabel = 0` where ShapeInstance is XbimShapeInstance for IfcSpace object.
