### ISSUE TITLE
Load Ifc File System.AccessViolationException

### ISSUE THREAD

**Issue by hakanornek** [xBimTeam/XbimGeometry#467]
Hi Xbim Team,

I am getting a System.AccessViolationException error when loading the Ifc file attached below. It seems to be related to :
Xbim.Geometry.Engine64.dll (Xbim.Geometry.Xbimsolid.init).

I did not encounter any errors when opening the same IFC file in Solibri, BimVision, and DDSCad.
I wonder what could be causing the problem. I would be very grateful if you could help. Thank you in advance.

#### Assemblies and versions affected:

My Development Environment:
VS framework 4.7 and winform
Xbim.Geometry version: 5.1.437

#### Steps (or code) to reproduce the issue:
 ```
      '------------------------------------------------------------------------
   oModel = IfcStore.Open(ifcFilename, Nothing, -1, AddressOf worker.ReportProgress, FileAccessMode)
   '------------------------------------------------------------------------
   If oModel.GeometryStore.IsEmpty Then
       Dim context As Xbim3DModelContext = New Xbim3DModelContext(oModel)
       context.CreateContext(progDelegate:=AddressOf worker.ReportProgress)   <----- Error (System.AccessViolationException)
   End If
   '------------------------------------------------------------------------
```

#### Minimal file to reproduce the issue:

[Sample_House_V4.zip](https://github.com/xBimTeam/XbimGeometry/files/14449720/Sample_House_V4.zip)

**Comment by andyward** [comment]
Hi Hakan

This is usually down to a edge case bug between xbim GE and the native OpenCascade library.

Have you tried using the latest 5.1 Geometry build from the develop branch - looks fine in 5.1.742. You'll need to set up Myget as a repository. See https://www.myget.org/feed/xbim-develop/package/nuget/Xbim.Geometry for latest

<img width="782" alt="image" src="https://github.com/xBimTeam/XbimGeometry/assets/923699/762eabb3-4d6e-441b-9803-b1b80f8dcbf1">

**Comment by hakanornek** [comment]
Hi Andy,

Thanks for the quick response. I've updated Xbim.Geometry and all dependent libraries from the 'https://www.myget.org/F/xbim-develop/api/v3/index.json' repository to their latest versions.
![NuGetPack](https://github.com/xBimTeam/XbimGeometry/assets/10813855/66d38e0e-402c-4cb7-9e55-6b5220ad5e40)


However, I couldn't find the Xbim.ifc2x3.Interfaces namespace in the Xbim.ifc2x3 library, which was available in previous versions. Therefore, entities belonging to the ifc2x3 library such as IIfcUnit, IIfcWall, etc., could not be found. I also couldn't find any information regarding this issue in the Breaking Changes section related to Xbim.ifc2x3.

Even if I disregard the use of the Xbim.ifc2x3 library, I still receive the error <No service for type 'Xbim.IO.IModelProvider' has been registered> for ifc4 files. Consequently, I had to revert back to the last stable version available on NuGet, which is 5.1.341.

![error](https://github.com/xBimTeam/XbimGeometry/assets/10813855/b42b5b5f-4d72-48e2-bc46-577dbde1b83b)

The AccessViolation error is likely suppressing the real error. Therefore, I will try to identify the problematic #item by reading the logs, following the information I found at https://docs.xbim.net/examples/watch-the-log.html. 

I need help with another issue. I want to make selected entities transparent and move them in Xbim.
I found the following example for transparency, but it makes the entire model transparent.
```
           DrawingControl.Dispatcher.Invoke(Function()
                                                 DrawingControl.ModelOpacity = 0.1
                                                 System.Threading.Thread.Sleep(100)
                                             End Function)
```
As far as I understand, we need to perform these operations not with Xbim libraries but with Helix. How can I find an instance of a shape belonging to any entity such as IfcWall, IfcColumn in Helix?"

Thank you very much for your helps.

**Comment by andyward** [comment]
Looks like you're using v6 not the latest vesion of v5.1, which is why you're seeing these issues. There are some breaking changes in v6, including:

1. Removing the IFC2x3 interfaces as they were more hinderance than help. The IFC4 interfaces are backward compatible to 2x3.
2. Dependency injection has been introduced which changes how IModelProviders are registered - see https://github.com/xBimTeam/XbimGeometry/tree/feature/netcore?tab=readme-ov-file#getting-started

If you just want to test in XbimXplorer with v6 GE checck out this branch: https://github.com/andyward/XbimWindowsUI/tree/feature/ifc4x3 in my repo.

Alternatively pick up the latest 5.1 xbim Essentials and Geometry from Myget.

Can you pick up the Transparency issue in a new Issue in WindowsUI please?

**Comment by hakanornek** [comment]
I tested it with v6 GE in XbimXplorer, mymodel works. 
I will move the transparency issue to WindowsUI. 
Thanks for everything ...
