### ISSUE TITLE
We need to get  plot line bounding box distance for all levels.

### ISSUE THREAD

**Issue by ashvinisawantsofttechengr** [xBimTeam/XbimGeometry#480]
We are replacing hoops by XBim. 
In below code we are able to get plot line bounding box distance by hoops, we want to get that by using XBim.
By using plot line bounding box distance we are able to find out front line margin of podium.
public void DetectProposedMargin(PlotDB objPlot, List<Point> polygon, List<Point> PlotPoint, string LevelName, out List<Tuple<List<Point>, string, string, string, string, Point, List<Point>>> ListPlotLineBBoxDistanceAllLevels)
        {
            try
            {
                ListPlotLineBBoxDistanceAllLevels = new List<Tuple<List<Point>, string, string, string, string, Point, List<Point>>>();
                var PlotPoints = ClsBimDataDB.Plots.FirstOrDefault().Points.ToList();
                //PlotPoints = PointOperator.ConvexHull(PlotPoints);
                var plotLineIntersectionData = new Dictionary<string, List<Tuple<double, Point, Point, Point, Point, double>>>();
                var plotLineIntersectionDataAll = new Dictionary<string, List<Tuple<double, Point, Point, Point, Point, double>>>();

                PointOperator objop = new PointOperator();
                Dictionary<string, double> sideNamesWithDistances = new Dictionary<string, double>();
                double Rad2Deg = 180.0 / Math.PI;

                double minDistanceOfBuildingToPlot = 999999;
                for (int k = 0; k < polygon.Count; k++)
                {
                    var pt = polygon[k];
                    var pt2 = polygon[(k + 1) % polygon.Count];
                    if (objop.ComputeEuclideanDistance(pt, pt2) < 1)
                    {
                        //k++;
                        continue;
                    }
                    var interSectedPoint = new Point();
                    var interSectedPoint2 = new Point();
                    //  Get each line from the plot points
                    for (int j = 0; j < PlotPoint.Count; j++)
                    {
                        //ClsConversion.Goforexcel(PlotPoint);
                        var nxt = PlotPoint[j];
                        var nxt2 = PlotPoint[(j + 1) % PlotPoint.Count];
                        if (objop.ComputeEuclideanDistance(nxt, nxt2) < 1)
                        {
                            // j++;
                            continue;
                        }
                        var tempdistance = objop.FindDistanceBetweenSegments(pt, pt2, nxt, nxt2, out interSectedPoint, out interSectedPoint2);// * clsBIMHandler.bimdcr.ConvfLength;
                        double diff = Math.Abs(Math.Atan2(pt2.Y - pt.Y, pt2.X - pt.X) - Math.Atan2(nxt2.Y - nxt.Y, nxt2.X - nxt.X));
                        double angle = Math.Round(Math.Min(diff, Math.Abs(180 - diff)) * Rad2Deg);
                        if (angle1R(angle))
                        {
                            var sideName = getIntersectedSideNameofPlot(objPlot, interSectedPoint);
                            if (string.IsNullOrEmpty(sideName))
                                sideName = getIntersectedSideNameofPlot(objPlot, interSectedPoint2);
                            if (sideName != string.Empty)
                            {
                                if (!plotLineIntersectionData.ContainsKey(sideName))
                                    plotLineIntersectionData[sideName] = new List<Tuple<double, Point, Point, Point, Point, double>>();
                                if (tempdistance > 1)// && IsPerpenducularToRoadandBuildingLine(sideName, pt, pt2, nxt, nxt2, interSectedPoint, interSectedPoint2))
                                {
                                    plotLineIntersectionData[sideName].Add(new Tuple<double, Point, Point, Point, Point, double>(tempdistance, interSectedPoint, interSectedPoint2, pt, pt2, angle));
                                }

                            }
                            if (tempdistance < minDistanceOfBuildingToPlot)
                                minDistanceOfBuildingToPlot = tempdistance;
                        }
                        //if (angle1R(angle))
                        {
                            var sideName = getIntersectedSideNameofPlot(objPlot, interSectedPoint);
                            if (string.IsNullOrEmpty(sideName))
                                sideName = getIntersectedSideNameofPlot(objPlot, interSectedPoint2);
                            if (sideName != string.Empty)
                            {
                                if (!plotLineIntersectionDataAll.ContainsKey(sideName))
                                    plotLineIntersectionDataAll[sideName] = new List<Tuple<double, Point, Point, Point, Point, double>>();
                                if (tempdistance > 1)// && IsPerpenducularToRoadandBuildingLine(sideName, pt, pt2, nxt, nxt2, interSectedPoint, interSectedPoint2))
                                {
                                    plotLineIntersectionDataAll[sideName].Add(new Tuple<double, Point, Point, Point, Point, double>(tempdistance, interSectedPoint, interSectedPoint2, pt, pt2, angle));
                                }

                            }
                            if (tempdistance < minDistanceOfBuildingToPlot)
                                minDistanceOfBuildingToPlot = tempdistance;
                        }
                    } // end Plot
                }// End Polygon

                foreach (var item in plotLineIntersectionData)
                {
                    var sortedMargin = item.Value.OrderBy(n => n.Item1).ToList();
                    List<Point> itersectedPoints = new List<Point>();
                    if (sortedMargin == null)
                    {

                    }
                    if (sortedMargin?.Count > 0)
                    {
                        itersectedPoints.Add(sortedMargin[0].Item2);
                        itersectedPoints.Add(sortedMargin[0].Item3);
                        Point CenterPoint = new Point((sortedMargin[0].Item2.X + sortedMargin[0].Item3.X) / 2, (sortedMargin[0].Item2.Y + sortedMargin[0].Item3.Y) / 2);
                        Point BuildLineCenterPoint = new Point((sortedMargin[0].Item4.X + sortedMargin[0].Item5.X) / 2, (sortedMargin[0].Item4.Y + sortedMargin[0].Item5.Y) / 2);
                        itersectedPoints.Add(BuildLineCenterPoint);
                        if (sortedMargin[0].Item1.ToString() == "8.45959788924709")
                        {
                            var tuple = new Tuple<List<Point>, string, string, string, string, Point, List<Point>>(polygon, "-1", (sortedMargin[0].Item1 + 1).ToString(), item.Key, LevelName, CenterPoint, itersectedPoints);
                            ListPlotLineBBoxDistanceAllLevels.Add(tuple);
                        }
                        else
                        {
                            var tuple = new Tuple<List<Point>, string, string, string, string, Point, List<Point>>(polygon, "-1", sortedMargin[0].Item1.ToString(), item.Key, LevelName, CenterPoint, itersectedPoints);
                            ListPlotLineBBoxDistanceAllLevels.Add(tuple);
                        }
                    }
                }
                foreach (var item in plotLineIntersectionDataAll)
                {
                    var sortedMargin = item.Value.OrderBy(n => n.Item1).ToList();
                    List<Point> itersectedPoints = new List<Point>();

                    itersectedPoints.Add(sortedMargin[0].Item2);
                    itersectedPoints.Add(sortedMargin[0].Item3);
                    Point CenterPoint = new Point((sortedMargin[0].Item2.X + sortedMargin[0].Item3.X) / 2, (sortedMargin[0].Item2.Y + sortedMargin[0].Item3.Y) / 2);
                    Point BuildLineCenterPoint = new Point((sortedMargin[0].Item4.X + sortedMargin[0].Item5.X) / 2, (sortedMargin[0].Item4.Y + sortedMargin[0].Item5.Y) / 2);
                    itersectedPoints.Add(BuildLineCenterPoint);
                    if (ListPlotLineBBoxDistanceAllLevels.Where(n => n.Item4 == item.Key).Count() == 0)
                    {
                        var tuple = new Tuple<List<Point>, string, string, string, string, Point, List<Point>>(polygon, "-1", (sortedMargin[0].Item1).ToString(), item.Key, LevelName, CenterPoint, itersectedPoints);
                        ListPlotLineBBoxDistanceAllLevels.Add(tuple);
                    }
                }
            }
            catch (Exception ex)
            {
                ShowStatus.SetStatus(false);
                throw ex;
            }
        }

**Comment by martin1cerny** [comment]
Hi @ashvinisawantsofttechengr , I'm glad you have chosen the Toolkit as a replacement for Hoops. However, I'm sorry, but this kind of question is way beyond the level of support we can provide here on GitHub. It is not an issue with the Toolkit, or IFC implementation. If you need an assistance with mapping Hoops features and functionality to xbim Toolkit, we can provide commercial support for that. Feel free to get in touch if you are interested.
