### ISSUE TITLE
How to get subcomponent of any element in xbim? 

### ISSUE THREAD

**Issue by ashvinisawantsofttechengr** [xBimTeam/XbimGeometry#488]
public override string GetPlotName(BIMDCREnums.clsEnums.ModelType model, int buildingNo)
        {
            string Name = string.Empty;
            try
            {
                var m_compIFCSite = ClsECC.m_clsExecCtxCmp.GetComponent(model, BIMDCREnums.clsEnums.EC.IFCSITE, buildingNo);
                foreach (Component compsurface in m_compIFCSite.GetSubcomponents())
                {
                    Name = compsurface.GetName();
                }
            }
            catch (System.Exception)
            {
#if DEBUG
                throw;
#endif
            }
            return Name;
        }
Want to get subcomponent of IfcSite.

**Comment by andyward** [comment]
Does this example help? https://docs.xbim.net/examples/spatial-hierarchy.html
