### ISSUE TITLE
Xbim Xplorer can not display product with using tessellated data

### ISSUE THREAD

**Issue by 6ther** [xBimTeam/XbimGeometry#490]
I do not know why the Xbim Xplorer can not display product that using tessellated data.
Is my tessellated data is wrong?
This is my ifc.
[TessellationTest.txt](https://github.com/user-attachments/files/16330036/TessellationTest.txt)

**Comment by gyorm** [comment]
I think this object is too small for XbimXplorer to handle comfortably. The sides measure at 0.008m, and 0.013m respectively.
It actually does open it, you need to zoom out enough to see it. I looked at it with other viewers, and it opened without problems.

**Comment by andyward** [comment]
Thanks @gyorm! Looks like it's just an issue with the frustrum in XbimXplorer/Helix3D - the object is so small that zooming to it puts it in front of the near clip-plane. Zooming out a bit ensures it appears. 

It's a bit of an edge case (walls are normally larger than 8x13mm!)... but if needs a fix this needs to be in xbimTeam/WindowsUI not Geometry. My guess is we're using a fixed distance for the near clip-plane

**Comment by 6ther** [comment]
thanks a lot.
