### ISSUE TITLE
Bug in XbimSolidSet::Init(IIfcExtrudedAreaSolid^ repItem, ILogger^ logger)

### ISSUE THREAD

**Issue by santiagoIT** [xBimTeam/XbimGeometry#492]
When the composite profile consists of only one profile, a log warning is issued. However the LogInfo format message is missing an argument, which results in an exception being thrown and the XbimSolid not being generated.

Will submit a pull request with the simple fix

**Comment by santiagoIT** [comment]
Pull request:
https://github.com/xBimTeam/XbimGeometry/pull/493

**Comment by andyward** [comment]
Thanks - merged!
