### ISSUE TITLE
Geometry generation exception

### ISSUE THREAD

**Issue by GVladislavG** [xBimTeam/XbimGeometry#514]
Hello, xBim team!

There is problem in generation of geometry in this file.
[ProblemIfc.zip](https://github.com/user-attachments/files/18050083/ProblemIfc.zip)

**Comment by andyward** [comment]
There seems to be a some issues with this model. I was able to open it partially in our latest v6 engine.

I tried putting it through the IFC validation service at https://validate.buildingsmart.org/ - and it a) flagged up some invalid Ifc Schema, and b) failed checking the Implementors agreements (actually broke the validator). 

![image](https://github.com/user-attachments/assets/03a635be-af0c-4bab-a936-6b7038a9d537)

Is this a Tekla test file or a real customer file?

**Comment by GVladislavG** [comment]
It is file made in Tekla by real customer. 
We also had problems with geometry generation in Tekla files before.

**Comment by andyward** [comment]
It loads in the latest v6 GE but I did have to disable EsentModel, and use MemoryModel explicitly as it was hitting an issue of "Version store out of memory (cleanup already attempted)" in Esent.

There are a number of errors identified in the model however. Some may be down to precision.

![image](https://github.com/user-attachments/assets/de0ffe30-68cb-4851-ad27-996f52c510c1)

What issue did you hit, and what versions of xbim are you using?

**Comment by GVladislavG** [comment]
I tried to use this version pairs:
XBim.Essentials 6.0.445 + XBim.Geometry 5.1.541
XBim.Essentials 6.0.484 - Develop + XBim.Geometry 5.1.762 - Develop

I got this Exception:
![Снимок экрана 2024-12-10 174431](https://github.com/user-attachments/assets/de963084-f1cb-475a-a251-fe9e38981ebd)

![Снимок экрана 2024-12-10 174452](https://github.com/user-attachments/assets/5b49bfde-2e5c-42f8-976f-a3b9b36b2111)

**Comment by GVladislavG** [comment]
When I try to add this code fragment to my project I get this
![image](https://github.com/user-attachments/assets/554da828-5bd3-41b6-81d9-f8dc4a041428)

**Comment by andyward** [comment]
Try it earlier in the application lifecycle. e.g. at app initialisation. It needs to be configured before any access IfcStore or other xbim code

**Comment by GVladislavG** [comment]
This code fragment didn't help(( 
I got the same error "Version store out of memory (cleanup already attempted)".
Maybe there are some other ways?

**Comment by andyward** [comment]
You must be adding the Esent (or Heuristic) model in somewhere later on in the lifecycle. The ideas is we're taking out Esent as a IModel implementation as that's where the issue arises.

Check your code for 'AddEsent' or 'AddHeuristic' in the ConfigureServices builder.

**Comment by tvcong0999** [comment]
> Ok, this isn't a Geometry issue as much as a problem in the EsentModel. So v6 GE is irrelevant (GE6 will be in nuget soon, I don't believe it's a solution for this issue). It's the same issue I encountered where we've hit a limit in Esent ("Version store out of memory (cleanup already attempted)").
> 
> A workaround may be if you're able to try setting up xbim as per:
> 
> ```cs
> XbimServices.Current.ConfigureServices(s => s.AddXbimToolkit(opt => 
>     opt.AddMemoryModel() // Rather than AddHeuristicModel(), which employs Esent for larger IFC files.
> ));
> ```
> 
> Separately there may be some [Esent config](https://github.com/xBimTeam/XbimEssentials/blob/8c4bfb2be73cef1ee0c6b3fcab0ca0fb3381a296/Xbim.IO.Esent/Esent/PersistedEntityInstanceCache.cs#L609) we can increase behind `EsentModel` but will need someone to look into this. Would need to understand why this particular model is triggering the issues first.

I had the same problem and it worked for me. Thanks a lot!!!

**Comment by GVladislavG** [comment]
Thanks! 
Can you also take a look at [#515](https://github.com/xBimTeam/XbimGeometry/issues/515) please?
There is incorrect geometry generation.

**Comment by andyward** [comment]
Closing in GE - tracking in Essentials as it's an Esent issue
