### ISSUE TITLE
Weird vertices values for IfcSlab with OpeningAndAdditionsExcluded

### ISSUE THREAD

**Issue by Panddha** [xBimTeam/XbimGeometry#52]
Hi,

first of all I think xBim is a great project and I couldn't find any other library as good or even close to it. 

I need to know the wcs vertices of an IfcSlab and its openings.
The first part (ifcslab without openings) is working fine, but the second part is not.

1. `XbimGeometryRepresentationType.OpeningsAndAdditionsExcluded`: I get correct (wcs) values.
2. `XbimGeometryRepresentationType.OpeningsAndAdditionsOnly`: I don't get any values.
3.` XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded`: I get weird values.

I don't understand this behaviour and its probably because I dont really get how the geometry works here, so any help is very much appreciated.

My code to get wcs vertices (which is from [stackoverflow](http://stackoverflow.com/questions/42216138/xbim-geometry-error)). I don't apply the transformation as I concluded the problem is not the transformation (transformation works fine for OpeningAndAdditionsExcluded).

```
public void CalculateZeichenkoerper(IfcProduct product) {

  var productShape = 
```
`  context.ShapeInstancesOf(product)
.Where(p => p.RepresentationType == XbimGeometryRepresentationType.OpeningsAndAdditionsExcluded)
.Distinct();`

    if (productShape.Any()) {
        foreach (var shapeInstance in productShape) {
            Console.WriteLine("New ShapeInstance");
            var geometry = Bauelement.context.ShapeGeometry(shapeInstance);
            var data = ((IXbimShapeGeometryData)geometry).ShapeData;
            using (var stream = new MemoryStream(data)) {
                using (var reader = new BinaryReader(stream)) {
                    XbimShapeTriangulation mesh = reader.ReadShapeTriangulation();

                    //mesh = mesh.Transform(product.Transform()); // apply the absolute wcs transform to the mesh to get the absolute vertices
                    foreach (var v in mesh.Vertices.OrderByDescending(p => (p.Z))) {
                        Console.WriteLine(v);
                    }
                }
            }
        }
    }
}`

For OpeningsAndAdditionsExcluded I get these values which are correct. (I checked them after applying the transform of the ifcslab)
> 33,5999984741211 48,4000015258789 0,319999992847443
52 48,4000015258789 0,319999992847443
52 17,2000007629395 0,319999992847443
70,7799987792969 17,2000007629395 0,319999992847443
70,7799987792969 0 0,319999992847443
9,9475983006414E-14 0 0,319999992847443
0 48,4000015258789 0,319999992847443
18,3999996185303 48,4000015258789 0,319999992847443
18,3999996185303 25,6000003814697 0,319999992847443
33,5999984741211 25,6000003814697 0,319999992847443
52 48,4000015258789 -3,99680288865056E-15
33,5999984741211 48,4000015258789 -3,99680288865056E-15
52 17,2000007629395 -3,99680288865056E-15
70,7799987792969 17,2000007629395 -3,99680288865056E-15
70,7799987792969 0 -3,99680288865056E-15
9,9475983006414E-14 0 -3,99680288865056E-15
0 48,4000015258789 -3,99680288865056E-15
18,3999996185303 48,4000015258789 -3,99680288865056E-15
18,3999996185303 25,6000003814697 -3,99680288865056E-15
33,5999984741211 25,6000003814697 -3,99680288865056E-15

For OpeningAndAdditionsIncluded I am getting these values which seem like absolute/wcs coordinates in respect to Z-Coordinates but X should be around 200 and Y about 500.
> -189,744216918945 139,919387817383 20,4500007629395
-171,344223022461 139,919387817383 20,4500007629395
-189,744216918945 117,119384765625 20,4500007629395
-171,344223022461 108,719383239746 20,4500007629395
-204,944229125977 139,919387817383 20,4500007629395
-206,744216918945 133,594375610352 20,4500007629395
-205,194229125977 133,594375610352 20,4500007629395
-223,344223022461 139,919387817383 20,4500007629395
-206,744216918945 129,619384765625 20,4500007629395
-205,194229125977 129,619384765625 20,4500007629395
-204,944229125977 117,119384765625 20,4500007629395
-196,369216918945 105,069381713867 20,4500007629395
-196,369216918945 102,419380187988 20,4500007629395
-191,119216918945 92,7693862915039 20,4500007629395
-196,369216918945 92,7693862915039 20,4500007629395
-196,369216918945 91,8193817138672 20,4500007629395
-203,969223022461 98,8193817138672 20,4500007629395
-205,219223022461 98,8193817138672 20,4500007629395
-205,219223022461 91,8193817138672 20,4500007629395
-223,344223022461 91,5193862915039 20,4500007629395
-189,494216918945 133,594375610352 20,4500007629395
-187,944229125977 133,594375610352 20,4500007629395
-189,494216918945 129,619384765625 20,4500007629395
-187,944229125977 129,619384765625 20,4500007629395
-152,564224243164 91,5193862915039 20,4500007629395
-152,564224243164 108,719383239746 20,4500007629395
-189,469223022461 108,419380187988 20,4500007629395
-189,469223022461 102,419380187988 20,4500007629395
-190,819229125977 102,419380187988 20,4500007629395
-191,119216918945 102,419380187988 20,4500007629395
-189,469223022461 98,8193817138672 20,4500007629395
-189,469223022461 91,8193817138672 20,4500007629395
-190,819229125977 91,8193817138672 20,4500007629395
-191,119216918945 91,8193817138672 20,4500007629395
-203,969223022461 91,8193817138672 20,4500007629395
-190,819229125977 108,419380187988 20,4500007629395
-191,119216918945 105,069381713867 20,4500007629395
-190,819229125977 98,8193817138672 20,4500007629395
-171,344223022461 139,919387817383 20,1299991607666
-189,744216918945 139,919387817383 20,1299991607666
-189,744216918945 117,119384765625 20,1299991607666
-171,344223022461 108,719383239746 20,1299991607666
-187,944229125977 133,594375610352 20,1299991607666
-187,944229125977 129,619384765625 20,1299991607666
-189,494216918945 129,619384765625 20,1299991607666
-189,494216918945 133,594375610352 20,1299991607666
-190,819229125977 98,8193817138672 20,1299991607666
-191,119216918945 102,419380187988 20,1299991607666
-189,469223022461 98,8193817138672 20,1299991607666
-196,369216918945 102,419380187988 20,1299991607666
-191,119216918945 92,7693862915039 20,1299991607666
-190,819229125977 91,8193817138672 20,1299991607666
-191,119216918945 91,8193817138672 20,1299991607666
-190,819229125977 102,419380187988 20,1299991607666
-191,119216918945 105,069381713867 20,1299991607666
-190,819229125977 108,419380187988 20,1299991607666
-152,564224243164 91,5193862915039 20,1299991607666
-152,564224243164 108,719383239746 20,1299991607666
-189,469223022461 108,419380187988 20,1299991607666
-189,469223022461 102,419380187988 20,1299991607666
-189,469223022461 91,8193817138672 20,1299991607666
-196,369216918945 91,8193817138672 20,1299991607666
-203,969223022461 91,8193817138672 20,1299991607666
-203,969223022461 98,8193817138672 20,1299991607666
-205,219223022461 91,8193817138672 20,1299991607666
-223,344223022461 91,5193862915039 20,1299991607666
-204,944229125977 117,119384765625 20,1299991607666
-196,369216918945 105,069381713867 20,1299991607666
-204,944229125977 139,919387817383 20,1299991607666
-205,194229125977 129,619384765625 20,1299991607666
-205,194229125977 133,594375610352 20,1299991607666
-206,744216918945 129,619384765625 20,1299991607666
-223,344223022461 139,919387817383 20,1299991607666
-196,369216918945 92,7693862915039 20,1299991607666
-205,219223022461 98,8193817138672 20,1299991607666
-206,744216918945 133,594375610352 20,1299991607666

**Comment by redscorpion201** [comment]
I'm using `context.ShapeInstancesOf(ifcElement).Where(x => x.RepresentationType == XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded)` **without** the distinct filter.
This works fine for me.
I suppose this works, because openings and additions use the same coordinates but are substracted from the remaining geometry. However this is only a guess from my side...

**Comment by Panddha** [comment]
Thank you very much for your idea.

Well if I use OpeningAndAdditionsIncluded without the distinct filter I get the right shape but at still at the wrong position.
If I use OpeningAndAdditionsOnly without the distinct filter I still get nothing.
If I use OpeningAndAdditionsExcluded without the distinct filter I still get the right shape at the right position.

So nothing seems changed.

Example with absolute coordinates (INDEX X,Y):
![face](https://cloud.githubusercontent.com/assets/10030741/25174342/583288ce-24f7-11e7-9f7d-bc4dd3c01251.png)

**Comment by CBenghi** [comment]
Hello @Panddha,
I'm happy to look into this but I wonder if we can try to simplify the question.
I'm attaching a file to use as a sample. What is it that you are looking for in this file?
![image](https://cloud.githubusercontent.com/assets/5476273/25178004/0556d236-24fc-11e7-9322-8a1d473b69ce.png)

Claudio
[OneSmallWallOneVoid.zip](https://github.com/xBimTeam/XbimGeometry/files/933823/OneSmallWallOneVoid.zip)

**Comment by Panddha** [comment]
Hi @CBenghi,

I want the absolute coordinates for the opening in that wall. 

With your file I get the correct numbers for OpeningsAndAdditionsExcluded and OpeningsAndAdditionsIncluded but no values for OpeningsAndAdditionsOnly.
(But I guess I could get the them via e.g. `IfcWall.Openings` though I don't know how get the shape from that.)

The problem (wrong coordinates for OpeningsAndAdditionsIncluded) seems to occur because I try to transform the mesh with ` mesh = mesh.Transform(product.Transform())`. The relative coordinates seem fine in my file. So the transform behaves weirdly if the mesh is not centered, I guess.


Transformed mesh from OpeningsAndAdditionsIncluded for some wall in my file:
X should be around 300 and Y around 600, Z values are **nearly** correct (error seems to grow with larger values)
> 120,538258344084 728,816872940906 5,25999994278135
> 101,600758344084 728,816872940906 5,25999994278135
> 120,538258344084 728,691872940906 5,25999994278135
> 101,600758344084 728,691872940906 5,25999994278135
> 106,121586591154 728,816872940906 2,20999999046507
> 106,615757733732 728,816872940906 2,20999999046507
> 115,646595746428 728,816872940906 2,20999999046507
> 116,128254681975 728,816872940906 2,20999999046507
> 117,413258344084 728,816872940906 2,20999999046507
> 107,900761395842 728,816872940906 2,20999999046507
> 114,361592084318 728,816872940906 2,20999999046507
> 104,836598187834 728,816872940906 2,20999999046507
> 117,413258344084 728,691872940906 2,20999999046507
> 116,128254681975 728,691872940906 2,20999999046507
> 115,646595746428 728,691872940906 2,20999999046507
> 114,361592084318 728,691872940906 2,20999999046507
> 106,121586591154 728,691872940906 2,20999999046507
> 104,836598187834 728,691872940906 2,20999999046507
> 107,900761395842 728,691872940906 2,20999999046507
> 106,615757733732 728,691872940906 2,20999999046507
> 106,615757733732 728,816872940906 -0,0500000000043086
> 106,121586591154 728,816872940906 -0,0500000000043086
> 116,128254681975 728,816872940906 -0,0500000000043086
> 115,646595746428 728,816872940906 -0,0500000000043086
> 117,413258344084 728,816872940906 -0,0500000000043086
> 114,361592084318 728,816872940906 -0,0500000000043086
> 107,900761395842 728,816872940906 -0,0500000000043086
> 104,836598187834 728,816872940906 -0,0500000000043086
> 117,413258344084 728,691872940906 -0,0500000000043086
> 116,128254681975 728,691872940906 -0,0500000000043086
> 114,361592084318 728,691872940906 -0,0500000000043086
> 115,646595746428 728,691872940906 -0,0500000000043086
> 106,121586591154 728,691872940906 -0,0500000000043086
> 104,836598187834 728,691872940906 -0,0500000000043086
> 107,900761395842 728,691872940906 -0,0500000000043086
> 106,615757733732 728,691872940906 -0,0500000000043086
> 120,538258344084 728,816872940906 -0,100000000743245
> 101,600758344084 728,816872940906 -0,100000000743245
> 120,538258344084 728,691872940906 -0,100000000743245
> 101,600758344084 728,691872940906 -0,100000000743245

**Not** transformed mesh from OpeningsAndAdditionsIncluded for same wall in my file:
> -152,544219970703 112,919387817383 5,30999994277954
> -171,481719970703 112,919387817383 5,30999994277954
> -152,544219970703 112,794387817383 5,30999994277954
> -171,481719970703 112,794387817383 5,30999994277954
> -166,960891723633 112,919387817383 2,25999999046326
> -166,466720581055 112,919387817383 2,25999999046326
> -157,435882568359 112,919387817383 2,25999999046326
> -156,954223632813 112,919387817383 2,25999999046326
> -155,669219970703 112,919387817383 2,25999999046326
> -165,181716918945 112,919387817383 2,25999999046326
> -158,720886230469 112,919387817383 2,25999999046326
> -168,245880126953 112,919387817383 2,25999999046326
> -155,669219970703 112,794387817383 2,25999999046326
> -156,954223632813 112,794387817383 2,25999999046326
> -157,435882568359 112,794387817383 2,25999999046326
> -158,720886230469 112,794387817383 2,25999999046326
> -166,960891723633 112,794387817383 2,25999999046326
> -168,245880126953 112,794387817383 2,25999999046326
> -165,181716918945 112,794387817383 2,25999999046326
> -166,466720581055 112,794387817383 2,25999999046326
> -166,466720581055 112,919387817383 -6,12199180238804E-12
> -166,960891723633 112,919387817383 -6,12199180238804E-12
> -156,954223632813 112,919387817383 -6,12199180238804E-12
> -157,435882568359 112,919387817383 -6,12199180238804E-12
> -155,669219970703 112,919387817383 -6,12199180238804E-12
> -158,720886230469 112,919387817383 -6,12199180238804E-12
> -165,181716918945 112,919387817383 -6,12199180238804E-12
> -168,245880126953 112,919387817383 -6,12199180238804E-12
> -155,669219970703 112,794387817383 -6,12199180238804E-12
> -156,954223632813 112,794387817383 -6,12199180238804E-12
> -158,720886230469 112,794387817383 -6,12199180238804E-12
> -157,435882568359 112,794387817383 -6,12199180238804E-12
> -166,960891723633 112,794387817383 -6,12199180238804E-12
> -168,245880126953 112,794387817383 -6,12199180238804E-12
> -165,181716918945 112,794387817383 -6,12199180238804E-12
> -166,466720581055 112,794387817383 -6,12199180238804E-12
> -152,544219970703 112,919387817383 -0,0500000007450581
> -171,481719970703 112,919387817383 -0,0500000007450581
> -152,544219970703 112,794387817383 -0,0500000007450581
> -171,481719970703 112,794387817383 -0,0500000007450581

Transformed mesh from OpeningsAndAdditionsExcluded for same wall in my file:
X,Y, and Z values are all correct. 
> 273,082478314787 615,959985123523 5,31000013351622
> 292,019980222136 615,959985123523 5,31000013351622
> 273,082478314787 615,834985123523 5,31000013351622
> 292,019980222136 615,834985123523 5,31000013351622
> 292,019980222136 615,959985123523 -0,0499999999981866
> 273,082478314787 615,959985123523 -0,0499999999981866
> 273,082478314787 615,834985123523 -0,0499999999981866
> 292,019980222136 615,834985123523 -0,0499999999981866

Transformed mesh from OpeningsAndAdditionsIncluded for the wall in OneSmallWallOneVoid.ifc:
None of these Y values can be found in OpeningsAndAdditionsExcluded (below) which is weird as the the opening points should have a y value which is included below.
> -3853,69421604864 2165,5441479146 3000
> -6853,6942770838 2165,5441479146 3000
> -3853,69421604864 1875,54408687945 3000
> -6853,6942770838 1875,54408687945 3000
> -4153,69421604864 2165,5441479146 2400
> -4853,6942770838 2165,5441479146 2400
> -4153,69421604864 1875,54408687945 2400
> -4853,6942770838 1875,54408687945 2400
> -4153,69421604864 2165,5441479146 1200
> -4853,6942770838 2165,5441479146 1200
> -4853,6942770838 1875,54408687945 1200
> -4153,69421604864 1875,54408687945 1200
> -3853,69421604864 2165,5441479146 0
> -6853,6942770838 2165,5441479146 0
> -3853,69421604864 1875,54408687945 0
> -6853,6942770838 1875,54408687945 0

**Not** transformed mesh from OpeningsAndAdditionsIncluded for the wall in OneSmallWallOneVoid.ifc:
The values here are the same as OpeningsAndAdditionsExcluded _(just in this file, not in mine: in mine file the values are vastly different, see above)_
> -426,847106933594 1155,27209472656 3000
> -3426,84716796875 1155,27209472656 3000
> -426,847106933594 865,272033691406 3000
> -3426,84716796875 865,272033691406 3000
> -726,847106933594 1155,27209472656 2400
> -1426,84716796875 1155,27209472656 2400
> -726,847106933594 865,272033691406 2400
> -1426,84716796875 865,272033691406 2400
> -726,847106933594 1155,27209472656 1200
> -1426,84716796875 1155,27209472656 1200
> -1426,84716796875 865,272033691406 1200
> -726,847106933594 865,272033691406 1200
> -426,847106933594 1155,27209472656 0
> -3426,84716796875 1155,27209472656 0
> -426,847106933594 865,272033691406 0
> -3426,84716796875 865,272033691406 0

Transformed mesh from OpeningsAndAdditionsExcluded for the wall in OneSmallWallOneVoid.ifc:
> -3426,84710911505 1155,27205318804 3000
> -426,84710911505 1155,27205318804 3000
> -3426,84710911505 865,27205318804 3000
> -426,84710911505 865,27205318804 3000
> -426,84710911505 1155,27205318804 0
> -3426,84710911505 1155,27205318804 0
> -3426,84710911505 865,27205318804 0
> -426,84710911505 865,27205318804 0

**Not** transformed mesh from OpeningsAndAdditionsExcluded for the wall in 
> 0 145 3000
> 3000 145 3000
> 0 -145 3000
> 3000 -145 3000
> 3000 145 0
> 0 145 0
> 0 -145 0
> 3000 -145 0


My conclusion is that `mesh = mesh.Transform(product.Transform()); ` does not what i want it to do.
Maybe I need to use another transform and not the IfcProduct's transform (though I do not know which).

Dominik

**Comment by CBenghi** [comment]
It might be only marginally helpful, but the an example on how to put a RepresentationItem (e.g. the shape of the void) in the right location is available in the Xbim.Presentation\WpfMeshGeometry3D.cs

the function that does that is public static WpfMeshGeometry3D GetGeometry(IIfcShapeRepresentation rep, XbimModelPositioningCollection positions, Material mat)

In explorer you can: 
1) you open the file,
2) select the wall
3) select hasopenings # 1031 (in the property panel)
4) select relatedopeningElement # 1026
5) select representation # 1019
6) select representations # 1017

And you'll see that the 3d viewer highlights the void in the window like so:

![image](https://cloud.githubusercontent.com/assets/5476273/25189438/1081972a-2521-11e7-8d92-6c3ac2bb5fe3.png)

Which is I think what you're looking for.

**Comment by Panddha** [comment]
This function was quite helpful and is pretty much what I'm looking for. Thank you!

 I might get the right information. Though I'm stuck at how/where to get a `XbimModelPositioningCollection` out of a `IfcStore` or `Xbim3DModelContext`.

Could you please explain how to do that or which class produces a `XbimModelPositioningCollection` .
