### ISSUE TITLE
IfcSweptDiskSolid along IfcPolyLine

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimGeometry#53]
Hello,

It appears that there is possibly another bug with IfcSweptDiskSolid.
The attached model is a rebar with swept disk along polyline geometry.

The first image is from Solibri Model Viewer, the second one is from latest Windows UI develop build.
I'm preparing another file where this kind of issue is even more evident.

![circular-rebar-solibri](https://cloud.githubusercontent.com/assets/5221157/25441754/6b32b834-2aa3-11e7-9d44-cdacd92661cd.png)

![circular-rebar-xbim](https://cloud.githubusercontent.com/assets/5221157/25441763/6f625734-2aa3-11e7-9e40-e94a55398bdf.png)

[circular-rebar.zip](https://github.com/xBimTeam/XbimGeometry/files/958868/circular-rebar.zip)

**Comment by urosjovanovic** [comment]
One more sample.

![circular-rebar-2-solibri](https://cloud.githubusercontent.com/assets/5221157/25442537/9965da4a-2aa5-11e7-866b-07dd420db2eb.png)

![circular-rebar-2-xbim](https://cloud.githubusercontent.com/assets/5221157/25442539/9bfee65c-2aa5-11e7-845b-a4e26b80b8e2.png)

[circular-rebar-2.zip](https://github.com/xBimTeam/XbimGeometry/files/958922/circular-rebar-2.zip)

**Comment by CBenghi** [comment]
It looks like if the profile is not aligned to the Directrix in IfcSweptDiskSolid.
I'm not sure this would be supported in OCC.
I'll have a look,

**Comment by CBenghi** [comment]
Hello @urosjovanovic,

I've posted an update in https://github.com/xBimTeam/XbimGeometry/commit/96635a404d06fab04133637b0dcf02c8944c31c6

that should fix the issue; I've only tested the first sample, please have a look at the models you have to confirm, and in case close the issue.

**Comment by urosjovanovic** [comment]
Hello @CBenghi 

Is the new Geometry package available via NuGet in WindowsUI on develop branch?
I can't test it because it looks like it isn't available to download, and for some reason, rebuilding the Xbim.Geometry solution in VS2015 U3 fails for me (bunch of linking errors) so I can't get the updated binaries.

Maybe you can send me the .dlls?

**Comment by CBenghi** [comment]
It should.
You have to add the develop nuget source to your nuget configuration.
See the list at http://docs.xbim.net/index.html in the "Compilation" section.
Claudio

**Comment by urosjovanovic** [comment]
Okay, I've managed to run WindowsUI with latest geometry lib. The first sample appears to be fixed indeed, but the second one still produces the same output. I'm not actually sure if these two issues are related at all actually.

**Comment by SteveLockley** [comment]
Please see #74 for resolution
