### ISSUE TITLE
AccessViolationException when importing .ifc file

### ISSUE THREAD

**Issue by vomicz** [xBimTeam/XbimGeometry#54]
I'm trying to open the file:
[171210TrainingStructure_brep.zip](https://github.com/xBimTeam/XbimGeometry/files/973446/171210TrainingStructure_brep.zip)

Using the following lines of code:

```C#
var model = IfcStore.Open(fileName, null, null, (p, s) => { UpdateProgress(context, p); });`
if (model.GeometryStore.IsEmpty)
{
    var ctxt = new Xbim3DModelContext(model);
    //upgrade to new geometry representation, uses the default 3D model
    ctxt.CreateContext((p, s) => { UpdateProgress(context, p); }); //<-This line throws the exception
}
```

And I get an AccessViolationException. Occasionally, the context is created just fine but most of the attempts just fail.

#### Message: 
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
#### StackTrace:
at BRepOffsetAPI_MakeOffset.Perform(BRepOffsetAPI_MakeOffset* , Double , Double )
   at Xbim.Geometry.XbimWire.Init(IIfcCenterLineProfileDef profile)

**Comment by CBenghi** [comment]
Hello @vomicz,
this is something to do with multithreading.
As a workaround I've posted an update to Xplorer that allows you to configure the geometry engine to work in a single thread.
If you do this the application will mesh the file correctly.

![image](https://cloud.githubusercontent.com/assets/5476273/25824530/b05bedd4-3437-11e7-92e1-a4918e1fa267.png)

I'll still try to investigate the issue in the days to come.

**Comment by vomicz** [comment]
Great, thank you for the information.
However, I'm not using the explorer for the geometry reading, is there a way for me to force this attribute on the CreateContext() method?

**Comment by CBenghi** [comment]
You can create the context in a single thread with the following code:
```
var context = new Xbim3DModelContext(model);
context.MaxThreads = 1;
```
Hope this helps.

**Comment by CBenghi** [comment]
This should be fixed by https://github.com/xBimTeam/XbimGeometry/commit/7a252c7a8fb49815629770f0cdf7b1d225ae7965

**Comment by andyward** [comment]
Closing
