### ISSUE TITLE
Reading transformed geometry based on IfcLocalPlacement

### ISSUE THREAD

**Issue by urosjovanovic** [xBimTeam/XbimGeometry#55]
Hello all,

Is there an option to read transformed geometry coordinates, based on IfcLocalPlacement? 
For example. there is an IfcSite instance which has a local placement (10, 10, 0) relative to the world coordinate system (as defined [here](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcgeometricconstraintresource/lexical/ifclocalplacement.htm)) and inside that IfcSite is an IfcBuilding instance with local placement (5, 5, 0) relative to the IfcSite and inside that building is an IfcDoor instance with local placement (2, 2, 0) relative to the building. 

If I were to read vertices from that door instance, this local placement transformation wouldn't be applied (aka offset (17, 17, 0) wouldn't be added). 

Is there a method or something exposed via public API which can calculate this kind of transformation, or  must it be calculated manually if needed?

**Comment by urosjovanovic** [comment]
It seems like previous version of Xbim (v3) did exactly what I've described. Upon reading mesh data and applying transform (if shape instance has any) I would get exact coordinates (including local placement offsets). In version 4 though, this is not the case. I'm gonna try to extract a sample where I can display this behaviour more clearly.

**Comment by gcoulby** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [d](https://trello.com/c/6ndZguNs/1-d)

**Comment by urosjovanovic** [comment]
I've managed to get what I want like this:

`XbimMatrix3D transform = shapeInstance.Transformation * new XbimPlacementTree(model).WorldCoordinateSystem;`

Now, I'm not sure if this is the correct way to go about this. Will do some more research and report back.

**Comment by CBenghi** [comment]
@urosjovanovic, 
well spotted, if you think there's scope for a clearer API feel free to fork the repository and send pull request.

**Comment by SteveLockley** [comment]
Resolved
