### ISSUE TITLE
Problem occur in Deployment on another PC 

### ISSUE THREAD

**Issue by BIMDevelopement** [xBimTeam/XbimGeometry#6]
Hi ,

I am trying to deploy my application on another PC where visual studio 2013 is not installed .I have installed 4.5.1 & 4.5.2 both framework. But still conversion of ifc to wexbim is not done .

**Comment by LloydPickering** [comment]
I think I know the problem... The Geometry Engine is native C++ and as such requires the Redistributable Visual C++ Package to be installed on the PC/Server to which you are deploying.

You can get it from:
https://www.microsoft.com/en-gb/download/details.aspx?id=40784
