### ISSUE TITLE
IFC Alignment 1.1 Export Plugin

### ISSUE THREAD

**Issue by FlixFix** [xBimTeam/XbimGeometry#62]
Hi guys!
My name is Felix and I'm studying civil engineering, currently writing my dissertation. 
The subject is a documentation of alignment elements in road design and the mapping of alignments onto an .ifc file. Therefore my dissertation also explains the different entities of the ifc alignment with all their attributes.
However, the main goal of my thesis is to program an ifc export plugin for Autodesk civil 3D.
I've only just started coding and learned c# two months ago, so I'm fairly new to the whole area. My current plugin already creates a .txt-file listing all the alignments and profiles with their attributes needed for an ifc-file. It does not create a real ifc file yet though. Therefore I need an early binding to write the actual ifc-file. 
As I said I don't Know much bout coding yet and even less bout GitHub, but do you have such an early binding that lets me create an ifc-file and that i could use for my purpose or is your code only to read the ifc-file? 
Sorry if my answer to this is fairly obvious, but as I said I'm really new in the area.

I appreciate every answer and help regarding my problem! Thank you very much in advance.

Regards,
Felix

**Comment by SteveLockley** [comment]
Off topic for this forum
