### ISSUE TITLE
Retrieve  data or informations from ifc file using xbim

### ISSUE THREAD

**Issue by herzim** [xBimTeam/XbimGeometry#63]
Hi All,
Is it possible,to retrieve a data  from ifc file with xbim 
i would like to get all informations as the left side of XbimXplorer but in web page
Thanks
![cap](https://user-images.githubusercontent.com/3863533/28170253-bbde36e8-67dc-11e7-937c-d0d0d78bc0b6.PNG)

**Comment by CBenghi** [comment]
Hello,
Yes, it is.
You can probably start looking at the example at
http://docs.xbim.net/examples/excel-space-report-from-ifc.html

**Comment by herzim** [comment]
Thank you for your prompt response.
My problem is that i do not want to specify the type like "IIfcSpace"
var spaces = model.Instances.OfType<IIfcSpace>().ToList();
I want to recover all layers regardless of the contents of the file.

**Comment by CBenghi** [comment]
I don't understand what you mean by layer.

**Comment by herzim** [comment]
I want to recover the information shown by this screenshot
![infossh](https://user-images.githubusercontent.com/3863533/28203639-77e7b752-6872-11e7-93d4-6e1645255d0a.PNG)

**Comment by CBenghi** [comment]
The initial code you need looks something like

``` cs
private void button_Click(object sender, RoutedEventArgs e)
{
	
	using (var model = IfcStore.Open("SampleHouse.ifc"))
	{
		//Get all spaces in the model. 
		//We use ToList() here to avoid multiple enumeration with Count() and foreach(){}
		var project = model.Instances.OfType<IIfcProject>().FirstOrDefault();

		report(project, 0);
	}
}


private void report(IIfcObjectDefinition obj, int v)
{
	Write(obj.Name, v, obj.GetType().Name);
	foreach (var ifcRelAggregates in obj.IsDecomposedBy)
	{
		foreach (var ifcObjectDefinition in ifcRelAggregates.RelatedObjects)
		{
			report(ifcObjectDefinition, v+1);
		}
	}
}

private void Write(string content, int indent, string type = "")
{
	string indentString = new string('\t', indent);
	Console.WriteLine($"{indentString}{content} {type}");
}
```
Then you'll have to decide what objects to show for each of the ifcspaces and group them by class.

I Hope this helps,
Claudio

**Comment by herzim** [comment]
I hope so too, thank you so much.
