### ISSUE TITLE
 converting file from ifc to wexbim with progress bar

### ISSUE THREAD

**Issue by herzim** [xBimTeam/XbimGeometry#65]
Hello
i need a help please , i  want to see a progress bar when converting file from ifc to wexbim
Is it possible ?

Thanks

**Comment by SteveLockley** [comment]
Off topic. You will need to implement a call back function in your code or an event raiser

**Comment by andyward** [comment]
To get progress updates, just pass in a delegate when calling `Xbim3DModelContext.CreateContext(progressDelegate)`

https://github.com/xBimTeam/XbimGeometry/blob/7c9a341e119a196cd779e582d9d9715905271694/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L666
