### ISSUE TITLE
Geometry Engine Crash with IIfcGrid

### ISSUE THREAD

**Issue by daveime** [xBimTeam/XbimGeometry#66]
I've come across a problem with the geometry engine and its handling of IIfcGrid entries.

The following NuGet packages (and their corresponding dependencies) are used.

Xbim.Essentials v4.0.27
Xbim.Geometry v4.0.11

I'm using the following sample code to open the model and create 3D context geometry

```
string filename = "BAD_MODEL.ifc";
IfcStore model = IfcStore.Open(filename);
Xbim3DModelContext context = new Xbim3DModelContext(model);
context.CreateContext();
```

The model opening stage completes successfully, but then the 3D context geometry creation crashes with the following exception :-

```
Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
    at BRepOffsetAPI_MakePipe.{ctor}(BRepOffsetAPI_MakePipe* , TopoDS_Wire* , TopoDS_Shape* )
    at Xbim.Geometry.XbimGeometryCreator.CreateGrid(IIfcGrid grid)
```

I've narrowed this problem down to the following lines in the IFC file :-

#4358190= IFCGRID...
#4358428= IFCGRID...
#4358609= IFCGRID...

If I manually hack the IFC file, removing these 3 lines and their references on line #28433, the 3D context geometry creation completes successfully.

Attached are links to zipped versions of the "BAD_MODEL.ifc" file, and the "BAD_MODEL_FIXED.ifc" version with the IFCGRID definitions and references removed.

[BAD_MODEL.zip](http://marikinacgi.com/IFC/BAD_MODEL.zip)
[BAD_MODEL_FIXED.zip](http://marikinacgi.com/IFC/BAD_MODEL_FIXED.zip)

Unfortunately, I don't know the source of the IFC file, how it was created / exported, and indeed if contains valid IIfcGrid data values - so it's unclear if the issue is a real bug in the geometry engine or an issue with the file itself.

Thanks
Dave Mullen

**Comment by CBenghi** [comment]
Hello Dave,
thanks for raising the issue.
I've tried to open the model with the latest Xplorer and it seems to work without problmes, the bug has probably been fixed in the develop branch.
I have had plans to merge and deploy for a while, but they always get delayed.
At this stage develop packages are more advanced than master, except WindowsUI which still needs work.
Best,
Claudio

**Comment by daveime** [comment]
Claudio,

Thanks for the prompt update and tests you did. I guess I'll have to try building the geometry engine from your source develop branch when I can find the time. I'm just lazy at heart, and rely on NuGet far more than I should.

**Comment by CBenghi** [comment]
Hello Dave,
we do have nuget for develop as well.
http://docs.xbim.net/index.html lists the urls for the develop repositories under the "Compilation" section.
Best,
Claudio
