### ISSUE TITLE
Unable to load the file or assembly  'Xbim.Geometry.Engine64'  & Uncaught Failed to fetch binary data from server.

### ISSUE THREAD

**Issue by herzim** [xBimTeam/XbimGeometry#67]
Hello,
I 'm using xbim in a web application , it work correctly but when i try to deply it on the serveur I got two errors: 
1- Unable to load the file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies. The specified file can not be found.
when I copied manuelly I get the second error 
2- Uncaught Failed to fetch binary data from server. Server code: 404. This might be due to CORS policy of your browser if you run this as a local file.

![xbim erreur](https://user-images.githubusercontent.com/3863533/28779173-21ba477e-75fa-11e7-90c6-5af02f8ecb66.PNG)

how to fix this problem please?
Thanks,

**Comment by CBenghi** [comment]
The Xbim.Geometry.Engine64.dll should be available in the /x64 subfolder of the directory where your Xbim.ModelGeometry.Scene.dll is.
If it is there and cannot be found it must be some problem with some setting on the web server.
Something like the following:
![image](https://user-images.githubusercontent.com/5476273/28971881-99638186-7925-11e7-9e22-6d30bbcf94c4.png)
I hope this helps,
Claudio

**Comment by herzim** [comment]
Thank you for your reply,
I added the geometry package with nuget and it works correctly locally but near its deployment on the server it does not copy the two folders in the bin directory. When i copy them manually the site works correctly So i do not understand why this.  but the Xbim.ModelGeometry.Scene.dll  si there.

Is there a reason or a solution for this?
Thank you in advance.

**Comment by martin1cerny** [comment]
Geometry engine native code is loaded in runtime so deployment might not recognize it as a dependency. You need to make sure your deployment workflow will pick these dlls up for publishing.
