### ISSUE TITLE
Boolean operations transform geometry to world coordinates.

### ISSUE THREAD

**Issue by jspuij** [xBimTeam/XbimGeometry#69]
First of all thank you for this library, it is very much appreciated. However I have an issue with openings and projections in the XBIM geometry library. For our application we create our own scene graph, based on the geometry that is created by XBIM while importing IFC files. The scene graph is built using relative transformations based on IfcLocalPlacement types defined in the IFC file. (see http://www.buildingsmart-tech.org/ifc/IFC4/final/html/schema/ifcgeometricconstraintresource/lexical/ifclocalplacement.htm)

This is a bit different from XbimExplorer that seems to transform vertices and normals for every shape instance to world coordinate space before populating the meshes. This of course is fine for a static viewer, but once you start manipulating objects, it becomes convenient to keep the relative transformations.

This works quite well for most geometry, but it fails on geometry that is created by performing a Boolean operation. Shape instances that are created by applying a Boolean operation all end up in world coordinates. It seems that the GetGeometryFromCache method below transforms the geometry to world coordinates:

```csharp
internal IXbimGeometryObject GetGeometryFromCache(XbimShapeInstance shapeInstance, bool makeCopy)
            {

                int ifcShapeId;
                if (GeometryShapeLookup.TryGetValue(shapeInstance.ShapeGeometryLabel, out ifcShapeId))
                {
                    IXbimGeometryObject obj;
                    if (CachedGeometries.TryGetValue(ifcShapeId, out obj))
                        return makeCopy ? obj.Transform(shapeInstance.Transformation) : obj.TransformShallow(shapeInstance.Transformation);
                } //it might be a map
                else
                {
                    GeometryReference geomRef;
                    if (ShapeLookup.TryGetValue(shapeInstance.InstanceLabel, out geomRef))
                    {
                        IXbimGeometryObject obj;
                        if (CachedGeometries.TryGetValue(geomRef.GeometryId, out obj))
                            return makeCopy ? obj.Transform(shapeInstance.Transformation) : obj.TransformShallow(shapeInstance.Transformation);
                    }
                }
                return null;
            }
```

https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L261-L282

This method is called from the AddGeometries method of XbimBooleanDefinition:

```csharp
            private void AddGeometries(XbimCreateContextHelper contextHelper, XbimGeometryEngine engine, IModel model, ConcurrentDictionary<int, bool> dupIds, IList<XbimShapeInstance> argumentIds, IList<XbimShapeInstance> cutToolIds, IList<XbimShapeInstance> projectToolIds)
            {
                bool placebo;
                _argumentGeometries = engine.CreateGeometryObjectSet();
                foreach (var argument in argumentIds)
                {

                    var geom = contextHelper.GetGeometryFromCache(argument, dupIds.TryGetValue(argument.ShapeGeometryLabel, out placebo));
                    if (geom != null)
                        _argumentGeometries.Add(geom);
                    else
                        LogWarning(model.Instances[argument.IfcProductLabel],
                       "Some 3D geometric form definition is missing"
                       );
                }

                //now build the openings
                _cutGeometries = engine.CreateSolidSet();
                foreach (var openingShape in cutToolIds)
                {
                    var openingGeom = contextHelper.GetGeometryFromCache(openingShape, dupIds.TryGetValue(openingShape.ShapeGeometryLabel, out placebo));
                    if (openingGeom != null)
                        _cutGeometries.Add(openingGeom);
                    else
                        LogWarning(model.Instances[openingShape.IfcProductLabel],
                       "Some 3D geometric form definition is missing");
                }

                //now all the projections
                _projectGeometries = engine.CreateSolidSet();

                foreach (var projectionShape in projectToolIds)
                {
                    var projGeom = contextHelper.GetGeometryFromCache(projectionShape, dupIds.TryGetValue(projectionShape.ShapeGeometryLabel, out placebo));
                    if (projGeom != null)
                        _projectGeometries.Add(projGeom);
                    else
                        LogWarning(model.Instances[projectionShape.IfcProductLabel],
                       "Some 3D geometric form definition is missing");
                }
            }
```
https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L47-L98

I haven’t found any other invocations of either GetGeometryFromCache or AddGeometries. Subsequently a new XbimShapeInstance is created with an identity matrix as transformation in:

```csharp
                                var shapeInstance = new XbimShapeInstance
                                {
                                    IfcProductLabel = elementLabel,
                                    ShapeGeometryLabel = 0,
                                    /*Set when geometry written*/
                                    StyleLabel = bop.StyleId,
                                    RepresentationType = XbimGeometryRepresentationType.OpeningsAndAdditionsIncluded,
                                    RepresentationContext = bop.ContextId,
                                    IfcTypeId = (short)typeId,
                                    Transformation = XbimMatrix3D.Identity,
                                    BoundingBox = elementGeom.BoundingBox
                                };
```

https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.ModelGeometry.Scene/Xbim3DModelContext.cs#L866-L877

To me it seems unnecessary to transform the instance to world coordinates, as the specification states:

- For IfcElement the convention applies that it shall be placed relative:
    - to the local placement of the IfcElement to which it is tied by an element composition relationship
        - for features that are located relative to the main component (such as openings), as expressed by IfcRelVoidsElement and IfcRelProjectsElement;

Even if there are any projected or voided elements, they have coordinates and/or transformations relative to the main element. The transformations of the “main” shape as defined in the placement tree, up to the level of the main shape, can be carried over to the XbimShapeInstance that is newly created at the location above.

I’ve adapted XbimGeometry to accommodate these changes, and it indeed seems to solve my problems, however since my knowledge and experience with IFC is rather limited until recently, I wonder whether I’m on the right track and not overlooking anything.
I can create a pull request with suggested changes if this is appreciated.

**Comment by SteveLockley** [comment]
The standard does say this and most BIM exporters now obey this rule, but they did not in the early days.
This approach was adopted to make a robust implementation, we could change it in the future but at the moment it is low priority as it has very little impact on performance. You can always invert the transform and move the resulting object back to ts local placement
