### ISSUE TITLE
Problem with getting Space Geometry

### ISSUE THREAD

**Issue by Primpod** [xBimTeam/XbimGeometry#7]
Sorry if this is the wrong place. I'm trying to retreive the geometry information for IFCSpace products, and having a bad time, as I can't figure out how to get this information for these objects. There's a similar issue open from in june, but the solution offered there did not work for me. What I'd like to know is if there's any way of getting a mesh out of it. I can provide a model if that's helpful. This is the kind of thing I'm trying. 

             using (XbimModel model = ParseModelFile(path, xbimFileName, false))
                {
                    var context = new Xbim3DModelContext(model);                                                   
                    IEnumerable<IfcProduct> products = model.Instances.OfType<IfcSpace>(true);                    
                     foreach (var product in products)
                     {
                        var productShape =
                            context.ShapeInstancesOf(product)
                            .Distinct();

                        if (productShape.Any())
                        {
                            //always null
                        }
                     }
                }

**Comment by andyward** [comment]
You need to create the Geometry after you get the 3DModelContext.

e.g.

```
using (XbimModel model = ParseModelFile(path, xbimFileName, false))
            {
                var context = new Xbim3DModelContext(model);       
                context.CreateContext(XbimGeometryType.PolyhedronBinary);
....
```

**Comment by Primpod** [comment]
Thanks! Looks like that was the issue.
