### ISSUE TITLE
System.Runtime.InteropServices.SEHException when calling Xbim3DModelContext.CreateContext()

### ISSUE THREAD

**Issue by jdkuhnke** [xBimTeam/XbimGeometry#70]
Hi,

first thank you for this very useful library!
We just got a new IFC2x3 file and wanted to convert the file via Xbim. For that we use the geometry engine to get the 3D coordinates. This usually works without any issue.
However, with this new file I get an Exception when calling CreateContext().

> System.Runtime.InteropServices.SEHException

This occurs in the 32-bit and the 64-bit version.
The call stack regarding to Xbim is:

>  	[Managed to Native Transition]	

>  	Xbim.Geometry.Engine64.dll!Xbim.Geometry.XbimGeometryCreator.CreateGrid(Xbim.Ifc4.Interfaces.IIfcGrid grid)	Unknown

>  	Xbim.ModelGeometry.Scene.dll!Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(Xbim.ModelGeometry.Scene.Xbim3DModelContext.XbimCreateContextHelper contextHelper, Xbim.Common.ReportProgressDelegate progDelegate, Xbim.Common.Geometry.IGeometryStoreInitialiser geometryStore, Xbim.Common.Geometry.XbimGeometryType geomStorageType) Line 1136	C#

>  	Xbim.ModelGeometry.Scene.dll!Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(Xbim.Common.ReportProgressDelegate progDelegate, bool adjustWcs) Line 678	C#

>

> ueberbau IFC.exe!ueberbau_IFC.BauelementBuilder.BauelementBuilder(Xbim.Common.IModel model) Line 37	C#

Does anyone have any idea why this is happening? So wether it is a bug or a wrong application on our part?

Here is a link to the IFC file: [RANDOM.ifc](https://drive.google.com/open?id=0B8U_qpv8r1QGbTd6a3dlRThrMUk)

To recreate this you can use following code snippet:

```
string filename = "PATH\RANDOM.ifc";
var ifcStore = IfcStore.Open(filename);
var context = new Xbim3DModelContext(ifcStore);
context.CreateContext();
```

Sincerly,
Dominik

**Comment by SteveLockley** [comment]
I have run this against the latest geometry engine in the Develop branch and cannot repeat the issue. It is now seemingly resolved and completes with no errors or warnings in the regression test.
