### ISSUE TITLE
File opens very slowly and with broken geometry models.

### ISSUE THREAD

**Issue by Artoymyp** [xBimTeam/XbimGeometry#73]
I'm trying to open the attached file using XbimExplorer from the WindowsUI master-branch. 
The 'Creating geometry' step takes enormous amount of time (~15 min). Also, the displayed geometry for some of the walls is incorrect. See the image taken using Solibri Model Viewer.
Expected 
![image](https://user-images.githubusercontent.com/12625469/30636844-634b06ba-9e18-11e7-8232-5d04cd90f258.png)
Actual
![image](https://user-images.githubusercontent.com/12625469/30637478-37d86d2c-9e1a-11e7-88ed-a3a568ac11e8.png)

[3D-MODEL.zip](https://github.com/xBimTeam/XbimGeometry/files/1317281/3D-MODEL.zip)

**Comment by CBenghi** [comment]
Yes, we are aware of issues in the geometry engine when meshing items composed of several booleans.
I've posted a branch adopting opencascade 7.2 and will try optimising that, but it might take quite some time.
Thanks for the file. I'll add the offending elements to the regression test suite.

**Comment by andyward** [comment]
Fixed v5
![image](https://user-images.githubusercontent.com/923699/49661520-2d9ecc00-fa41-11e8-8087-7fbdbb1ac3e1.png)

**Comment by Artoymyp** [comment]
Great work! 
But I can see that there is a wall on the roof on the "fixed" screenshot. And there is no such a wall on the roof on the Solibri screenshot (maybe it is hidden?). Sorry, I can't check it myself right now. Could you double check this issue instead?

**Comment by andyward** [comment]
I think you're right. That wall entity 24006 is not being clipped correctly. 

![image](https://user-images.githubusercontent.com/923699/49684798-d2b4b580-fad0-11e8-9d21-f7cbaa0e99ac.png)

**Comment by andyward** [comment]
Fixed with PR #162 

![image](https://user-images.githubusercontent.com/923699/55072898-3a910b00-5084-11e9-96e3-1d5931069917.png)
