### ISSUE TITLE
IfcTrimmedCurve case

### ISSUE THREAD

**Issue by theebow** [xBimTeam/XbimGeometry#76]
Hi team,

is there any developpement will happen in a (short^^) future to resolve the IfcTrimmedCurve case entities ?
today returning the NotImplementedException
[TrimmedCurveProblem.zip](https://github.com/xBimTeam/XbimGeometry/files/1458012/TrimmedCurveProblem.zip)
as you can test with the ifc joined file

Thanks

		void XbimEdge::Init(IIfcCurve^ curve)
		{
			IIfcLine^ line = dynamic_cast<IIfcLine^>(curve);
			if (line != nullptr) return Init(line);
			IIfcConic^ conic = dynamic_cast<IIfcConic^>(curve);
			if (conic != nullptr) return Init(conic);
			IIfcPolyline^ pline = dynamic_cast<IIfcPolyline^>(curve);
			if (pline != nullptr) return Init(pline);
			IIfcBSplineCurve^ bspline = dynamic_cast<IIfcBSplineCurve^>(curve);
			if (bspline != nullptr) return Init(bspline);
			IIfcPcurve^ pcurve = dynamic_cast<IIfcPcurve^>(curve);
			if (pcurve != nullptr) return Init(pcurve);
			throw gcnew NotImplementedException(String::Format("Curve of Type {0} in entity #{1} is not implemented", curve->GetType()->Name, curve->EntityLabel));
		}

**Comment by CBenghi** [comment]
Hello @theebow,
have you got a picture of what the shape in the attached file should look like?
Claudio

**Comment by theebow** [comment]
Hi Claudio,
(sorry i don't receive notification for your reply)
i will give you picture tomorrow ;)

**Comment by theebow** [comment]
Hi @CBenghi 
here are some pictures, one from revit, another from BimVision
Hope it 'll help you
Best regards

![trimmedcurvebimvision](https://user-images.githubusercontent.com/17316045/32884124-a32258b0-cab9-11e7-8590-b436efa3d55c.png)
![trimmedcurverevit](https://user-images.githubusercontent.com/17316045/32884127-a3434278-cab9-11e7-9df3-c3e467729181.png)

**Comment by theebow** [comment]
UP ^^

**Comment by SteveLockley** [comment]
This issue is now fixed in the V5 pending release
