### ISSUE TITLE
Reading the original, untesselated geometry from XBim

### ISSUE THREAD

**Issue by Timmitry** [xBimTeam/XbimGeometry#77]
I want to use XBim to load Ifc-Files, and then import the geometry into our application. My current example file is [OneWall.ifc](https://github.com/xBimTeam/XbimWebUI/blob/master/Xbim.WeXplorer/tests/data/OneWall.ifc).

I did succeed in importing the tesselated meshes, as [described here](https://stackoverflow.com/a/42930683/4469336).

However, since we are able to work with more complex geometry data, I would like to import the original geometry. For example, in the OneWall-file, the geometry of the wall is a swept solid (if I analysed that correctly). How would I access this geometry representation?

Thanks a lot,
Tim

**Comment by martin1cerny** [comment]
Just read the data using xBIM. 

```cs
var wall = model.Instances.FirstOrDefault<IfcWall>();
var representations = wall.Representation.Representations;
foreach (var representation in representations)
{
    var context = representation.ContextOfItems;
    var identifier = representation.RepresentationIdentifier;
    var type =  representation.RepresentationType;
    var items = representation.Items;
}
```

See [IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcproduct.htm) for details.

**Comment by Timmitry** [comment]
Thank you, that did help me!
