### ISSUE TITLE
Retrieve information from a selected object in xbimXplorer

### ISSUE THREAD

**Issue by GLFichera** [xBimTeam/XbimGeometry#78]
Hi,It's possibile to retrieve properties like Area,Volume from a selected objected in the 3D view, like a door or a wall? Thanks.

**Comment by martin1cerny** [comment]
It is possible to calculate volume and surface area of the geometry if it is a proper closed 3D solid geometry (some geometries might be just surfaces even if they appear as closed 3D volumes). It is exposed as relatively high level function of every [IXbimSolid](https://github.com/xBimTeam/XbimGeometry/blob/master/Xbim.Geometry.Engine/XbimSolid.h#L81). Also be aware that sum of surface areas of all solids which form a product might not be the area you look for.

**Comment by GLFichera** [comment]
Thank you so much. I don't know if it is the correct section but i would know if it's possibile to change the xbim xplorer language. I would change from English to Italian.

**Comment by martin1cerny** [comment]
It is better to ask in [XbimWindowsUI](https://github.com/xBimTeam/XbimWindowsUI) project because that contains all windows specific UI. Also, try to ask @CBenghi who has made most of the recent developments in this area and speaks Italian.
