### ISSUE TITLE
Guidance on net40 build

### ISSUE THREAD

**Issue by lycandroid** [xBimTeam/XbimGeometry#8]
Hi, I'm trying to build XbimGeometry for .net 4.0 but not getting very far.  Can you confirm I'm doing the right thing.

I get the Net40 branch and load Xbim.Geometry.Nuget.sln in vs2013.
Attempt build.  The NuGet package restore fails Xbim.Essentials 3.1.0:

    NuGet Package restore failed for project Xbim.Geometry.Engine.Interop: Unable to find version '3.1.0' of package 'Xbim.Essentials'..
    NuGet Package restore failed for project Xbim.ModelGeometry.Scene: Unable to find version '3.1.0' of package 'Xbim.Essentials'..
    NuGet Package restore failed for project Xbim.Geometry.Engine.Tests: Unable to find version '3.1.0' of package 'Xbim.Essentials'..
    NuGet Package restore failed for project Xbim.Geometry.Profiler: Unable to find version '3.1.0' of package 'Xbim.Essentials'..
    NuGet Package restore failed for project XbimRegression: Unable to find version '3.1.0' of package 'Xbim.Essentials'..

I don't think I want the nuget packages anyway as I think you only have the net4.5 versions on there?

So I build the net40 branch of Xbim.Essenitals, which works.
In Xbim.Geometry.Engine.Interop I replace the Xbim.Essentials DLL references with my builds.
Try build again and get:

    1>------ Skipped Build: Project: Xbim.Geometry.Engine, Configuration: Debug CarveCSG Win32 ------
    1>Project not selected to build for this solution configuration 
    2>------ Build started: Project: Xbim.Geometry.Engine.Interop, Configuration: Debug CarveCSG Any CPU ------
    2>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.Common". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
    2>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.Ifc.Extensions". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
    2>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.Ifc2x3". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
    2>C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Xbim.IO". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
    2>  BRepBuilderAPI_FastSewing.cxx
    2>  TopOpeBRepTool_PROJECT.cxx
    2>  XbimCompound.cpp
    2>  XbimCurve.cpp
    2>c:\projects\xbimteam\xbimgeometry\xbim.geometry.engine\XbimGeometryObject.h(3): error C2653: 'XbimGeometry' : is not a class or namespace name (XbimCurve.cpp)
    ...  lots more errors

I can not understand the "Could not locate the assembly" errors.  The references are correct and exist.  Is this perhaps some hangover from nuget dependencies?  Not had any luck removing the references.

Regardless, this then apparently leads to the mass of errors.

At this stage wondering if I'm doing this right or if there is a different procedure to follow?

**Comment by LloydPickering** [comment]
Try adding the development nuget feed to your package sources:

https://www.myget.org/F/xbim-develop/api/v2

Then make sure you are checking for Pre Release packages.

After that, try to add in the nuget references you need from that feed (so Xbim.Geometry)

**Comment by lycandroid** [comment]
That's great, many thanks.  That has got me a lot further along.

Part of my aim was to get it running on windows 2003 (which is limited to .NET 4), but a secondary issue has come up.   When using XbimModel.CreateFrom I get a Microsoft.Isam.Esent.Interop.EsentTaggedNotNULLException, "No non-NULL tagged columns".  This was using the Lakeside_Restaurant.ifc sample.

Using the same IFC file does not give the error on windows 8 and 10 - I have not tried other platforms.

I can fully appreciate that windows 2003 may not be a supported platform, and I'm quite happy to not target that platform if necessary.

Is windows 2003 supported?

Happy to raise this as a separate issue if you prefer.

**Comment by CBenghi** [comment]
Hi,
The issue you mention comes from Esent; unfortunately it's APIs have different implementations on various OSs.
There should be a solution to this soon enough, as we have (in the develop branch) an infrastructure to deal with multiple repository engines.
Esent and Memory are the only two in development at the moment, but more should come and you could implement your own... it's only a few tables.
I'll close this issue as Net40 should be closed, open a new one for the Esent problem if you think it's useful.
Best,
Claudio
