### ISSUE TITLE
Obtain the ifc file's build data

### ISSUE THREAD

**Issue by LoganQiong** [xBimTeam/XbimGeometry#80]
I want to get ifc file in the build data, save to the local database, how to achieve?

**Comment by martin1cerny** [comment]
I'm not sure what you mean by *build data*. But if you mean processed geometry, just use EsentModel and the geometry will be persisted in the database.

**Comment by LoganQiong** [comment]
Import the geometric model data in the ifc format file into the database for viewing

**Comment by martin1cerny** [comment]
My reply above applies. Check [XbimXplorer](https://github.com/xBimTeam/XbimWindowsUI/tree/master/XbimXplorer) for an example. It gets IFC file, processes the geometry, stores in the database and presents it to the user.

**Comment by LoganQiong** [comment]
Thanks, Martin Černý
