### ISSUE TITLE
Get IFC file basic information

### ISSUE THREAD

**Issue by LoganQiong** [xBimTeam/XbimGeometry#81]
![2017-12-22](https://user-images.githubusercontent.com/34224151/34294018-ab317abe-e741-11e7-99be-f1ef77d0b0a0.png)
How to get the build information in IFC format，Trying to get the information in the following ways, but can not get the basic information you want，for example：

            using (var model = IfcStore.Open("SampleHouse.ifc"))
            {
                var project = model.Instances.OfType<IIfcProject>().FirstOrDefault();
            }

**Comment by martin1cerny** [comment]
Can you try to be more specific about what kind of information you need to
find?

Dne 22. 12. 2017 10:56 napsal uživatel "LoganQiong" <
notifications@github.com>:

**Comment by CBenghi** [comment]
Hello @LoganQiong,
judging from the screenshot it seems to me that you are trying to get information about elements in the model.
The syntax above returns on a single entity from the model of type IfcProject.
To get all the properties of your interest you probably have to start from the instance of you choice.

```
 using (var model = IfcStore.Open("SampleHouse.ifc"))
{
     var wall = model.Instances.OfType<IIfcWallStandardCase>().FirstOrDefault();
}
```
But then you will have to navigate the relationship in IFC to get the information you want.
In your case you'll have to look at the instances of
```
var prosets = wall.IsDefinedBy.OfType<IfcRelDefinesByProperties>();
foreach (var p in propset)
{
// p.RelatingPropertyDefinition will allow you to investigate the props.
}
```
I hope this helps, but I think you should have a look at buildingSmart's documentation to understand the hierarchy better.
Best,
Claudio

**Comment by LoganQiong** [comment]
Hi  @CBenghi,
I understand what you mean, I get the structural information of the building from the following website: http://www.buildingsmart-tech.org/ifc/IFC4/Add1/html/schema/templates/spatial-composition.htm
(For example：Project-> site-> building-> building storey-> space-> element)
You mean I have to traverse each layer through this building structure code to get the information, but this project is too great, can not reach the degree of flexibility, there is no relevant example code to achieve this function!

**Comment by CBenghi** [comment]
You don't need necessarily to follow the spatial composition structure.
The code I have listed earlier goes directly to the wall (IIfcWallStandardCase), it is from there onward that you have to understand the logic of information storage in ifcPropertySets.
There is code for excel code extraction in our samples, but your query is not precise enough to help you more than this... please be more precise.
Claudio

**Comment by LoganQiong** [comment]
What I provided before is a relatively simple IFC model, whose purpose is to know how to get the structural information of IFC model. The models actually used may be more complicated, for example:
![2017-12-26](https://user-images.githubusercontent.com/34224151/34344376-387f3470-ea20-11e7-879e-d9b588f809a1.png)
