### ISSUE TITLE
Get the direction vector coordinates

### ISSUE THREAD

**Issue by LoganQiong** [xBimTeam/XbimGeometry#82]
How to get the orientation vector coordinates of the displayed model in the IFC file, like this:
![17-11-23](https://user-images.githubusercontent.com/34224151/34433685-dc4164fa-ecbb-11e7-8400-2cb33f12fd25.png)

**Comment by CBenghi** [comment]
Hello @LoganQiong,
I am sorry but the question is not clear enough for any answer.
This also applies to https://github.com/xBimTeam/XbimGeometry/issues/81
Best,
Claudio

**Comment by LoganQiong** [comment]
@CBenghi 
I found a solution, I get 4 matrix information through analysis, we can draw the position of each model position.For example: 
        static string _ifcFile = @"E:\SampleHouse.ifc";
        private static void Main(string[] args)
        {
            //获取IFC模型X、Y、Z坐标轴
            using (var model = IfcStore.Open(_ifcFile))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                //求几何模型数量
                var geometrys = context.ShapeGeometries();

                //求模型实例数量
                var instances = context.ShapeInstances();

                string jsonString = "";
                foreach (var instance in instances)
                {
                    string faces_json = "";
                    string point_json = "";

                    //求单个模型4向矩阵信息
                    _var transfor = instance.Transformation;
                    var matrixItem = transfor.ToString().Split(' ');
                    var matrix4 = JsonConvert.SerializeObject(matrixItem);_

                    var geometry = context.ShapeGeometry(instance);
                    var data = ((IXbimShapeGeometryData)geometry).ShapeData;

                    using (var stream = new MemoryStream(data))
                    {
                        using (var reader = new BinaryReader(stream))
                        {
                            var mesh = reader.ReadShapeTriangulation();

                            //查找模型所有的面
                            List<XbimFaceTriangulation> Faces = mesh.Faces as List<XbimFaceTriangulation>;
                            faces_json = JsonConvert.SerializeObject(Faces);

                            //查找模型所有的点坐标
                            List<XbimPoint3D> Point = mesh.Vertices as List<XbimPoint3D>;
                            point_json = JsonConvert.SerializeObject(Point);
                        }
                    }
                }
            }
         }
_[Resolution 4 matrix data method address](http://www.songho.ca/opengl/gl_matrix.html)_
