### ISSUE TITLE
How to obtain IFC model material attribute information

### ISSUE THREAD

**Issue by LoganQiong** [xBimTeam/XbimGeometry#84]
How do I get model material information next?

        private static void Main(string[] args)
        {
            using (var model = IfcStore.Open("SampleHouse.ifc"))
            {
                IEnumerable<IfcMaterialLayerSet> ifcMaterialLayerSets = model.FederatedInstances.OfType<IfcMaterialLayerSet>();

                foreach (IfcMaterialLayerSet ifcMaterialLayerSet in ifcMaterialLayerSets)
                {
                    foreach (IfcMaterialLayer ifcMaterialLayer in ifcMaterialLayerSet.MaterialLayers)
                    {

                    }
                }

                IEnumerable<IfcMaterial> ifcMaterials = model.FederatedInstances.OfType<IfcMaterial>();

                foreach (IfcMaterial ifcMaterial in ifcMaterials)
                {

                }
            }
        }

**Comment by martin1cerny** [comment]
Materils are more complex than this. See [IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcmaterialresource/lexical/ifcmaterialselect.htm) for more details. You might also want to consider [geometry styling](http://www.buildingsmart-tech.org/ifc/IFC2x3/TC1/html/ifcpresentationappearanceresource/lexical/ifcpresentationstyle.htm) which is independent of semantic material definitions. IFC4 offeres even [more data types](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifcmaterialselect.htm) for materials.
