### ISSUE TITLE
Add a  IfcTriangulatedFaceSet to a IFC 

### ISSUE THREAD

**Issue by GerryArk** [xBimTeam/XbimGeometry#87]
Hi xBim team 
You are doing a amazing work so far.
Just started to work with xBim  for creating ifc files  to share models. 
Above other items I need to create a  IfcTriangulatedFaceSet  object  and add it to 
the IFC shema but I have found no examples and  a bit lost on how to populate such object with triangles 
and vertex data. 
Any tip ? 

thanks

**Comment by martin1cerny** [comment]
The best resource to have a look is [IFC documentation](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/link/ifctriangulatedfaceset.htm). xBIM is 'just' a pure implementation.

**Comment by GerryArk** [comment]
Hi Martin 
Thanks, I know what I want to do but I am unable to add faceindexes  to the  IfcTriangulatedFaceSet  
done this in other libraries but here i got lost,  the data needed is part of a  interface and I was unable to find the way out.
My knowledge is in c++ so I feel a bit lost using c# I must admit

**Comment by GerryArk** [comment]
My code just if anybody could point me out 

                var mesh = model.Instances.New<IfcTriangulatedFaceSet>();
                mesh.Closed = false;
                mesh.Coordinates = model.Instances.New<IfcCartesianPointList3D>();
                var p = model.Instances.New<IfcCartesianPoint>();
                p.SetXYZ(0, 0, 0);
                mesh.Coordinates.CoordList.Add( p.Coordinates );

                p = model.Instances.New<IfcCartesianPoint>();
                p.SetXYZ(1, 0, 0);
                mesh.Coordinates.CoordList.Add(p.Coordinates);

                p = model.Instances.New<IfcCartesianPoint>();
                p.SetXYZ(1, 1, 0);
                mesh.Coordinates.CoordList.Add(p.Coordinates);

I was unable to find the wey to push triangle indices here 
mesh.CoordIndex.Add(  ????   );

**Comment by martin1cerny** [comment]
Right, I can see your confusion. There is a special function `IItemSet.GetAt(int index)` for a list of lists kind of data. It is a new feature in IFC4 and we have this special handling in place to keep it all transactional (that is why there is no `ItemSet` with public constructor). Your code would look like this:

```cs
var coordinates = model.Instances.New<IfcCartesianPointList3D>();
var mesh = model.Instances.New<IfcTriangulatedFaceSet>(fs =>
{
    fs.Closed = false;
    fs.Coordinates = coordinates;
});
var points = new double[][] {
    new [] {0d,0d,0d},
    new [] {1d,0d,0d},
    new [] {1d,1d,0d},
    new [] {0d,1d,0d},
    new [] {0d,0d,2d},
    new [] {1d,0d,2d},
    new [] {1d,1d,2d},
    new [] {0d,1d,2d}
};
var indices = new long[][] {
    new [] {1L,6L,5L},
    new [] {1L,2L,6L},
    new [] {6L,2L,7L},
    new [] {7L,2L,3L},
    new [] {7L,8L,6L},
    new [] {6L,8L,5L},
    new [] {5L,8L,1L},
    new [] {1L,8L,4L},
    new [] {4L,2L,1L},
    new [] {2L,4L,3L},
    new [] {4L,8L,7L},
    new [] {7L,3L,4L}
};
for (int i = 0; i < points.Length; i++)
{
    var values = points[i].Select(v => new IfcLengthMeasure(v));
    coordinates.CoordList.GetAt(i).AddRange(values);
}
for (int i = 0; i < indices.Length; i++)
{
    var values = indices[i].Select(v => new IfcPositiveInteger(v));
    mesh.CoordIndex.GetAt(i).AddRange(values);
}
```

This will result in
```
#24=IFCCARTESIANPOINTLIST3D(((0.,0.,0.),(1.,0.,0.),(1.,1.,0.),(0.,1.,0.),(0.,0.,2.),(1.,0.,2.),(1.,1.,2.),(0.,1.,2.)));
#25=IFCTRIANGULATEDFACESET(#24,$,.F.,((1,6,5),(1,2,6),(6,2,7),(7,2,3),(7,8,6),(6,8,5),(5,8,1),(1,8,4),(4,2,1),(2,4,3),(4,8,7),(7,3,4)),$);
```

Which is this:
![geometry result](http://www.buildingsmart-tech.org/ifc/IFC4/Add2/html/figures/ifctriangulatedfaceset_example-01.png)

**Comment by martin1cerny** [comment]
**Note:** Indices are **1 based** in IFC, not 0 based like in most languages. Make sure you handle the +1 increment if needed or you will get out of range exceptions or a broken geometry.

**Comment by GerryArk** [comment]
Thanks  Martin 
That was a great help indeed. 
I would have never solved this  without your help
