### ISSUE TITLE
Cannot compile against build of XbimEssentials from git master

### ISSUE THREAD

**Issue by todoooo** [xBimTeam/XbimGeometry#9]
I cloned and compiled XbimEssentials from the git master branch. Now I have cloned XbimGeometry and I'm trying to compile it by referencing those assemblies (not the Nuget XbimEssentials package), but the Xbim.Geometry.Engine C++ project complains about missing methods for classes implementing some of the interfaces. e.g. IXbimGeometryObject

Where can I get the updated C++ code please?

**Comment by benjymous** [comment]
The latest cutting edge code is in the 'develop' branch for each Xbim module

**Comment by SteveLockley** [comment]
Please could you hold fire we are merging the essentials 4 into essentials now we are confident it is correct.

Prof. Steve Lockley
Chair of Building Modelling
University of Northumbria
Mobile 07967 600 923

On 15 Oct 2015, at 05:10, todoooo <notifications@github.com<mailto:notifications@github.com>> wrote:


I cloned and compiled XbimEssentials from the git master branch. Now I have cloned XbimGeometry and I'm trying to compile it by referencing those assemblies (not the Nuget XbimEssentials package), but the Xbim.Geometry.Engine C++ project complains about missing methods for classes implementing some of the interfaces. e.g. IXbimGeometryObject

Where can I get the updated C++ code please?

**Comment by todoooo** [comment]
Great. I'm looking forward to that and I appreciate your work. I hope I can contribute once I get up to speed. I'm moving from Delphi to C# so fighting with Visual Studio isn't fun.

Are release/tag branches planned for xBIM? I find it unusual that the master branches should ever be broken, if they are indeed the release branches.

**Comment by CBenghi** [comment]
Just a quick heads up, I believe master is all working now.
The publication of broken master was an oversight, our policy would be to keep it stable, of course.
