### ISSUE TITLE
如何获取IFC构件模型的GuId？

### ISSUE THREAD

**Issue by LoganQiong** [xBimTeam/XbimGeometry#90]
How to get GuId built by IFC model with the following code: 
            using (var model = IfcStore.Open(_ifcFile))
            {
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var geometrys = context.ShapeGeometries();
                var instances = context.ShapeInstances();
             }

**Comment by CBenghi** [comment]
You don't need to create the the context for getting the GUID.
It's a direct property of IfcRoot entities.
