### ISSUE TITLE
[Unity] Xbim.Geometry.Engine64 not found

### ISSUE THREAD

**Issue by Vizzr** [xBimTeam/XbimGeometry#93]
First of all, great package!

The issue:
I am trying to load the IFC file back into Unity.
I can't seem to load the Geometry data of the IIfcProducts.

First the geometry had no shapeinstances, shape data... all those things.
So to fix this I called:
"var context = new Xbim3DModelContext(model);
        context.CreateContext();"

This throws the error:
"FileNotFoundException: Could not load file or assembly 'Xbim.Geometry.Engine64' or one of its dependencies"

Without this call the application has no errors, but also has no Geometry results.

I tried retrieving the geometry data in a CMD application and that works perfectly fine.

I know that in Unity you have to paste the .dlls in the Assets folder for example.
Which I did.

I read that the Xbim.Geometry.Interop depends on the Engine64 or Engine32 and that it loads from the Executable path.
I tried to paste the Engine64 and Engine32.dlls in the executable path and that did not resolve the issue.  After that I pasted both files in all paths and did also not resolve the issue.

Can someone help me with this error?

**Comment by martin1cerny** [comment]
[Here](https://github.com/xBimTeam/XbimGeometry/issues/86) is a discussion about this. I'm sorry but nobody from the core team works with Unity so your only chance is community. Successful example is shown in [here](https://github.com/xBimTeam/XbimWindowsUI/issues/62).

**Comment by Vizzr** [comment]
Thanks for the quick response.
I'll definitely check it out!

I will post an update later on

**Comment by liszto** [comment]
@martin1cerny from my side I use this setup in Unity and everything is fine : 
![image](https://user-images.githubusercontent.com/408031/36262899-0702f29e-1269-11e8-99f0-f46183fc3793.png)

**Comment by Dschoni** [comment]
@liszto is there any way to contact you directly to get a minimal working example on how to use Xbim with unity? I seem to be having the same problem as mentioned here: https://github.com/xBimTeam/XbimGeometry/issues/109 and would really like to find out, what steps have to be taken to get the `CreateContext()` to work inside unity.

**Comment by andyward** [comment]
Fix incoming in v5 relating to how we load the engine that may help resolving the native DLL

**Comment by andyward** [comment]
Closing this. Please reopen if still an issue
