### ISSUE TITLE
NotImplementedException issue during CreateContext call

### ISSUE THREAD

**Issue by liszto** [xBimTeam/XbimGeometry#94]
Hello guys,
I'm working on Unity and I try to generate a mesh within the engine by reading an ifc file.
Until I try the other which was to generate at least a wall from unity by creating an ifc file which was a success. But now I try to do the reverse one but an issue happen during the CreateContext call : 

`NotImplementedException: The method or operation is not implemented.
System.Runtime.InteropServices.Marshal.GetExceptionPointers () (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
<Module>.___CxxCallUnwindDtor (System.MonoFNPtrFakeClass pDtor, System.Void* pThis) (at <53dab193172641d196c7067894b3a595>:0)
<Module>..cctor () (at <53dab193172641d196c7067894b3a595>:0)
Rethrow as TypeInitializationException: The type initializer for '<Module>' threw an exception.
System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) (at <9c9f068c46c64ffd91fda7af157b4d15>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
Xbim.Geometry.Engine.Interop.XbimGeometryEngine..ctor () (at <d98477b9c3594ccdb43a24b8b3542994>:0)
Xbim.ModelGeometry.Scene.Xbim3DModelContext.get_Engine () (at <dbaecf0d124a446f88d862633c685e42>:0)
Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext (Xbim.Common.ReportProgressDelegate progDelegate, System.Boolean adjustWcs) (at <dbaecf0d124a446f88d862633c685e42>:0)`

I try to search why this could happen from my side but currently I don't find anything to go further :'( 

I tried to update xbim geometry repository by switching on developer branch but I have some issue with nuget package. 
But I think I don't need this cause I've already seen some people generating meshes from xbim with Unity but they didn't encounter this issue.

I tried with multiple files to be sure it wasn't a feature from it that wasn't implement from xbim side but it always failed.

Any idea about it ?

Thanks,
Aurelien.

**Comment by liszto** [comment]
@Ajes1337 I have some question for you :

Did you rebuild the dll from your side ?
If yes, which IDE did you use ? If it's Visual Studio, which version ?
Which Unity version did you use too ?
Thanks in advance, those informations could help me to debug my issue I think ! :)

**Comment by Vizzr** [comment]
@liszto 
I know the issue.
Unity uses mono.
Mono does not implement " System.Runtime.InteropServices.Marshal.GetExceptionPointers ()" 

From mono github [():](https://github.com/mono/mono/blob/813c1308fe53d16b419d22777f4d1124f06e7c9e/mcs/class/corlib/System.Runtime.InteropServices/Marshal.cs) (Line: 421)
public static IntPtr GetExceptionPointers()
{
	throw new NotImplementedException ();
}

I just don' t know how to fix it.

**Comment by liszto** [comment]
Ok thanks for this mono limitation that I didn't know until you said it.
I will check this asap. I think I can figure out to find a solution but I have to get the project from my office to check this. 
So if I have enough time this week-end i would try to fix this otherwise I will check this monday morning ;)

**Comment by Vizzr** [comment]
@liszto 
It's strange, because the github page of mono itself says that it does not implement it.
I have posted a question about the issue on the unity forums.
[https://forum.unity.com/threads/getexceptionpointers-returns-not-implemented.518175/](https://forum.unity.com/threads/getexceptionpointers-returns-not-implemented.518175/)

**Comment by martin1cerny** [comment]
Because this is not an issue of xBIM, can I close the issue?

**Comment by liszto** [comment]
Could you just let it open for a bit ?
Just in case @Ajes1337 would answer me concerning the settings from his project.
Cause it's more related to your part than unity's one due to the Visual Studio project configuration and co.

Currently I try to build your project with my visual configuration and it always failed. So it's not totally related to unity side, so I try to figure out why.

**Comment by Ajes1337** [comment]
baaaaah, I'll answer then... :b

When I made xBIM "work" with Unity, I never got it to work.. :D

The way I got the geometry into Unity was by making a small .Net program with all the xBIM stuff, and making it connect to the Unity build with TCP... So when I pressed a button in Unity, Unity opened a small .Net program with the xBIM code, and did the importing stuff, and transferred the Geometry to Unity with TCP, and closed itself down after it was done... so that was haxy, but it worked :) 

Cannot remember details, it was back in summer, and have not touched it since :/

kind regards

**Comment by liszto** [comment]
Ok ! 
Thanks for the answer I will try to find a way to solve this from my side so without the haxy TCP stuff.
So I will check if I can find a way to build successfully all the dll stuff from Visual and then import it into unity without any issue.
Currently my main concern is the Visual Studio side. Then I will check in Unity what could go wrong 💃

**Comment by liszto** [comment]
I just succeeded  to build the project with visual studio 2013. But indeed the issue is still the same in Unity.
So my first issue didn't occur due to my VS 2017 build but indeed due to mono logic.

The external .NET program used by ajes could be a solution to use. I will try something and I keep you in touch on the result :/

**Comment by Vizzr** [comment]
@liszto 
Thanks for the update.
I'm currently working on an external project as well.

**Comment by liszto** [comment]
my solution failed.
So I will adapt the code loop logic to an external apps which will be called from Unity and use the result in it.
Hopefully their new compiler stuff and co. will solve this by dropping mono stuff (maybe in 2018).
I think we can consider this topic closed now !
