### ISSUE TITLE
According to a single model instance, how to get its Guid?

### ISSUE THREAD

**Issue by LoganQiong** [xBimTeam/XbimGeometry#99]
I want to get Guid from each instance, and then spliced to the last json string, because another place need to use Guid, hope to help me! code show as below:

            using (var model = IfcStore.Open(_ifcFile))
            {
                string jsonString = "";
                var context = new Xbim3DModelContext(model);
                context.CreateContext();

                var instances = context.ShapeInstances();
                foreach (var instance in instances)
                {
                    var geometry = context.ShapeGeometry(instance);
                    var data = ((IXbimShapeGeometryData)geometry).ShapeData;

                    //==========================================================

                    //According to a single model instance, how to get its Guid?

                    //==========================================================

                    using (var stream = new MemoryStream(data))
                    {
                        using (var reader = new BinaryReader(stream))
                        {
                            var mesh = reader.ReadShapeTriangulation();

                            //get the face
                            List<XbimFaceTriangulation> Faces = mesh.Faces as List<XbimFaceTriangulation>;
                            var faces_json = JsonConvert.SerializeObject(Faces);

                            //Get the point
                            List<XbimPoint3D> Point = mesh.Vertices as List<XbimPoint3D>;
                            var point_json = JsonConvert.SerializeObject(Point);

                            jsonString += ",{\"ObjectID\":\"Guid\",\"Faces\":[" + faces_json.Substring(1) + "],\"Points\":" + point_json + "}";
                        }
                    }
                }
            }

**Comment by martin1cerny** [comment]
What kind of Guid do you want? Geometry instances don't have any Guid.

**Comment by LoganQiong** [comment]
Is GlobalId， code show as below:
[{
"GlobalId":"3Hmf6cl9j9jO5h9YDtGK95",
"text":"Basic Wall:Wall-Ext_102Bwk-75Ins-100LBlk-12P:285345 - WallStandardCase #150"
},{
"GlobalId":"3Hmf6cl9j9jO5h9YDtGKEU",
"text":"Basic Wall:Wall-Ext_102Bwk-50Air-45Ins-100DBlk-12P:285562 - WallStandardCase #257"
}]

I want to put GlobalId and Face, Point together, then what to do？

**Comment by martin1cerny** [comment]
`instance.IfcProductLabel` will give you product label. You will need to use that to get the actual product and than `product.GlobalId` will be your GUID.

**Comment by LoganQiong** [comment]
@martin1cerny 
IfcProductLabel how to get the actual product and get GlobalId, you can hint again? thank you very much!

**Comment by LoganQiong** [comment]
@martin1cerny 
I found it！thank you very much!

        using (var model = IfcStore.Open(_ifcFile))
        {
            string jsonString = "";
            var context = new Xbim3DModelContext(model);
            context.CreateContext();

            var instances = context.ShapeInstances();
            foreach (var instance in instances)
            {
                var geometry = context.ShapeGeometry(instance);
                var data = ((IXbimShapeGeometryData)geometry).ShapeData;


                //==========================================================

                    var productId = instance.IfcProductLabel;
                    IIfcProduct product = model.Instances[productId] as IIfcProduct;
                    var globalId = product.GlobalId;

                //==========================================================


                using (var stream = new MemoryStream(data))
                {
                    using (var reader = new BinaryReader(stream))
                    {
                        var mesh = reader.ReadShapeTriangulation();

                        //get the face
                        List<XbimFaceTriangulation> Faces = mesh.Faces as List<XbimFaceTriangulation>;
                        var faces_json = JsonConvert.SerializeObject(Faces);

                        //Get the point
                        List<XbimPoint3D> Point = mesh.Vertices as List<XbimPoint3D>;
                        var point_json = JsonConvert.SerializeObject(Point);

                        jsonString += ",{\"ObjectID\":\"" + globalId + "\",\"Faces\":[" + faces_json.Substring(1) + "],\"Points\":" + point_json + "}";
                    }
                }
            }
        }

**Comment by LoganQiong** [comment]
@ martin1cerny
Why have the same GlobalId?

**Comment by LoganQiong** [comment]
@martin1cerny
Why have the same GlobalId? Is this normal?

**Comment by martin1cerny** [comment]
Not sure what you mean but one product has many geometry instances (window having frame and glass panels).

**Comment by martin1cerny** [comment]
Closing, because original issue was solved.
